### ISSUE TITLE
Rendering system breaks when viewing item_rail, game crashes when viewing its tooltip.

### ISSUE THREAD

**Issue by Dunkmania101** [TeamOpenIndustry/ImmersiveRailroading#1033]
Hello! This is going to be one of those "title says it all" issues, with the exception that I'll actually include version numbers and a log!

Jokes aside, here they are (I tried to upload the entire file but it was too big for gist's liking):

`[06Aug2021 17:46:35.799] [Render thread/ERROR] [cam72cam.mod.ModCore/CATCHING]: Catching
cam72cam.mod.serialization.SerializationException: Unable to access field gauge in class class cam72cam.immersiverailroading.items.nbt.RailSettings
	at cam72cam.mod.serialization.TagSerializer.init(TagSerializer.java:68) ~[universalmodcore:1.1.2]
	at cam72cam.mod.serialization.TagSerializer.deserialize(TagSerializer.java:145) ~[universalmodcore:1.1.2]
	at cam72cam.mod.serialization.TagSerializer.deserialize(TagSerializer.java:139) ~[universalmodcore:1.1.2]
	at cam72cam.immersiverailroading.items.nbt.RailSettings.from(RailSettings.java:78) ~[immersiverailroading:1.16.5-forge-1.9.0]
	at cam72cam.immersiverailroading.util.RailInfo.<init>(RailInfo.java:98) ~[immersiverailroading:1.16.5-forge-1.9.0]
	at cam72cam.immersiverailroading.render.item.TrackBlueprintItemModel.render(TrackBlueprintItemModel.java:26) ~[immersiverailroading:1.16.5-forge-1.9.0]
	at cam72cam.immersiverailroading.render.item.TrackBlueprintItemModel.lambda$getModel$0(TrackBlueprintItemModel.java:23) ~[immersiverailroading:1.16.5-forge-1.9.0]
	at cam72cam.mod.render.StandardModel.lambda$addCustom$3(StandardModel.java:99) ~[universalmodcore:1.1.2]
	at cam72cam.mod.render.StandardModel.lambda$renderCustom$5(StandardModel.java:165) ~[universalmodcore:1.1.2]
	at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
	at cam72cam.mod.render.StandardModel.renderCustom(StandardModel.java:165) ~[universalmodcore:1.1.2]
	at cam72cam.mod.render.StandardModel.render(StandardModel.java:126) ~[universalmodcore:1.1.2]
	at cam72cam.mod.render.StandardModel.render(StandardModel.java:121) ~[universalmodcore:1.1.2]
	at cam72cam.mod.render.ItemRender$BakedItemModel.lambda$handlePerspective$0(ItemRender.java:352) ~[universalmodcore:1.1.2]
	at cam72cam.mod.render.ItemRender$2.func_239207_a_(ItemRender.java:261) ~[universalmodcore:1.1.2]
	at net.minecraft.client.renderer.ItemRenderer.func_229111_a_(ItemRenderer.java:137) ~[?:?]
	at com.mrcrayfish.obfuscate.client.Hooks.fireRenderGuiItem(Hooks.java:33) ~[obfuscate:0.6.2-1.16.3]
	at net.minecraft.client.renderer.ItemRenderer.redirect$bja000$fireRenderGuiItem(ItemRenderer.java:1020) ~[?:?]
	at net.minecraft.client.renderer.ItemRenderer.func_191962_a(ItemRenderer.java:236) ~[?:?]
	at net.minecraft.client.renderer.ItemRenderer.func_175042_a(ItemRenderer.java:212) ~[?:?]
	at com.refinedmods.refinedstorage.screen.BaseScreen.renderItem(BaseScreen.java:298) ~[refinedstorage:1.9.15]
	at com.refinedmods.refinedstorage.screen.grid.stack.ItemGridStack.draw(ItemGridStack.java:208) ~[refinedstorage:1.9.15]
	at com.refinedmods.refinedstorage.screen.grid.GridScreen.renderForeground(GridScreen.java:385) ~[refinedstorage:1.9.15]
	at com.refinedmods.refinedstorage.screen.BaseScreen.func_230451_b_(BaseScreen.java:164) ~[refinedstorage:1.9.15]
	at net.minecraft.client.gui.screen.inventory.ContainerScreen.func_230430_a_(ContainerScreen.java:122) ~[?:?]
	at com.refinedmods.refinedstorage.screen.BaseScreen.func_230430_a_(BaseScreen.java:127) ~[refinedstorage:1.9.15]
	at com.refinedmods.refinedstorage.screen.grid.GridScreen.func_230430_a_(GridScreen.java:356) ~[refinedstorage:1.9.15]
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:302) ~[forge:?]
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:492) ~[?:?]
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:976) ~[?:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) ~[?:?]
	at net.minecraft.client.main.Main.main(Main.java:184) ~[minecraft-1.16.5-client.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) ~[forge-1.16.5-36.2.2-launcher.jar:36.2]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:52) [ForgeWrapper-1.5.1.jar:1.5.1]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
Caused by: java.lang.NoSuchFieldException: modifiers
	at java.lang.Class.getDeclaredField(Class.java:2549) ~[?:?]
	at cam72cam.mod.serialization.TagSerializer.init(TagSerializer.java:64) ~[universalmodcore:1.1.2]
	... 54 more`

Immersive Railroading Version: 1.16.5-1.9.0
UniversalModCore Version: 1.16.5-1.1.2
Forge Version: 36.2.2

I suspect the issue is in the rendering of the rail item, specifically with some unknown "modifiers", whatever they may be.
Sorry if this is a duplicate issue, I saw some that looked similar but I pretty sure they weren't exactly the same.

Thanks!

**Comment by cam72cam** [comment]
Downgrade java to 1.8, I don't yet support newer versions

**Comment by Dunkmania101** [comment]
I figured I should mention that Java 11 seems to work too, as I can hover over the rail item just fine.
