### ISSUE TITLE
Crash after placing very long track blueprint (1.16.5)

### ISSUE THREAD

**Issue by biauk** [TeamOpenIndustry/ImmersiveRailroading#1046]
Tried to place blueprint of straight track with length of about 150 blocks, crashed after placing secong Golden Spike. When trying to load world again, same crash appeared instantly after loading.

---- Minecraft Crash Report ----
// Daisy, daisy...

Time: 14.08.21 18:37
Description: Ticking block entity

java.lang.NoSuchMethodError: net.minecraft.world.server.TicketManager.registerTicking(Lnet/minecraft/world/server/TicketType;Lnet/minecraft/util/math/ChunkPos;ILjava/lang/Object;)V
	at net.minecraft.world.server.ServerChunkProvider.registerTickingTicket(ServerChunkProvider.java:438) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at cam72cam.mod.world.ChunkManager.flagEntityPos(ChunkManager.java:21) ~[universalmodcore:1.1.2] {re:classloading}
	at cam72cam.mod.world.World.keepLoaded(World.java:289) ~[universalmodcore:1.1.2] {re:classloading,pl:runtimedistcleaner:A}
	at cam72cam.immersiverailroading.tile.TileRailPreview.update(TileRailPreview.java:158) ~[immersiverailroading:1.16.5-forge-1.9.0] {re:classloading}
	at cam72cam.mod.block.tile.TileEntityTickable.func_73660_a(TileEntityTickable.java:47) ~[universalmodcore:1.1.2] {re:classloading}
	at net.minecraft.world.World.func_217391_K(World.java:491) ~[?:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:371) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:immersiveengineering.mixins.json:coremods.ServerWorldMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:851) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:118) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_291] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.world.server.ServerChunkProvider.registerTickingTicket(ServerChunkProvider.java:438) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at cam72cam.mod.world.ChunkManager.flagEntityPos(ChunkManager.java:21) ~[universalmodcore:1.1.2] {re:classloading}
	at cam72cam.mod.world.World.keepLoaded(World.java:289) ~[universalmodcore:1.1.2] {re:classloading,pl:runtimedistcleaner:A}
	at cam72cam.immersiverailroading.tile.TileRailPreview.update(TileRailPreview.java:158) ~[immersiverailroading:1.16.5-forge-1.9.0] {re:classloading}
	at cam72cam.mod.block.tile.TileEntityTickable.func_73660_a(TileEntityTickable.java:47) ~[universalmodcore:1.1.2] {re:classloading}
-- Block entity being ticked --
Details:
	Name: immersiverailroading:block_rail_preview // cam72cam.mod.block.tile.TileEntityTickable
	Block: Block{immersiverailroading:block_rail_preview}
	Block location: World: (263,4,432), Chunk: (at 7,0,0 in 16,27; contains blocks 256,0,432 to 271,255,447), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Block: Block{immersiverailroading:block_rail_preview}
	Block location: World: (263,4,432), Chunk: (at 7,0,0 in 16,27; contains blocks 256,0,432 to 271,255,447), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
Stacktrace:
	at net.minecraft.world.World.func_217391_K(World.java:491) ~[?:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:371) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:immersiveengineering.mixins.json:coremods.ServerWorldMixin,pl:mixin:A}

-- Affected level --
Details:
	All players: 1 total; [ServerPlayerEntity['biauk'/15, l='ServerLevel[tester 16]', x=263.30, y=4.10, z=241.31]]
	Chunk stats: ServerChunkCache: 3118
	Level dimension: minecraft:overworld
	Level spawn location: World: (176,4,80), Chunk: (at 0,0,0 in 11,5; contains blocks 176,0,80 to 191,255,95), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 598948 game time, 127260 day time
	Level name: tester 16
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
	Level weather: Rain time: 1 (now: false), thunder time: 1 (now: false)
	Known server brands: forge
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:851) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:118) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_291] {}

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_291, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1357337936 bytes (1294 MB) / 2488381440 bytes (2373 MB) up to 5355339776 bytes (5107 MB)
	CPUs: 4
	JVM Flags: 7 total; -Xmx5G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -XX:+IgnoreUnrecognizedVMOptions
	ModLauncher: 8.0.9+86+master.3cf110c
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.2.jar mixin PLUGINSERVICE 
		/eventbus-4.0.0.jar eventbus PLUGINSERVICE 
		/forge-1.16.5-36.2.0.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.5-36.2.0.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.5-36.2.0.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.5-36.2.0.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.2.jar mixin TRANSFORMATIONSERVICE 
		/OptiFine_1.16.4_HD_U_G6.jar OptiFine TRANSFORMATIONSERVICE 
		/forge-1.16.5-36.2.0.jar fml TRANSFORMATIONSERVICE 
	FML: 36.2
	Forge: net.minecraftforge:36.2.0
	FML Language Providers: 
		javafml@36.2
		minecraft@1
	Mod List: 
		forge-1.16.5-36.2.0-client.jar                    |Minecraft                     |minecraft                     |1.16.5              |DONE      |Manifest: NOSIGNATURE
		worldedit-forge-mc1.16.3-7.2.1-dist.jar           |WorldEdit                     |worldedit                     |7.2.1+299386a       |DONE      |Manifest: NOSIGNATURE
		BiomesOPlenty-1.16.4-13.0.0.426-universal.jar     |Biomes O' Plenty              |biomesoplenty                 |1.16.4-13.0.0.426   |DONE      |Manifest: NOSIGNATURE
		MekanismTools-1.16.4-10.0.17.444.jar              |Mekanism: Tools               |mekanismtools                 |10.0.17             |DONE      |Manifest: NOSIGNATURE
		mcw-doors-1.0.3-mc1.16.5.jar                      |Macaw's Doors                 |mcwdoors                      |1.0.3               |DONE      |Manifest: NOSIGNATURE
		ImmersiveRailroading-1.16.5-forge-1.9.0.jar       |Immersive Railroading         |immersiverailroading          |1.16.5-forge-1.9.0  |DONE      |Manifest: NOSIGNATURE
		engineersdecor-1.16.4-1.1.14.jar                  |Engineer's Decor              |engineersdecor                |1.1.14              |DONE      |Manifest: bf:30:76:97:e4:58:41:61:2a:f4:30:d3:8f:4c:e3:71:1d:14:c4:a1:4e:85:36:e3:1d:aa:2f:cb:22:b0:04:9b
		mcw-furniture-2.0.1-mc1.16.5.jar                  |Macaw's Furniture             |mcwfurnitures                 |2.0.1               |DONE      |Manifest: NOSIGNATURE
		mcw-fences-1.0.0-mc1.16.5.jar                     |Macaw's Fences and Walls      |mcwfences                     |1.0.0               |DONE      |Manifest: NOSIGNATURE
		MekanismGenerators-1.16.4-10.0.17.444.jar         |Mekanism: Generators          |mekanismgenerators            |10.0.17             |DONE      |Manifest: NOSIGNATURE
		TrackAPI-1.16.4-forge-1.2.1.jar                   |TrackAPI                      |trackapi                      |1.2                 |DONE      |Manifest: NOSIGNATURE
		Mekanism-1.16.4-10.0.17.444.jar                   |Mekanism                      |mekanism                      |10.0.17             |DONE      |Manifest: NOSIGNATURE
		mcw-windows-1.0.3-mc1.16.5.jar                    |Macaw's Windows               |mcwwindows                    |1.0.3               |DONE      |Manifest: NOSIGNATURE
		ImmersivePetroleum-1.16.5-3.3.0-5.jar             |Immersive Petroleum           |immersivepetroleum            |3.3.0-5             |DONE      |Manifest: NOSIGNATURE
		ImmersiveEngineering-1.16.5-5.0.2-137.jar         |Immersive Engineering         |immersiveengineering          |1.16.5-5.0.2-137    |DONE      |Manifest: 44:39:94:cf:1d:8c:be:3c:7f:a9:ee:f4:1e:63:a5:ac:61:f9:c2:87:d5:5b:d9:d6:8c:b5:3e:96:5d:8e:3f:b7
		forge-1.16.5-36.2.0-universal.jar                 |Forge                         |forge                         |36.2.0              |DONE      |Manifest: 22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		cofh_core-1.16.4-1.2.1.jar                        |CoFH Core                     |cofh_core                     |1.2.1               |DONE      |Manifest: NOSIGNATURE
		thermal_foundation-1.16.4-1.2.0.jar               |Thermal Series                |thermal                       |1.2.0               |DONE      |Manifest: NOSIGNATURE
		thermal_expansion-1.16.4-1.2.0.jar                |Thermal Expansion             |thermal_expansion             |1.2.0               |DONE      |Manifest: NOSIGNATURE
		thermal_innovation-1.16.4-1.2.0.jar               |Thermal Innovation            |thermal_innovation            |1.2.0               |DONE      |Manifest: NOSIGNATURE
		thermal_locomotion-1.16.4-1.2.0.jar               |Thermal Locomotion            |thermal_locomotion            |1.2.0               |DONE      |Manifest: NOSIGNATURE
		thermal_cultivation-1.16.4-1.2.0.jar              |Thermal Cultivation           |thermal_cultivation           |1.2.0               |DONE      |Manifest: NOSIGNATURE
		mcw-paintings-1.0.1-mc1.16.5.jar                  |Macaw's Paintings             |mcwpaintings                  |1.0.1               |DONE      |Manifest: NOSIGNATURE
		UniversalModCore-1.16.5-forge-1.1.2.jar           |Universal Mod Core            |universalmodcore              |1.1.2               |DONE      |Manifest: NOSIGNATURE
		mcw-lights-1.0.0-mc1.16.5.jar                     |Macaw's Lights and Lamps      |mcwlights                     |1.0.0               |DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: d5191cf3-32c3-4108-89ca-548e8286855e
	Player Count: 1 / 8; [ServerPlayerEntity['biauk'/15, l='ServerLevel[tester 16]', x=263.30, y=4.10, z=241.31]]
	Data Packs: vanilla, mod:immersivepetroleum, mod:forge, mod:immersiveengineering, mod:biomesoplenty, mod:engineersdecor, mod:worldedit (incompatible), mod:cofh_core (incompatible), mod:thermal (incompatible), mod:thermal_expansion (incompatible), mod:thermal_innovation (incompatible), mod:thermal_cultivation (incompatible), mod:mekanismtools, mod:mekanismgenerators, mod:mekanism, mod:thermal_locomotion (incompatible), mod:mcwdoors, mod:mcwfurnitures, mod:mcwfences, mod:mcwwindows, mod:mcwpaintings (incompatible), mod:immersiverailroading (incompatible), mod:trackapi (incompatible), mod:universalmodcore (incompatible), mod:mcwlights (incompatible)
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'forge'
	OptiFine Version: OptiFine_1.16.4_HD_U_G6
	OptiFine Build: 20210117-001622
	Render Distance Chunks: 15
	Mipmaps: 2
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.5.13469 Compatibility Profile Context 21.19.512.4
	OpenGlRenderer: AMD Radeon (TM) R5 M430
	OpenGlVendor: ATI Technologies Inc.
	CpuCount: 4

**Comment by cam72cam** [comment]
Try upgrading Optifine

**Comment by biauk** [comment]
Problem solved. Thank you!
