### ISSUE TITLE
The player cannot enter the server after death [1.7.10]

### ISSUE THREAD

**Issue by TheBigPandaQwQ** [TeamOpenIndustry/ImmersiveRailroading#1047]
**Describe the bug**  
Running immersive railroading in Minecraft 1.7.10 server, players sometimes cannot enter the server after death.Then, the player will be disconnected immediately after entering the server and prompt "a fatal error has occurred, this connection is terminated"

**How to reproduce**  
Steps to reproduce the unwanted behavior:

 1. Kill player many times
 

**Server System Information**  
 OS: Centos Linux release 7.9
 <br>System Memory: 4gb
 <br>Allocated Memory: 3gb
 <br>IR-Version: 1.9.0_1.7.10
 <br>Forge-Version: 1.7.10-Forge10.13.4.1614-1.7.10

**Server Information**
 Server Core: Thermos-1.7.10-1614-server-ALPHA58.jar
 

**Player System Information**  
 OS: Windows10
 <br>System Memory: 8gb
 <br>Allocated Memory: 3gb
 <br>IR-Version: 1.9.0_1.7.10
 <br>Forge-Version: 1.7.10-Forge10.13.4.1614-1.7.10

**Modlist**  
 TrackAPI-1.2.jar
 ImmersiveRailroading-1.7.10-forge-1.9.0.jar
 UniversalModCore-1.7.10-forge-1.1.2.jar
 
**latest.log**
 Server log:
[20:11:21 INFO]: UUID of player xxxxxxxx is xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
[20:11:21 INFO]: Client protocol version 2 
[20:11:21 INFO]: Client attempting to join with 6 mods : FML@7.10.99.99,trackapi@1.2,Forge@10.13.4.1614,mcp@9.05,immersiverailroading@1.9.0,universalmodcore@1.1.2 
[20:11:21 INFO]: Attempting connection with missing mods [kimagine] at CLIENT 
[20:11:21 INFO]: [Server thread] Server side modded connection established 
[20:11:21 INFO]: xxxxxxxx[/xxx.xxx.xxx.xxx:xxxxx] logged in with entity id 423 at ([world] 40.0, 80.0, 248.0) 
[20:11:22 ERROR]: SimpleChannelHandlerWrapper exception 
java.lang.NullPointerException 
at cam72cam.mod.entity.Player$MovementSync.handle(Player.java:120) ~[Player$MovementSync.class:?] 
at cam72cam.mod.net.Packet$Handler.handle(Packet.java:170) ~[Packet$Handler.class:?] 
at cam72cam.mod.net.Packet$Handler.onMessage(Packet.java:153) ~[Packet$Handler.class:?] 
at cam72cam.mod.net.Packet$Handler.onMessage(Packet.java:149) ~[Packet$Handler.class:?] 
at cpw.mods.fml.common.network.simpleimpl.SimpleChannelHandlerWrapper.channelRead0(SimpleChannelHandlerWrapper.java:37) ~[SimpleChannelHandlerWrapper.class:1.7.10-1614.58] 
at cpw.mods.fml.common.network.simpleimpl.SimpleChannelHandlerWrapper.channelRead0(SimpleChannelHandlerWrapper.java:17) ~[SimpleChannelHandlerWrapper.class:1.7.10-1614.58] 
at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:98) ~[SimpleChannelInboundHandler.class:?] 
at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [DefaultChannelHandlerContext.class:?] 
at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [DefaultChannelHandlerContext.class:?] 
at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) [MessageToMessageDecoder.class:?] 
at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) [MessageToMessageCodec.class:?] 
at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [DefaultChannelHandlerContext.class:?] 
at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [DefaultChannelHandlerContext.class:?] 
at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) [DefaultChannelPipeline.class:?] 
at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) [EmbeddedChannel.class:?] 
at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77) [FMLProxyPacket.class:1.7.10-1614.58] 
at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:245) [ej.class:?] 
at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:181) [nc.class:?] 
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:1023) [MinecraftServer.class:?] 
at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:432) [lt.class:?] 
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:841) [MinecraftServer.class:?] 
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:693) [MinecraftServer.class:?] 
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_291]
[20:11:22 ERROR]: There was a critical exception handling a packet on channel cam72cam.mod 
java.lang.NullPointerException 
at cam72cam.mod.entity.Player$MovementSync.handle(Player.java:120) ~[Player$MovementSync.class:?] 
at cam72cam.mod.net.Packet$Handler.handle(Packet.java:170) ~[Packet$Handler.class:?] 
at cam72cam.mod.net.Packet$Handler.onMessage(Packet.java:153) ~[Packet$Handler.class:?] 
at cam72cam.mod.net.Packet$Handler.onMessage(Packet.java:149) ~[Packet$Handler.class:?] 
at cpw.mods.fml.common.network.simpleimpl.SimpleChannelHandlerWrapper.channelRead0(SimpleChannelHandlerWrapper.java:37) ~[SimpleChannelHandlerWrapper.class:1.7.10-1614.58] 
at cpw.mods.fml.common.network.simpleimpl.SimpleChannelHandlerWrapper.channelRead0(SimpleChannelHandlerWrapper.java:17) ~[SimpleChannelHandlerWrapper.class:1.7.10-1614.58] 
at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:98) ~[SimpleChannelInboundHandler.class:?] 
at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) ~[DefaultChannelHandlerContext.class:?] 
at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) ~[DefaultChannelHandlerContext.class:?] 
at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[MessageToMessageDecoder.class:?] 
at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) ~[MessageToMessageCodec.class:?] 
at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) ~[DefaultChannelHandlerContext.class:?] 
at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) ~[DefaultChannelHandlerContext.class:?] 
at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) ~[DefaultChannelPipeline.class:?] 
at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) ~[EmbeddedChannel.class:?] 
at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77) [FMLProxyPacket.class:1.7.10-1614.58] 
at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:245) [ej.class:?] 
at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:181) [nc.class:?] 
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:1023) [MinecraftServer.class:?] 
at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:432) [lt.class:?] 
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:841) [MinecraftServer.class:?] 
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:693) [MinecraftServer.class:?] 
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_291] 
[20:11:22 INFO]: xxxxxxxx lost connection: A fatal error has occured, this connection is terminated 
[20:11:22 INFO]: xxxxxxxx Left the game.

**Additional context**  
After testing, it is known that "ImmersiveRailroading 1.8.0-7e0f82" also has this problem
It is likely that the problem is caused by "UniversalModCore".

**Comment by cam72cam** [comment]
Give this jar a try: https://teamopenindustry.cc/maven/cam72cam/universalmodcore/UniversalModCore/1.7.10-forge-1.1.2-7287c5/UniversalModCore-1.7.10-forge-1.1.2-7287c5.jar

I plan on releasing that and some other bugfixes tonight

**Comment by TheBigPandaQwQ** [comment]
OK, thank you for your reply. I'll try it

**Comment by TheBigPandaQwQ** [comment]
I have tried this jar, and so far this problem has not occurred again.
