### ISSUE TITLE
Ticking Player (ImmersiveRailroading 1.12.2)

### ISSUE THREAD

**Issue by ItzMatttt** [TeamOpenIndustry/ImmersiveRailroading#1059]
So basicaly, every time I open my Minecraft world (with 12 mods, INCLUDING ImmersiveRailroading and all its required mods) my game would crash, the reason being 'Ticking Player'. Iv'e played with ImmersiveRailroading for some time and I have never encountered this issue. I went on Forge forums and report the issue, however someone said: "This seems to be an issue of the immersiverailroading. Try reporting it to the mod author" so here I am now. (By the way, I don't really know what "Ticking Player" even means, so yeah)

This is the crash report:

---- Minecraft Crash Report ----

WARNING: coremods are present:
  IELoadingPlugin (ImmersiveEngineering-core-0.12-89.jar)
Contact their authors BEFORE contacting forge

// I let you down. Sorry :(

Time: 8/23/21 10:29 PM
Description: Ticking player

java.lang.NullPointerException: Ticking player
	at cam72cam.immersiverailroading.entity.EntityMoveableRollingStock.getCollision(EntityMoveableRollingStock.java:96)
	at cam72cam.immersiverailroading.entity.EntityMoveableRollingStock.getCollision(EntityMoveableRollingStock.java:28)
	at cam72cam.mod.entity.ModdedEntity.func_174813_aQ(ModdedEntity.java:423)
	at net.minecraft.world.chunk.Chunk.func_177414_a(Chunk.java:900)
	at net.minecraft.world.World.func_175674_a(World.java:3028)
	at net.minecraft.world.World.func_72839_b(World.java:3011)
	at net.minecraft.entity.player.EntityPlayer.func_70636_d(EntityPlayer.java:563)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2179)
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:234)
	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:382)
	at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:173)
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:209)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:285)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:790)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at cam72cam.immersiverailroading.entity.EntityMoveableRollingStock.getCollision(EntityMoveableRollingStock.java:96)
	at cam72cam.immersiverailroading.entity.EntityMoveableRollingStock.getCollision(EntityMoveableRollingStock.java:28)
	at cam72cam.mod.entity.ModdedEntity.func_174813_aQ(ModdedEntity.java:423)
	at net.minecraft.world.chunk.Chunk.func_177414_a(Chunk.java:900)
	at net.minecraft.world.World.func_175674_a(World.java:3028)
	at net.minecraft.world.World.func_72839_b(World.java:3011)
	at net.minecraft.entity.player.EntityPlayer.func_70636_d(EntityPlayer.java:563)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2179)
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:234)

-- Player being ticked --
Details:
	Entity Type: null (net.minecraft.entity.player.EntityPlayerMP)
	Entity ID: 52
	Entity Name: ItzMatttt
	Entity's Exact location: 23.25, 30.13, 657.29
	Entity's Block location: World: (23,30,657), Chunk: (at 7,1,1 in 1,41; contains blocks 16,0,656 to 31,255,671), Region: (0,1; contains chunks 0,32 to 31,63, blocks 0,0,512 to 511,255,1023)
	Entity's Momentum: 0.00, 0.00, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:382)
	at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:173)
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:209)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:285)

-- Ticking connection --
Details:
	Connection: net.minecraft.network.NetworkManager@55b5ff6f
Stacktrace:
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:790)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1552821176 bytes (1480 MB) / 3623878656 bytes (3456 MB) up to 6442450944 bytes (6144 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx6G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2855 16 mods loaded, 16 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                   | Version        | Source                                             | Signature                                |
	|:------ |:-------------------- |:-------------- |:-------------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft            | 1.12.2         | minecraft.jar                                      | None                                     |
	| LCHIJA | mcp                  | 9.42           | minecraft.jar                                      | None                                     |
	| LCHIJA | FML                  | 8.0.99.99      | forge-1.12.2-14.23.5.2855.jar                      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge                | 14.23.5.2855   | forge-1.12.2-14.23.5.2855.jar                      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | flansmod             | 5.10.0         | Flan's+Mod-1.12.2-5.10.0 (2).jar                   | None                                     |
	| LCHIJA | trackapi             | 1.1            | TrackAPI-1.1_1.12.jar                              | None                                     |
	| LCHIJA | universalmodcore     | 1.0.1          | UniversalModCore-1.12.2-forge-1.0.1.jar            | None                                     |
	| LCHIJA | immersiverailroading | 1.8.0-7e0f82   | ImmersiveRailroading-1.12.2-forge-1.8.0-7e0f82.jar | None                                     |
	| LCHIJA | modroadworksreborn   | 0.0.3          | modroadworksreborn-0.0.3.jar                       | None                                     |
	| LCHIJA | prefab               | 1.3.1.2        | prefab-1.3.1.2.jar                                 | None                                     |
	| LCHIJA | df-roads             | 1.5.2-mc1.12.2 | Realistic-Road-Mod-1.12.2.jar                      | None                                     |
	| LCHIJA | roadworks            | 2.0.0 Beta     | Roadworks 2-1.12.2-1.0.jar                         | None                                     |
	| LCHIJA | trafficcontrol       | 0.3.5          | trafficcontrol-0.3.5.jar                           | None                                     |
	| LCHIJA | car                  | 1.2.12         | Ultimate-Car-Mod-1.12.2.jar                        | None                                     |
	| LCHIJA | worldedit            | 6.1.10         | worldedit-forge-mc1.12.2-6.1.10-dist.jar           | None                                     |
	| LCHIJA | immersiveengineering | 0.12-89        | Immersive-Engineering-Mod-1.12.2.jar               | 4cb49fcde3b43048c9889e0a3d083225da926334 |

	Loaded coremods (and transformers): 
IELoadingPlugin (ImmersiveEngineering-core-0.12-89.jar)
  blusunrize.immersiveengineering.common.asm.IEClassTransformer
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['ItzMatttt'/52, l='Immersive stuff', x=23.25, y=30.13, z=657.29]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

I thought I'd reach out to you, hoping that anyone knows how to fix it, because I really like the mod and I enjoyed playing it.
Please fix the bug (if it's infact an issue with ImmersiveRailroading) and help me trough. 

Anyways, I do still appreciate the dev's work, they have done an AZMAZING job on making the mod and I dont want that an issue like this ruins it.

Best regards,
Matt

**Comment by cam72cam** [comment]
Try updating to ImmersiveRailroading 1.9 and the latest UniversalModCore

**Comment by ItzMatttt** [comment]
Thank you, it looks like it works for now!

Appreciate it! <3
