### ISSUE TITLE
Crash ... without crash report ... again [1.16.5, Forge, Optifine]

### ISSUE THREAD

**Issue by biauk** [TeamOpenIndustry/ImmersiveRailroading#1078]
Game instantly crashed when just flying around an area, chash report didn't genereted, so I post last parts of log. This is not first time similar situation happens.

[15wrz2021 23:59:59.350] [Render thread/INFO] [STDOUT/]: [cam72cam.mod.sound.ClientSound:checkErr:45]: OpenAL Error 40965 : java.lang.Throwable
	at cam72cam.mod.sound.ClientSound.checkErr(ClientSound.java:45)
	at cam72cam.mod.sound.ClientSound.init(ClientSound.java:56)
	at cam72cam.mod.sound.ClientSound.play(ClientSound.java:89)
	at cam72cam.immersiverailroading.entity.EntityMoveableRollingStock.onTick(EntityMoveableRollingStock.java:260)
	at cam72cam.immersiverailroading.entity.EntityCoupleableRollingStock.onTick(EntityCoupleableRollingStock.java:154)
	at cam72cam.mod.entity.ModdedEntity.func_70071_h_(ModdedEntity.java:217)
	at net.minecraft.client.world.ClientWorld.func_217418_a(ClientWorld.java:252)
	at net.minecraft.world.World.func_217390_a(World.java:554)
	at net.minecraft.client.world.ClientWorld.func_217419_d(ClientWorld.java:210)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1483)
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:953)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607)
	at net.minecraft.client.main.Main.main(Main.java:184)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66)

[15wrz2021 23:59:59.350] [Render thread/INFO] [STDOUT/]: [cam72cam.mod.sound.ClientSound:checkErr:45]: OpenAL Error 40965 : java.lang.Throwable
	at cam72cam.mod.sound.ClientSound.checkErr(ClientSound.java:45)
	at cam72cam.mod.sound.ClientSound.init(ClientSound.java:56)
	at cam72cam.mod.sound.ClientSound.play(ClientSound.java:89)
	at cam72cam.immersiverailroading.entity.EntityMoveableRollingStock.onTick(EntityMoveableRollingStock.java:271)
	at cam72cam.immersiverailroading.entity.EntityCoupleableRollingStock.onTick(EntityCoupleableRollingStock.java:154)
	at cam72cam.mod.entity.ModdedEntity.func_70071_h_(ModdedEntity.java:217)
	at net.minecraft.client.world.ClientWorld.func_217418_a(ClientWorld.java:252)
	at net.minecraft.world.World.func_217390_a(World.java:554)
	at net.minecraft.client.world.ClientWorld.func_217419_d(ClientWorld.java:210)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1483)
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:953)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607)
	at net.minecraft.client.main.Main.main(Main.java:184)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66)

[15wrz2021 23:59:59.351] [Render thread/INFO] [STDOUT/]: [cam72cam.mod.sound.ClientSound:checkErr:45]: OpenAL Error 40965 : java.lang.Throwable
	at cam72cam.mod.sound.ClientSound.checkErr(ClientSound.java:45)
	at cam72cam.mod.sound.ClientSound.init(ClientSound.java:56)
	at cam72cam.mod.sound.ClientSound.play(ClientSound.java:89)
	at cam72cam.immersiverailroading.entity.EntityMoveableRollingStock.onTick(EntityMoveableRollingStock.java:260)
	at cam72cam.immersiverailroading.entity.EntityCoupleableRollingStock.onTick(EntityCoupleableRollingStock.java:154)
	at cam72cam.immersiverailroading.entity.FreightTank.onTick(FreightTank.java:138)
	at cam72cam.immersiverailroading.entity.Locomotive.onTick(Locomotive.java:153)
	at cam72cam.immersiverailroading.entity.LocomotiveDiesel.onTick(LocomotiveDiesel.java:146)
	at cam72cam.mod.entity.ModdedEntity.func_70071_h_(ModdedEntity.java:217)
	at net.minecraft.client.world.ClientWorld.func_217418_a(ClientWorld.java:252)
	at net.minecraft.world.World.func_217390_a(World.java:554)
	at net.minecraft.client.world.ClientWorld.func_217419_d(ClientWorld.java:210)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1483)
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:953)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607)
	at net.minecraft.client.main.Main.main(Main.java:184)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66)

[15wrz2021 23:59:59.351] [Render thread/INFO] [STDOUT/]: [cam72cam.mod.sound.ClientSound:checkErr:45]: OpenAL Error 40965 : java.lang.Throwable
	at cam72cam.mod.sound.ClientSound.checkErr(ClientSound.java:45)
	at cam72cam.mod.sound.ClientSound.init(ClientSound.java:56)
	at cam72cam.mod.sound.ClientSound.play(ClientSound.java:89)
	at cam72cam.immersiverailroading.entity.EntityMoveableRollingStock.onTick(EntityMoveableRollingStock.java:271)
	at cam72cam.immersiverailroading.entity.EntityCoupleableRollingStock.onTick(EntityCoupleableRollingStock.java:154)
	at cam72cam.immersiverailroading.entity.FreightTank.onTick(FreightTank.java:138)
	at cam72cam.immersiverailroading.entity.Locomotive.onTick(Locomotive.java:153)
	at cam72cam.immersiverailroading.entity.LocomotiveDiesel.onTick(LocomotiveDiesel.java:146)
	at cam72cam.mod.entity.ModdedEntity.func_70071_h_(ModdedEntity.java:217)
	at net.minecraft.client.world.ClientWorld.func_217418_a(ClientWorld.java:252)
	at net.minecraft.world.World.func_217390_a(World.java:554)
	at net.minecraft.client.world.ClientWorld.func_217419_d(ClientWorld.java:210)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1483)
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:953)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607)
	at net.minecraft.client.main.Main.main(Main.java:184)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66)

[15wrz2021 23:59:59.358] [Render thread/INFO] [STDOUT/]: [cam72cam.mod.sound.ClientSound:checkErr:45]: OpenAL Error 40965 : java.lang.Throwable
	at cam72cam.mod.sound.ClientSound.checkErr(ClientSound.java:45)
	at cam72cam.mod.sound.ClientSound.init(ClientSound.java:56)
	at cam72cam.mod.sound.ClientSound.play(ClientSound.java:89)
	at cam72cam.immersiverailroading.entity.EntityMoveableRollingStock.onTick(EntityMoveableRollingStock.java:260)
	at cam72cam.immersiverailroading.entity.EntityCoupleableRollingStock.onTick(EntityCoupleableRollingStock.java:154)
	at cam72cam.mod.entity.ModdedEntity.func_70071_h_(ModdedEntity.java:217)
	at net.minecraft.client.world.ClientWorld.func_217418_a(ClientWorld.java:252)
	at net.minecraft.world.World.func_217390_a(World.java:554)
	at net.minecraft.client.world.ClientWorld.func_217419_d(ClientWorld.java:210)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1483)
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:953)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607)
	at net.minecraft.client.main.Main.main(Main.java:184)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66)

[15wrz2021 23:59:59.359] [Render thread/INFO] [STDOUT/]: [cam72cam.mod.sound.ClientSound:checkErr:45]: OpenAL Error 40965 : java.lang.Throwable
	at cam72cam.mod.sound.ClientSound.checkErr(ClientSound.java:45)
	at cam72cam.mod.sound.ClientSound.init(ClientSound.java:56)
	at cam72cam.mod.sound.ClientSound.play(ClientSound.java:89)
	at cam72cam.immersiverailroading.entity.EntityMoveableRollingStock.onTick(EntityMoveableRollingStock.java:271)
	at cam72cam.immersiverailroading.entity.EntityCoupleableRollingStock.onTick(EntityCoupleableRollingStock.java:154)
	at cam72cam.mod.entity.ModdedEntity.func_70071_h_(ModdedEntity.java:217)
	at net.minecraft.client.world.ClientWorld.func_217418_a(ClientWorld.java:252)
	at net.minecraft.world.World.func_217390_a(World.java:554)
	at net.minecraft.client.world.ClientWorld.func_217419_d(ClientWorld.java:210)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1483)
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:953)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607)
	at net.minecraft.client.main.Main.main(Main.java:184)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66)

**Comment by biauk** [comment]
I'm not sure but there may be problem with Optifine option "Render Regions". Since I turned it off I didn't have any crash like that.

**Comment by BugfinderGameCrasher** [comment]
Try turning off VBOs

**Comment by cam72cam** [comment]
Don't follow what @BugfinderGameCrasher said

**Comment by BugfinderGameCrasher** [comment]
What? Why? I know a lot of people who use Optifine and turning off VBOs fixes a bug when trying to view or load any track, blueprint or otherwise

**Comment by cha0sbuster** [comment]
Please don't fight in the GitHub issues y'all, the rest of us get emails
about it.

**Comment by km00700** [comment]
The issue in that log is related to sound, not rendering, hence why disabling VBOs is not a solution. For the majority of systems, it's can hinder performance to disable them.

cha0sbuster, you can disable the emails by unsubscribing from notifications on the right side of this thread.

**Comment by cha0sbuster** [comment]
I mean, no, I want to keep track of actually useful updates on the issue.
You're right though, and hopefully this settles it.

**Comment by JimSkywalker** [comment]
Do you have the part of the log where you join the world? i had an issue that didn't generate a crash report with optifine on a different modpack and if it is the same issue then i might be of some help

**Comment by biauk** [comment]
I'm not an expert in reading logs, I'm not sure where loading world part certainly starts, but I think it's somewhere here: https://pastebin.com/SwxjBsUb

**Comment by cam72cam** [comment]
Fixed in the test builds
