### ISSUE TITLE
Minecraft 1.16.5 Forge Server Crash Error encoding field info in class cam72cam.immersiverailroading.tile.TileRail

### ISSUE THREAD

**Issue by Animeshnick21231** [TeamOpenIndustry/ImmersiveRailroading#1081]
---- Minecraft Crash Report ----
// This doesn't make any sense!

Time: 19.09.2021, 16:42
Description: Exception ticking world

java.lang.RuntimeException: cam72cam.mod.serialization.SerializationException: Error encoding field info in class cam72cam.immersiverailroading.tile.TileRail
	at cam72cam.mod.block.tile.TileEntity.func_189515_b(TileEntity.java:229) ~[universalmodcore:1.1.3] {re:classloading}
	at cam72cam.mod.block.tile.TileEntity.getUpdateTag(TileEntity.java:256) ~[universalmodcore:1.1.3] {re:classloading}
	at cam72cam.mod.block.tile.TileEntity.func_189518_D_(TileEntity.java:239) ~[universalmodcore:1.1.3] {re:classloading}
	at net.minecraft.world.server.ChunkHolder.func_219305_a(ChunkHolder.java:217) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.world.server.ChunkHolder.func_244385_a(ChunkHolder.java:209) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.world.server.ChunkHolder.func_244387_b(ChunkHolder.java:195) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.network.play.server.SMultiBlockChangePacket.func_244310_a(SourceFile:79) ~[?:?] {re:classloading}
	at net.minecraft.world.server.ChunkHolder.func_219274_a(ChunkHolder.java:194) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.world.server.ServerChunkProvider.func_241099_a_(ServerChunkProvider.java:355) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?] {re:computing_frames}
	at net.minecraft.world.server.ServerChunkProvider.func_217220_m(ServerChunkProvider.java:351) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.world.server.ServerChunkProvider.func_217207_a(ServerChunkProvider.java:326) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:333) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:forgeendertech:coremod,pl:mixin:APP:immersiveengineering.mixins.json:coremods.ServerWorldMixin,pl:mixin:APP:quark.mixins.json:ServerWorldMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:851) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixin.terraforged.json:common.MixinMinecraftServer,pl:mixin:APP:betterendforge.mixins.json:MinecraftServerMixin,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:291) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixin.terraforged.json:common.MixinMinecraftServer,pl:mixin:APP:betterendforge.mixins.json:MinecraftServerMixin,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixin.terraforged.json:common.MixinMinecraftServer,pl:mixin:APP:betterendforge.mixins.json:MinecraftServerMixin,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixin.terraforged.json:common.MixinMinecraftServer,pl:mixin:APP:betterendforge.mixins.json:MinecraftServerMixin,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at java.lang.Thread.run(Thread.java:832) [?:?] {}
Caused by: cam72cam.mod.serialization.SerializationException: Error encoding field info in class cam72cam.immersiverailroading.tile.TileRail
	at cam72cam.mod.serialization.TagSerializer.lambda$init$1(TagSerializer.java:108) ~[universalmodcore:1.1.3] {re:classloading}
	at cam72cam.mod.serialization.TagSerializer.lambda$init$3(TagSerializer.java:127) ~[universalmodcore:1.1.3] {re:classloading}
	at cam72cam.mod.serialization.TagSerializer.serialize(TagSerializer.java:156) ~[universalmodcore:1.1.3] {re:classloading}
	at cam72cam.mod.block.tile.TileEntity.func_189515_b(TileEntity.java:225) ~[universalmodcore:1.1.3] {re:classloading}
	... 18 more
Caused by: cam72cam.mod.serialization.SerializationException: Unable to access field settings in class class cam72cam.immersiverailroading.util.RailInfo
	at cam72cam.mod.serialization.TagSerializer.init(TagSerializer.java:68) ~[universalmodcore:1.1.3] {re:classloading}
	at cam72cam.mod.serialization.TagSerializer.serialize(TagSerializer.java:155) ~[universalmodcore:1.1.3] {re:classloading}
	at cam72cam.immersiverailroading.util.RailInfo$TagMapper.lambda$apply$0(RailInfo.java:353) ~[immersiverailroading:1.16.5-forge-1.9.1] {re:classloading}
	at cam72cam.mod.serialization.TagMapper$TagAccessor.lambda$new$0(TagMapper.java:17) ~[universalmodcore:1.1.3] {re:classloading}
	at cam72cam.mod.serialization.TagSerializer.lambda$init$1(TagSerializer.java:106) ~[universalmodcore:1.1.3] {re:classloading}
	at cam72cam.mod.serialization.TagSerializer.lambda$init$3(TagSerializer.java:127) ~[universalmodcore:1.1.3] {re:classloading}
	at cam72cam.mod.serialization.TagSerializer.serialize(TagSerializer.java:156) ~[universalmodcore:1.1.3] {re:classloading}
	at cam72cam.mod.block.tile.TileEntity.func_189515_b(TileEntity.java:225) ~[universalmodcore:1.1.3] {re:classloading}
	... 18 more
Caused by: java.lang.NoSuchFieldException: modifiers
	at java.lang.Class.getDeclaredField(Class.java:2569) ~[?:?] {}
	at cam72cam.mod.serialization.TagSerializer.init(TagSerializer.java:64) ~[universalmodcore:1.1.3] {re:classloading}
	at cam72cam.mod.serialization.TagSerializer.serialize(TagSerializer.java:155) ~[universalmodcore:1.1.3] {re:classloading}
	at cam72cam.immersiverailroading.util.RailInfo$TagMapper.lambda$apply$0(RailInfo.java:353) ~[immersiverailroading:1.16.5-forge-1.9.1] {re:classloading}
	at cam72cam.mod.serialization.TagMapper$TagAccessor.lambda$new$0(TagMapper.java:17) ~[universalmodcore:1.1.3] {re:classloading}
	at cam72cam.mod.serialization.TagSerializer.lambda$init$1(TagSerializer.java:106) ~[universalmodcore:1.1.3] {re:classloading}
	at cam72cam.mod.serialization.TagSerializer.lambda$init$3(TagSerializer.java:127) ~[universalmodcore:1.1.3] {re:classloading}
	at cam72cam.mod.serialization.TagSerializer.serialize(TagSerializer.java:156) ~[universalmodcore:1.1.3] {re:classloading}
	at cam72cam.mod.block.tile.TileEntity.func_189515_b(TileEntity.java:225) ~[universalmodcore:1.1.3] {re:classloading}
	... 18 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at cam72cam.mod.block.tile.TileEntity.func_189515_b(TileEntity.java:229) ~[universalmodcore:1.1.3] {re:classloading}
	at cam72cam.mod.block.tile.TileEntity.getUpdateTag(TileEntity.java:256) ~[universalmodcore:1.1.3] {re:classloading}
	at cam72cam.mod.block.tile.TileEntity.func_189518_D_(TileEntity.java:239) ~[universalmodcore:1.1.3] {re:classloading}
	at net.minecraft.world.server.ChunkHolder.func_219305_a(ChunkHolder.java:217) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.world.server.ChunkHolder.func_244385_a(ChunkHolder.java:209) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.world.server.ChunkHolder.func_244387_b(ChunkHolder.java:195) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.network.play.server.SMultiBlockChangePacket.func_244310_a(SourceFile:79) ~[?:?] {re:classloading}
	at net.minecraft.world.server.ChunkHolder.func_219274_a(ChunkHolder.java:194) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.world.server.ServerChunkProvider.func_241099_a_(ServerChunkProvider.java:355) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?] {re:computing_frames}
	at net.minecraft.world.server.ServerChunkProvider.func_217220_m(ServerChunkProvider.java:351) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.world.server.ServerChunkProvider.func_217207_a(ServerChunkProvider.java:326) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:333) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:forgeendertech:coremod,pl:mixin:APP:immersiveengineering.mixins.json:coremods.ServerWorldMixin,pl:mixin:APP:quark.mixins.json:ServerWorldMixin,pl:mixin:A,pl:runtimedistcleaner:A}
-- Affected level --
Details:
	All players: 1 total; [ServerPlayerEntity['petya21231'/69, l='ServerLevel[world]', x=7242.84, y=85.00, z=6785.88]]
	Chunk stats: ServerChunkCache: 3379
	Level dimension: minecraft:overworld
	Level spawn location: World: (7158,79,6553), Chunk: (at 6,4,9 in 447,409; contains blocks 7152,0,6544 to 7167,255,6559), Region: (13,12; contains chunks 416,384 to 447,415, blocks 6656,0,6144 to 7167,255,6655)
	Level time: 8301 game time, 8301 day time
	Level name: world
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Level weather: Rain time: 88326 (now: false), thunder time: 32970 (now: false)
	Known server brands: forge
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:851) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixin.terraforged.json:common.MixinMinecraftServer,pl:mixin:APP:betterendforge.mixins.json:MinecraftServerMixin,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:291) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixin.terraforged.json:common.MixinMinecraftServer,pl:mixin:APP:betterendforge.mixins.json:MinecraftServerMixin,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixin.terraforged.json:common.MixinMinecraftServer,pl:mixin:APP:betterendforge.mixins.json:MinecraftServerMixin,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixin.terraforged.json:common.MixinMinecraftServer,pl:mixin:APP:betterendforge.mixins.json:MinecraftServerMixin,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at java.lang.Thread.run(Thread.java:832) [?:?] {}

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 15.0.2, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 2094777456 bytes (1997 MB) / 6442450944 bytes (6144 MB) up to 6442450944 bytes (6144 MB)
	CPUs: 12
	JVM Flags: 2 total; -Xmx6144M -Xms6144M
	ModLauncher: 8.0.9+86+master.3cf110c
	ModLauncher launch target: fmlserver
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.2.jar mixin PLUGINSERVICE 
		/eventbus-4.0.0.jar eventbus PLUGINSERVICE 
		/forgeserver.jar object_holder_definalize PLUGINSERVICE 
		/forgeserver.jar runtime_enum_extender PLUGINSERVICE 
		/forgeserver.jar capability_inject_definalize PLUGINSERVICE 
		/accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE 
		/forgeserver.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.2.jar mixin TRANSFORMATIONSERVICE 
		/forgeserver.jar fml TRANSFORMATIONSERVICE 
	FML: 36.2
	Forge: net.minecraftforge:36.2.2
	FML Language Providers: 
		javafml@36.2
		minecraft@1
		kotlinforforge@1.15.1
	Mod List: 
		BetterDungeons-1.16.4-1.2.jar                     |YUNG's Better Dungeons        |betterdungeons                |1.16.4-1.2          |DONE      |Manifest: NOSIGNATURE
		astralsorcery-1.16-1.16.5-1.13.12.jar             |Astral Sorcery                |astralsorcery                 |1.16.5-1.13.12      |DONE      |Manifest: 45:2b:0a:49:6b:65:3b:39:a9:dd:d2:5b:55:7f:82:47:a5:1d:7a:cc:7f:a8:69:73:72:53:6f:57:4d:b2:1a:b7
		bigbrain-1.2.4.jar                                |Big Brain                     |bigbrain                      |1.2.4               |DONE      |Manifest: NOSIGNATURE
		jei-1.16.5-7.7.1.121.jar                          |Just Enough Items             |jei                           |7.7.1.121           |DONE      |Manifest: NOSIGNATURE
		SlashBlade-1.16-0.0.12.jar                        |Slash Blade                   |slashblade                    |0.0.12              |DONE      |Manifest: NOSIGNATURE
		BetterCaves-Forge-1.16.4-1.1.2.jar                |YUNG's Better Caves           |bettercaves                   |1.16.4-1.1.2        |DONE      |Manifest: NOSIGNATURE
		ForgeEndertech-1.16.5-7.2.0.0-build.0177.jar      |Forge Endertech               |forgeendertech                |7.2.0.0             |DONE      |Manifest: NOSIGNATURE
		BetterPortals-1.16.4-0.3.7.jar                    |YUNG's Better Portals         |betterportals                 |1.16.4-0.3.7        |DONE      |Manifest: NOSIGNATURE
		TerraForged-1.16.5-0.2.14.jar                     |TerraForged                   |terraforged                   |0.2.14              |DONE      |Manifest: 7b:73:d0:a2:c3:40:13:84:35:4f:c9:0e:2b:85:8c:08:ea:3c:3c:eb:f1:98:8b:5b:6e:ca:8a:a0:9a:cf:12:b3
		citadel-1.8.1-1.16.5.jar                          |Citadel                       |citadel                       |1.8.1               |DONE      |Manifest: NOSIGNATURE
		alexsmobs-1.12.0.jar                              |Alex's Mobs                   |alexsmobs                     |1.12.0              |DONE      |Manifest: NOSIGNATURE
		YungsApi-1.16.4-Forge-12.jar                      |YUNG's API                    |yungsapi                      |1.16.4-Forge-12     |DONE      |Manifest: NOSIGNATURE
		bookshelf-1.16.5-10.0.8.jar                       |Bookshelf                     |bookshelf                     |10.0.8              |DONE      |Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		mahoutsukai-1.16.5-v1.31.42.jar                   |Mahou Tsukai                  |mahoutsukai                   |1.16.5-v1.31.42     |DONE      |Manifest: NOSIGNATURE
		AdPother-1.16.5-4.1.0.0-build.0177.jar            |Pollution of the Realms       |adpother                      |4.1.0.0             |DONE      |Manifest: NOSIGNATURE
		ImmersivePetroleum-1.16.5-3.3.0-6.jar             |Immersive Petroleum           |immersivepetroleum            |3.3.0-6             |DONE      |Manifest: NOSIGNATURE
		forge-1.16.5-36.2.2-universal.jar                 |Forge                         |forge                         |36.2.2              |DONE      |Manifest: 22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		TravelersTitles-1.16.4-1.5.jar                    |Traveler's Titles             |travelerstitles               |1.16.4-1.5          |DONE      |Manifest: NOSIGNATURE
		betterendforge-1.16.4-1.6.0.jar                   |BetterEnd Forge               |betterendforge                |1.16.4-1.6.0        |DONE      |Manifest: NOSIGNATURE
		DynamicSurroundings-1.16.4-4.0.4.2.jar            |§3Dynamic Surroundings        |dsurround                     |1.16.4-4.0.4.2      |DONE      |Manifest: b4:98:14:b9:76:55:25:4f:e5:5f:4d:71:90:87:43:5b:f9:d5:3a:02:60:42:5e:da:1f:15:9c:ff:be:a9:7c:77
		structure_gel-1.16.5-1.7.7.jar                    |Structure Gel API             |structure_gel                 |1.7.7               |DONE      |Manifest: NOSIGNATURE
		forge-1.16.5-36.2.2-server.jar                    |Minecraft                     |minecraft                     |1.16.5              |DONE      |Manifest: NOSIGNATURE
		AmbientSounds_v3.1.6_mc1.16.5.jar                 |Ambient Sounds                |ambientsounds                 |3.0.3               |DONE      |Manifest: NOSIGNATURE
		ImmersiveEngineering-1.16.5-5.0.2-137 (3).jar     |Immersive Engineering         |immersiveengineering          |1.16.5-5.0.2-137    |DONE      |Manifest: 44:39:94:cf:1d:8c:be:3c:7f:a9:ee:f4:1e:63:a5:ac:61:f9:c2:87:d5:5b:d9:d6:8c:b5:3e:96:5d:8e:3f:b7
		projectvibrantjourneys-1.16.5-3.0.3.jar           |Project: Vibrant Journeys     |projectvibrantjourneys        |1.16.5-3.0.3        |DONE      |Manifest: NOSIGNATURE
		dungeons_plus-1.16.5-1.1.5.jar                    |Dungeons Plus                 |dungeons_plus                 |1.1.5               |DONE      |Manifest: NOSIGNATURE
		CreativeCore_v2.1.3_mc1.16.5.jar                  |CreativeCore                  |creativecore                  |2.0.0               |DONE      |Manifest: NOSIGNATURE
		HerdMentality-1.16.5-6.0.1.jar                    |HerdMentality                 |herdmentality                 |6.0.1               |DONE      |Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		TrackAPI-1.16.4-forge-1.2.1.jar                   |TrackAPI                      |trackapi                      |1.2                 |DONE      |Manifest: NOSIGNATURE
		flywheel-1.16-0.2.3.jar                           |Flywheel                      |flywheel                      |1.16-0.2.3          |DONE      |Manifest: NOSIGNATURE
		create-mc1.16.5_v0.3.2d.jar                       |Create                        |create                        |v0.3.2d             |DONE      |Manifest: NOSIGNATURE
		curios-forge-1.16.5-4.0.5.3.jar                   |Curios API                    |curios                        |1.16.5-4.0.5.3      |DONE      |Manifest: NOSIGNATURE
		gravestone-1.16.5-1.0.6 (1).jar                   |Gravestone Mod                |gravestone                    |1.16.5-1.0.6        |DONE      |Manifest: NOSIGNATURE
		AutoRegLib-1.6-49.jar                             |AutoRegLib                    |autoreglib                    |1.6-49              |DONE      |Manifest: NOSIGNATURE
		Quark-r2.4-316.jar                                |Quark                         |quark                         |r2.4-316            |DONE      |Manifest: NOSIGNATURE
		Regrowth-1.16.4-1.16.5-1.35.0.22.jar              |Regrowth Mod                  |regrowth                      |1.16.5-1.35.0.22    |DONE      |Manifest: NOSIGNATURE
		BetterStrongholds-1.16.4-1.2.1.jar                |YUNG's Better Strongholds     |betterstrongholds             |1.16.4-1.2.1        |DONE      |Manifest: NOSIGNATURE
		structurize-0.13.219-ALPHA-universal.jar          |Structurize                   |structurize                   |0.13.219-ALPHA      |DONE      |Manifest: NOSIGNATURE
		minecolonies-1.16.5-1.0.0-RELEASE-universal.jar   |MineColonies                  |minecolonies                  |1.0.0-RELEASE       |DONE      |Manifest: NOSIGNATURE
		ImmersiveRailroading-1.16.5-forge-1.9.1.jar       |Immersive Railroading         |immersiverailroading          |1.16.5-forge-1.9.1  |DONE      |Manifest: NOSIGNATURE
		UniversalModCore-1.16.5-forge-1.1.3.jar           |Universal Mod Core            |universalmodcore              |1.1.3               |DONE      |Manifest: NOSIGNATURE
		engineersdecor-1.16.4-1.1.14 (1).jar              |Engineer's Decor              |engineersdecor                |1.1.14              |DONE      |Manifest: bf:30:76:97:e4:58:41:61:2a:f4:30:d3:8f:4c:e3:71:1d:14:c4:a1:4e:85:36:e3:1d:aa:2f:cb:22:b0:04:9b
		observerlib-1.16.5-1.5.3.jar                      |ObserverLib                   |observerlib                   |1.16.5-1.5.3        |DONE      |Manifest: NOSIGNATURE
		ItemPhysic_v1.4.18_mc1.16.5.jar                   |ItemPhysic                    |itemphysic                    |1.6.0               |DONE      |Manifest: NOSIGNATURE
		AdChimneys-1.16.5-6.0.12.0-build.0177.jar         |Advanced Chimneys             |adchimneys                    |6.0.12.0            |DONE      |Manifest: NOSIGNATURE
		exoticbirds-1.16.4-1.1.0.jar                      |Exotic Birds                  |exoticbirds                   |1.1.0               |DONE      |Manifest: NOSIGNATURE
		CosmeticArmorReworked-1.16.5-v4.jar               |CosmeticArmorReworked         |cosmeticarmorreworked         |1.16.5-v4           |DONE      |Manifest: 5e:ed:25:99:e4:44:14:c0:dd:89:c1:a9:4c:10:b5:0d:e4:b1:52:50:45:82:13:d8:d0:32:89:67:56:57:01:53
		valhelsia_core-16.0.10.jar                        |Valhelsia Core                |valhelsia_core                |16.0.10             |DONE      |Manifest: NOSIGNATURE
		valhelsia_structures-1.16.5-0.1.5.jar             |Valhelsia Structures          |valhelsia_structures          |1.16.5-0.1.5        |DONE      |Manifest: NOSIGNATURE
		DynamicTrees-1.16.5-0.10.0-Beta24.jar             |Dynamic Trees                 |dynamictrees                  |1.16.5-0.10.0-Beta24|DONE      |Manifest: NOSIGNATURE
		DynamicTreesPlus-1.16.5-0.1.0-Beta10.jar          |Dynamic Trees Plus            |dynamictreesplus              |1.16.5-0.1.0-Beta10 |DONE      |Manifest: NOSIGNATURE
		BetterMineshafts-Forge-1.16.4-2.0.4.jar           |YUNG's Better Mineshafts      |bettermineshafts              |1.16.4-2.0.4        |DONE      |Manifest: NOSIGNATURE
		DynamicTreesTerraForged-1.16.5-1.0.0.jar          |Dynamic Trees for TerraForged |dtterraforged                 |1.16.5-1.0.0        |DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: c55fed0f-e3fb-44f6-a6fe-64c7551fa320
	Player Count: 1 / 20; [ServerPlayerEntity['petya21231'/69, l='ServerLevel[world]', x=7242.84, y=85.00, z=6785.88]]
	Data Packs: vanilla, mod:betterdungeons, mod:astralsorcery, mod:bigbrain, mod:jei, mod:slashblade (incompatible), mod:bettercaves (incompatible), mod:forgeendertech, mod:betterportals, mod:terraforged, mod:citadel (incompatible), mod:alexsmobs, mod:yungsapi, mod:bookshelf, mod:mahoutsukai (incompatible), mod:adpother, mod:immersivepetroleum, mod:forge, mod:travelerstitles, mod:betterendforge, mod:dsurround, mod:structure_gel, mod:ambientsounds, mod:immersiveengineering, mod:projectvibrantjourneys, mod:dungeons_plus, mod:creativecore, mod:herdmentality (incompatible), mod:trackapi (incompatible), mod:flywheel, mod:create, mod:curios, mod:gravestone, mod:autoreglib (incompatible), mod:quark (incompatible), mod:regrowth, mod:betterstrongholds, mod:structurize, mod:minecolonies (incompatible), mod:immersiverailroading (incompatible), mod:universalmodcore (incompatible), mod:engineersdecor, mod:observerlib, mod:itemphysic, mod:adchimneys, mod:exoticbirds, mod:cosmeticarmorreworked (incompatible), mod:valhelsia_core, mod:valhelsia_structures, mod:dynamictrees, mod:dynamictreesplus, mod:bettermineshafts, mod:dtterraforged
	Is Modded: Definitely; Server brand changed to 'forge'
	Type: Dedicated Server (map_server.txt)

**Comment by Animeshnick21231** [comment]
The crash occurs only on the server in a single player game everything is fine

**Comment by cam72cam** [comment]
Downgrade to java 1.8

**Comment by Animeshnick21231** [comment]
> Переход на Java 1.8

But I already have java 1.8.0_144.
What exactly do you mean ?
