### ISSUE TITLE
Placing a locomotive or rolling stock on tracks crashes my game.

### ISSUE THREAD

**Issue by BlueMoon32** [TeamOpenIndustry/ImmersiveRailroading#1123]
Whenever I place a locomotive or rolling stock on tracks, (I'm on 1.16.5 btw.) It just crashes my game.

When it crashes, minecraft launcher comes up and says:

The game crashed whilst exception in server tick loop
Error: java.lang.NoSuchMethodError: net.minecraft.world.server.TicketManager.registerTicking(Lnet/minecraft/world/server/TicketType;Lnet/minecraft/util/math/ChunkPos;ILjava/lang/Object;)V
Exit Code: -1

The crash report says:

---- Minecraft Crash Report ----
// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 12/20/21 2:32 PM
Description: Exception in server tick loop

java.lang.NoSuchMethodError: net.minecraft.world.server.TicketManager.registerTicking(Lnet/minecraft/world/server/TicketType;Lnet/minecraft/util/math/ChunkPos;ILjava/lang/Object;)V
	at net.minecraft.world.server.ServerChunkProvider.registerTickingTicket(ServerChunkProvider.java:438) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at cam72cam.mod.world.ChunkManager.flagEntityPos(ChunkManager.java:21) ~[?:1.1.3] {re:classloading}
	at cam72cam.mod.world.World.keepLoaded(World.java:289) ~[?:1.1.3] {re:classloading,pl:runtimedistcleaner:A}
	at cam72cam.immersiverailroading.entity.EntityCoupleableRollingStock.lambda$static$0(EntityCoupleableRollingStock.java:44) ~[?:1.16.5-forge-1.9.1] {re:classloading}
	at cam72cam.immersiverailroading.entity.EntityCoupleableRollingStock$$Lambda$3394/1060236531.accept(Unknown Source) ~[?:?] {}
	at cam72cam.mod.world.World.lambda$null$2(World.java:108) ~[?:1.1.3] {re:classloading,pl:runtimedistcleaner:A}
	at cam72cam.mod.world.World$$Lambda$6884/937298011.accept(Unknown Source) ~[?:?] {}
	at java.util.ArrayList.forEach(ArrayList.java:1249) ~[?:1.8.0_51] {re:computing_frames}
	at cam72cam.mod.world.World.lambda$registerEvents$3(World.java:108) ~[?:1.1.3] {re:classloading,pl:runtimedistcleaner:A}
	at cam72cam.mod.world.World$$Lambda$3592/35619333.accept(Unknown Source) ~[?:?] {}
	at cam72cam.mod.event.CommonEvents$EventBusForge.lambda$onWorldTick$3(CommonEvents.java:82) ~[?:1.1.3] {re:classloading}
	at cam72cam.mod.event.CommonEvents$EventBusForge$$Lambda$6883/2012736285.accept(Unknown Source) ~[?:?] {}
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:1.8.0_51] {}
	at cam72cam.mod.event.Event.execute(Event.java:24) ~[?:1.1.3] {re:classloading}
	at cam72cam.mod.event.CommonEvents$EventBusForge.onWorldTick(CommonEvents.java:82) ~[?:1.1.3] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_39_EventBusForge_onWorldTick_WorldTickEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus$$Lambda$3233/494799407.invoke(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.fml.hooks.BasicEventHooks.onPreWorldTick(BasicEventHooks.java:95) ~[?:?] {re:classloading}
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:848) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:118) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) [?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) [?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer$$Lambda$6548/704611578.run(Unknown Source) [?:?] {}
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 350070432 bytes (333 MB) / 1375731712 bytes (1312 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 12
	JVM Flags: 10 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -XX:+IgnoreUnrecognizedVMOptions -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 8.0.9+86+master.3cf110c
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.4.jar mixin PLUGINSERVICE 
		/eventbus-4.0.0.jar eventbus PLUGINSERVICE 
		/forge-1.16.5-36.2.20.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.5-36.2.20.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.5-36.2.20.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.5-36.2.20.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.4.jar mixin TRANSFORMATIONSERVICE 
		/OptiFine_1.16.5_HD_U_G6.jar OptiFine TRANSFORMATIONSERVICE 
		/OptiForge-MC1.16.5-0.5.0.jar optiforge TRANSFORMATIONSERVICE 
		/forge-1.16.5-36.2.20.jar fml TRANSFORMATIONSERVICE 
		/OptiForge-MC1.16.5-0.5.0.jar FakeOptiFine TRANSFORMATIONSERVICE 
		/OptiForge-MC1.16.5-0.5.0.jar optiforgewrapper TRANSFORMATIONSERVICE 
	FML: 36.2
	Forge: net.minecraftforge:36.2.20
	FML Language Providers: 
		javafml@36.2
		minecraft@1
	Mod List: 
		forge-1.16.5-36.2.20-client.jar                   |Minecraft                     |minecraft                     |1.16.5              |DONE      |Manifest: NOSIGNATURE
		OptiForge-MC1.16.5-0.5.0.jar                      |OptiForge                     |optiforge                     |0.5.0               |DONE      |Manifest: NOSIGNATURE
		TrackAPI-1.16.4-forge-1.2.1.jar                   |TrackAPI                      |trackapi                      |1.2                 |DONE      |Manifest: NOSIGNATURE
		forge-1.16.5-36.2.20-universal.jar                |Forge                         |forge                         |36.2.20             |DONE      |Manifest: 22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		ImmersiveEngineering-1.16.5-5.0.6-141.jar         |Immersive Engineering         |immersiveengineering          |1.16.5-5.0.6-141    |DONE      |Manifest: 44:39:94:cf:1d:8c:be:3c:7f:a9:ee:f4:1e:63:a5:ac:61:f9:c2:87:d5:5b:d9:d6:8c:b5:3e:96:5d:8e:3f:b7
		ImmersiveRailroading-1.16.5-forge-1.9.1.jar       |Immersive Railroading         |immersiverailroading          |1.16.5-forge-1.9.1  |DONE      |Manifest: NOSIGNATURE
		UniversalModCore-1.16.5-forge-1.1.3.jar           |Universal Mod Core            |universalmodcore              |1.1.3               |DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: dc648860-bcaa-41c7-98fa-cb8743e78510
	Player Count: 1 / 8; [ServerPlayerEntity['Little_Kitten__'/45, l='ServerLevel[Train]', x=-149.38, y=4.10, z=150.56]]
	Data Packs: vanilla, mod:optiforge, mod:trackapi (incompatible), mod:forge, mod:immersiveengineering, mod:immersiverailroading (incompatible), mod:universalmodcore (incompatible)
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'forge'
	OptiFine Version: OptiFine_1.16.5_HD_U_G6
	OptiFine Build: 20210117-013236
	Render Distance Chunks: 20
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 442.50
	OpenGlRenderer: Quadro P2200/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 12

**Comment by nbsp1221** [comment]
Did you solve it? I had the same problem, but I solved it now by upgrading OptiFine. https://github.com/TeamOpenIndustry/ImmersiveRailroading/issues/1046
