### ISSUE TITLE
Rail doesn't save settngs

### ISSUE THREAD

**Issue by BananaBlu77** [TeamOpenIndustry/ImmersiveRailroading#1130]
When I right click a rail in my hand, the GUI appears, i customize the rail sattings and then i press ESC to return to game, but the rail has the default settings: it hasn't saved my settings.
This only happens in multiplayer, in single player it works well.

Server details:
MC Version: 1.12.2
Server Type: Magma 1.12.2 (Forge + Paper)

Error:

[17:45:45] [Server thread/FATAL] [net.minecraft.server.MinecraftServer]: Error executing task
 java.util.concurrent.ExecutionException: java.lang.NullPointerException
        at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_212]
        at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_212]
        at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:926) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:461) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:865) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:737) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
Caused by: java.lang.NullPointerException
        at cam72cam.immersiverailroading.net.ItemRailUpdatePacket.handle(ItemRailUpdatePacket.java:39) ~[ItemRailUpdatePacket.class:?]
        at cam72cam.mod.net.Packet$Handler.handle(Packet.java:165) ~[Packet$Handler.class:?]
        at cam72cam.mod.net.Packet$Handler.lambda$onMessage$0(Packet.java:153) ~[Packet$Handler.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_212]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_212]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
        ... 5 more

**Comment by km00700** [comment]
You need to hit ENTER to exit with new settings. ESC just exits without saving. ESC sometimes works on SP because it doesn't need to send the update to a dedicated server.

**Comment by BananaBlu77** [comment]
Either when i hit ENTER it doesn't save settings

**Comment by km00700** [comment]
Then that's a bug with Magma not forwarding the update packet to the IR instance on the server. Generally, IR is incompatible with plugin server jars unless they forward all (not just vanilla) packets.
