### ISSUE TITLE
Error loading models on Forge Server, Crashes on Rail Placement

### ISSUE THREAD

**Issue by Ghost295** [TeamOpenIndustry/ImmersiveRailroading#1139]
Forge Version: 36.2.23
Server Java Version: 16.0.1 2021-04-20
Mod List:
- ImmersiveEngineering-1.16.5-5.0.7-143
- ImmersivePetroleum-1.16.5-3.3.0-11
- ImmersiveRailroading-1.16.5-forge-1.9.1
- jei-1.16.5-7.7.1.145
- journeymap-1.16.5-5.7.3
- TrackAPI-1.16.4-forge-1.2.1
- UniversalModCore-1.16.5-forge-1.1.3

`
[18Jan2022 20:59:27.965] [ImmersiveRailroading-1/INFO] [cam72cam.mod.ModCore/]: Loading Models 11% : rolling_stock/passenger/br_coach_mk1.json
[18Jan2022 20:59:28.925] [ImmersiveRailroading-1/ERROR] [cam72cam.mod.ModCore/]: Error loading model rolling_stock/passenger/b70baggage.json of type passenger
[18Jan2022 20:59:28.925] [ImmersiveRailroading-1/ERROR] [cam72cam.mod.ModCore/CATCHING]: Catching
java.lang.RuntimeException: cam72cam.mod.serialization.SerializationException: Unable to access field name in class class cam72cam.mod.model.obj.OBJGroup
	at cam72cam.mod.model.obj.OBJModel.lambda$null$3(OBJModel.java:71) ~[?:?]
	at cam72cam.mod.serialization.TagCompound.lambda$setList$19(TagCompound.java:239) ~[?:?]
	at cam72cam.mod.serialization.TagCompound.setter(TagCompound.java:57) ~[?:?]
	at cam72cam.mod.serialization.TagCompound.setList(TagCompound.java:235) ~[?:?]
	at cam72cam.mod.model.obj.OBJModel.lambda$new$4(OBJModel.java:65) ~[?:?]
	at cam72cam.mod.serialization.ResourceCache.getResource(ResourceCache.java:105) ~[?:?]
	at cam72cam.mod.model.obj.OBJModel.<init>(OBJModel.java:54) ~[?:?]
	at cam72cam.immersiverailroading.model.StockModel.<init>(StockModel.java:36) ~[?:?]
	at cam72cam.immersiverailroading.registry.EntityRollingStockDefinition.createModel(EntityRollingStockDefinition.java:485) ~[?:?]
	at cam72cam.immersiverailroading.registry.EntityRollingStockDefinition.<init>(EntityRollingStockDefinition.java:89) ~[?:?]
	at cam72cam.immersiverailroading.registry.CarPassengerDefinition.<init>(CarPassengerDefinition.java:9) ~[?:?]
	at cam72cam.immersiverailroading.registry.DefinitionManager.lambda$initModels$3(DefinitionManager.java:187) ~[?:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
	at java.util.stream.ReduceOps$ReduceTask.doLeaf(ReduceOps.java:952) ~[?:?]
	at java.util.stream.ReduceOps$ReduceTask.doLeaf(ReduceOps.java:926) ~[?:?]
	at java.util.stream.AbstractTask.compute(AbstractTask.java:327) ~[?:?]
	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:746) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:295) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.helpCC(ForkJoinPool.java:1116) ~[?:?]
	at java.util.concurrent.ForkJoinPool.awaitJoin(ForkJoinPool.java:1696) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doInvoke(ForkJoinTask.java:416) ~[?:?]
	at java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:741) ~[?:?]
	at java.util.stream.ReduceOps$ReduceOp.evaluateParallel(ReduceOps.java:919) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233) ~[?:?]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682) ~[?:?]
	at cam72cam.immersiverailroading.registry.DefinitionManager.initModels(DefinitionManager.java:200) ~[?:?]
	at cam72cam.immersiverailroading.registry.DefinitionManager.lambda$initDefinitions$2(DefinitionManager.java:121) ~[?:?]
	at java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1414) [?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:295) [?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016) [?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665) [?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598) [?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183) [?:?]
Caused by: cam72cam.mod.serialization.SerializationException: Unable to access field name in class class cam72cam.mod.model.obj.OBJGroup
	at cam72cam.mod.serialization.TagSerializer.init(TagSerializer.java:68) ~[?:?]
	at cam72cam.mod.serialization.TagSerializer.serialize(TagSerializer.java:155) ~[?:?]
	at cam72cam.mod.model.obj.OBJModel.lambda$null$3(OBJModel.java:68) ~[?:?]
	... 35 more

Caused by: java.lang.NoSuchFieldException: modifiers
	at java.lang.Class.getDeclaredField(Class.java:2549) ~[?:?]
	at cam72cam.mod.serialization.TagSerializer.init(TagSerializer.java:64) ~[?:?]
	at cam72cam.mod.serialization.TagSerializer.serialize(TagSerializer.java:155) ~[?:?]
	at cam72cam.mod.model.obj.OBJModel.lambda$null$3(OBJModel.java:68) ~[?:?]
	... 35 more
`

When I try in a singleplayer world it works but the same mods on a Forge Server can't load the models and crashes when placing rails.

**Comment by Ghost295** [comment]
Fixed the problem by using java 8 on the server
