### ISSUE TITLE
My Game Crashes When I Try Use The Switch On 1.16.5

### ISSUE THREAD

**Issue by Trainman4472** [TeamOpenIndustry/ImmersiveRailroading#1141]
My Game Crashes When I Try Use The Switch. I Go Into The Track Blueprint Editor And Click Switch But When I Press Enter To Leave It Crashes. This Doesn’t Happen With The Trains Or Other Tracks Just The Switch. Please Help

**Comment by km00700** [comment]
Send the crash report, please.

**Comment by Trainman4472** [comment]
Never mind found the cause if you press enter while changing the angle it crashes

**Comment by km00700** [comment]
but can you send the crash report, please? It helps us diagnose the bug that causes that issue.

**Comment by Trainman4472** [comment]
![image](https://user-images.githubusercontent.com/98214346/150637237-9afc5d83-9dab-4197-8405-6ca55c6d5b16.jpg)

**Comment by km00700** [comment]
that's not the crash report. The crash report is in the .minecraft/crash-reports folder

**Comment by Trainman4472** [comment]
--- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 22/01/22 11:39
Description: keyPressed event handler

java.lang.NullPointerException: keyPressed event handler
	at net.minecraft.client.gui.widget.button.Button.func_230930_b_(SourceFile:33) ~[?:?] {re:classloading}
	at net.minecraft.client.gui.widget.button.AbstractButton.func_231046_a_(SourceFile:26) ~[?:?] {re:classloading}
	at net.minecraft.client.gui.INestedGuiEventHandler.func_231046_a_(SourceFile:64) ~[?:?] {re:computing_frames,re:classloading}
	at net.minecraft.client.gui.screen.Screen.func_231046_a_(Screen.java:93) ~[?:?] {re:computing_frames,pl:runtimedistcleaner:A,re:classloading,pl:runtimedistcleaner:A}
	at cam72cam.mod.gui.screen.ScreenBuilder.func_231046_a_(ScreenBuilder.java:124) ~[?:1.1.3] {re:classloading}
	at net.minecraft.client.KeyboardListener.lambda$keyPress$4(KeyboardListener.java:302) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.KeyboardListener$$Lambda$7382/276434540.run(Unknown Source) ~[?:?] {}
	at net.minecraft.client.gui.screen.Screen.func_231153_a_(Screen.java:427) ~[?:?] {re:computing_frames,pl:runtimedistcleaner:A,re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.KeyboardListener.func_197961_a(KeyboardListener.java:293) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.KeyboardListener.func_228003_c_(KeyboardListener.java:391) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.KeyboardListener$$Lambda$7259/1333825399.run(Unknown Source) ~[?:?] {}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.execute(SourceFile:94) ~[?:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.client.KeyboardListener.func_228001_b_(KeyboardListener.java:390) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.KeyboardListener$$Lambda$2880/1493104631.invoke(Unknown Source) ~[?:?] {}
	at org.lwjgl.glfw.GLFWKeyCallbackI.callback(GLFWKeyCallbackI.java:37) ~[lwjgl-glfw-3.2.2.jar:build 10] {}
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.2.2.jar:build 10] {}
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101) ~[lwjgl-glfw-3.2.2.jar:build 10] {}
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(SourceFile:109) ~[?:?] {re:classloading}
	at net.minecraft.client.MainWindow.func_227802_e_(MainWindow.java:305) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:997) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.5-36.2.23.jar:36.2] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$463/943165647.call(Unknown Source) [forge-1.16.5-36.2.23.jar:36.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.client.gui.widget.button.Button.func_230930_b_(SourceFile:33) ~[?:?] {re:classloading}
	at net.minecraft.client.gui.widget.button.AbstractButton.func_231046_a_(SourceFile:26) ~[?:?] {re:classloading}
	at net.minecraft.client.gui.INestedGuiEventHandler.func_231046_a_(SourceFile:64) ~[?:?] {re:computing_frames,re:classloading}
	at net.minecraft.client.gui.screen.Screen.func_231046_a_(Screen.java:93) ~[?:?] {re:computing_frames,pl:runtimedistcleaner:A,re:classloading,pl:runtimedistcleaner:A}
	at cam72cam.mod.gui.screen.ScreenBuilder.func_231046_a_(ScreenBuilder.java:124) ~[?:1.1.3] {re:classloading}
	at net.minecraft.client.KeyboardListener.lambda$keyPress$4(KeyboardListener.java:302) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.KeyboardListener$$Lambda$7382/276434540.run(Unknown Source) ~[?:?] {}
-- Affected screen --
Details:
	Screen name: cam72cam.mod.gui.screen.ScreenBuilder
Stacktrace:
	at net.minecraft.client.gui.screen.Screen.func_231153_a_(Screen.java:427) ~[?:?] {re:computing_frames,pl:runtimedistcleaner:A,re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.KeyboardListener.func_197961_a(KeyboardListener.java:293) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.KeyboardListener.func_228003_c_(KeyboardListener.java:391) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.KeyboardListener$$Lambda$7259/1333825399.run(Unknown Source) ~[?:?] {}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.execute(SourceFile:94) ~[?:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.client.KeyboardListener.func_228001_b_(KeyboardListener.java:390) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.KeyboardListener$$Lambda$2880/1493104631.invoke(Unknown Source) ~[?:?] {}
	at org.lwjgl.glfw.GLFWKeyCallbackI.callback(GLFWKeyCallbackI.java:37) ~[lwjgl-glfw-3.2.2.jar:build 10] {}
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.2.2.jar:build 10] {}
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101) ~[lwjgl-glfw-3.2.2.jar:build 10] {}
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(SourceFile:109) ~[?:?] {re:classloading}


-- Affected level --
Details:
	All players: 1 total; [ClientPlayerEntity['YeetMaster756'/1, l='ClientLevel', x=199.90, y=4.00, z=-66.15]]
	Chunk stats: Client Chunk Cache: 841, 552
	Level dimension: minecraft:overworld
	Level spawn location: World: (208,4,-80), Chunk: (at 0,0,0 in 13,-5; contains blocks 208,0,-80 to 223,255,-65), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Level time: 11220 game time, 11220 day time
	Server brand: forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.world.ClientWorld.func_72914_a(ClientWorld.java:447) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2031) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:623) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.5-36.2.23.jar:36.2] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$463/943165647.call(Unknown Source) [forge-1.16.5-36.2.23.jar:36.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {}


-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 491840200 bytes (469 MB) / 1107296256 bytes (1056 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 8
	JVM Flags: 10 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -XX:+IgnoreUnrecognizedVMOptions -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 8.0.9+86+master.3cf110c
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.4.jar mixin PLUGINSERVICE 
		/eventbus-4.0.0.jar eventbus PLUGINSERVICE 
		/forge-1.16.5-36.2.23.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.5-36.2.23.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.5-36.2.23.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.5-36.2.23.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.4.jar mixin TRANSFORMATIONSERVICE 
		/forge-1.16.5-36.2.23.jar fml TRANSFORMATIONSERVICE 
	FML: 36.2
	Forge: net.minecraftforge:36.2.23
	FML Language Providers: 
		javafml@36.2
		minecraft@1
	Mod List: 
		forge-1.16.5-36.2.23-client.jar                   |Minecraft                     |minecraft                     |1.16.5              |DONE      |Manifest: NOSIGNATURE
		TrackAPI-1.16.4-forge-1.2.1.jar                   |TrackAPI                      |trackapi                      |1.2                 |DONE      |Manifest: NOSIGNATURE
		forge-1.16.5-36.2.23-universal.jar                |Forge                         |forge                         |36.2.23             |DONE      |Manifest: 22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		ImmersiveEngineering-1.16.5-5.0.7-143 (1).jar     |Immersive Engineering         |immersiveengineering          |1.16.5-5.0.7-143    |DONE      |Manifest: 44:39:94:cf:1d:8c:be:3c:7f:a9:ee:f4:1e:63:a5:ac:61:f9:c2:87:d5:5b:d9:d6:8c:b5:3e:96:5d:8e:3f:b7
		ImmersiveRailroading-1.16.5-forge-1.9.1.jar       |Immersive Railroading         |immersiverailroading          |1.16.5-forge-1.9.1  |DONE      |Manifest: NOSIGNATURE
		UniversalModCore-1.16.5-forge-1.1.3.jar           |Universal Mod Core            |universalmodcore              |1.1.3               |DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: dd63ddd9-9e99-4b2e-a3a8-a87608cb61c6
	Launched Version: 1.16.5-forge-36.2.23
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: Intel(R) UHD Graphics 630 GL version 4.6.0 - Build 27.20.100.8190, Intel
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: 
	Current Language: English (US)
	CPU: 8x Intel(R) Core(TM) i3-10100 CPU @ 3.60GHz

**Comment by km00700** [comment]
That's it! Thanks!

**Comment by km00700** [comment]
reopened for tracking.
