### ISSUE TITLE
Minecraft Mod Crash

### ISSUE THREAD

**Issue by Floopydoodle** [TeamOpenIndustry/ImmersiveRailroading#1145]
I am trying to play a fnaf minecraft mod but it crashes every time I start it, the crashing log is this.
 
---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3

Time: 1/29/22 8:39 PM
Description: Initializing game

java.lang.NoClassDefFoundError: net/soggymustache/fnaf/client/model/entity/ModelWitheredFreddy
	at net.soggymustache.fnaf.client.render.entity.RenderWitheredFreddy$RenderFactory.createRenderFor(RenderWitheredFreddy.java:32)
	at net.minecraftforge.fml.client.registry.RenderingRegistry.register(RenderingRegistry.java:77)
	at net.minecraftforge.fml.client.registry.RenderingRegistry.loadEntityRenderers(RenderingRegistry.java:70)
	at net.minecraft.client.renderer.entity.RenderManager.<init>(RenderManager.java:230)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:518)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: net.soggymustache.fnaf.client.model.entity.ModelWitheredFreddy
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 13 more
Caused by: java.lang.NoClassDefFoundError: net/soggymustache/bookworm/client/animation/part/BookwormModelBase
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 15 more
Caused by: java.lang.ClassNotFoundException: net.soggymustache.bookworm.client.animation.part.BookwormModelBase
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 19 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.soggymustache.fnaf.client.render.entity.RenderWitheredFreddy$RenderFactory.createRenderFor(RenderWitheredFreddy.java:32)
	at net.minecraftforge.fml.client.registry.RenderingRegistry.register(RenderingRegistry.java:77)
	at net.minecraftforge.fml.client.registry.RenderingRegistry.loadEntityRenderers(RenderingRegistry.java:70)
	at net.minecraft.client.renderer.entity.RenderManager.<init>(RenderManager.java:230)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:518)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 594077536 bytes (566 MB) / 939524096 bytes (896 MB) up to 21474836480 bytes (20480 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx20G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2855 5 mods loaded, 5 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID        | Version      | Source                              | Signature                                |
	|:----- |:--------- |:------------ |:----------------------------------- |:---------------------------------------- |
	| LCH   | minecraft | 1.12.2       | minecraft.jar                       | None                                     |
	| LCH   | mcp       | 9.42         | minecraft.jar                       | None                                     |
	| LCH   | FML       | 8.0.99.99    | forge-1.12.2-14.23.5.2855.jar       | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | forge     | 14.23.5.2855 | forge-1.12.2-14.23.5.2855.jar       | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | fnaf      | 1.12.2-V12   | FNaFUniverseMod_1.12.2-Release2.jar | None                                     |

	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 456.71' Renderer: 'GeForce GTX 1050 Ti/PCIe/SSE2'
	Launched Version: 1.12.2-forge-14.23.5.2855
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 1050 Ti/PCIe/SSE2 GL version 4.6.0 NVIDIA 456.71, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: Quark Programmer Art.zip (incompatible)
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i7-2600 CPU @ 3.40GHz

**Comment by cam72cam** [comment]
This is not related in any way to Immersive Railroading
