### ISSUE TITLE
Instant crash in creative inventory, failed to render item_rail

### ISSUE THREAD

**Issue by Enderbyte09** [TeamOpenIndustry/ImmersiveRailroading#1160]
When I try to access the creative inventory, as soon as I click the "page 2" button, it instantly crashes because it cannot render immersiverailroading:item_rail. I am on 1.16.5 and have all dependencies installed.
This is the crash report: 
17:15:31] [Render thread/INFO] [STDOUT/]: [net.minecraft.util.registry.Bootstrap:func_179870_a:123]: ---- Minecraft Crash Report ----
// My bad.

Time: 2022-02-25, 5:15 p.m.
Description: Rendering item

java.util.NoSuchElementException: No value present
	at java.util.Optional.get(Optional.java:143) ~[?:?] {}
	at cam72cam.immersiverailroading.registry.DefinitionManager.getTrack(DefinitionManager.java:304) ~[immersiverailroading:1.16.5-forge-1.9.1] {re:classloading}
	at cam72cam.immersiverailroading.registry.DefinitionManager.getTrack(DefinitionManager.java:298) ~[immersiverailroading:1.16.5-forge-1.9.1] {re:classloading}
	at cam72cam.immersiverailroading.render.rail.RailBuilderRender.renderRailBuilder(RailBuilderRender.java:29) ~[immersiverailroading:1.16.5-forge-1.9.1] {re:classloading}
	at cam72cam.immersiverailroading.render.item.TrackBlueprintItemModel.render(TrackBlueprintItemModel.java:58) ~[immersiverailroading:1.16.5-forge-1.9.1] {re:classloading}
	at cam72cam.immersiverailroading.render.item.TrackBlueprintItemModel.lambda$getModel$0(TrackBlueprintItemModel.java:23) ~[immersiverailroading:1.16.5-forge-1.9.1] {re:classloading}
	at cam72cam.mod.render.StandardModel.lambda$addCustom$3(StandardModel.java:99) ~[universalmodcore:1.1.3] {re:classloading}
	at cam72cam.mod.render.StandardModel.lambda$renderCustom$5(StandardModel.java:165) ~[universalmodcore:1.1.3] {re:classloading}
	at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?] {}
	at cam72cam.mod.render.StandardModel.renderCustom(StandardModel.java:165) ~[universalmodcore:1.1.3] {re:classloading}
	at cam72cam.mod.render.StandardModel.render(StandardModel.java:126) ~[universalmodcore:1.1.3] {re:classloading}
	at cam72cam.mod.render.StandardModel.render(StandardModel.java:121) ~[universalmodcore:1.1.3] {re:classloading}
	at cam72cam.mod.render.ItemRender$BakedItemModel.lambda$handlePerspective$0(ItemRender.java:352) ~[universalmodcore:1.1.3] {re:classloading}
	at cam72cam.mod.render.ItemRender$2.func_239207_a_(ItemRender.java:261) ~[universalmodcore:1.1.3] {re:classloading}
	at net.minecraft.client.renderer.ItemRenderer.func_229111_a_(ItemRenderer.java:137) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.ItemRenderer.func_191962_a(ItemRenderer.java:236) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.ItemRenderer.func_239387_b_(ItemRenderer.java:265) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.ItemRenderer.func_184391_a(ItemRenderer.java:257) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screen.inventory.ContainerScreen.func_238746_a_(ContainerScreen.java:237) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screen.inventory.ContainerScreen.func_230430_a_(ContainerScreen.java:106) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.DisplayEffectsScreen.func_230430_a_(DisplayEffectsScreen.java:48) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screen.inventory.CreativeScreen.func_230430_a_(CreativeScreen.java:608) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraftforge.client.ForgeHooksClient.drawScreenInternal(ForgeHooksClient.java:370) ~[forge:?] {re:classloading}
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:363) ~[forge:?] {re:classloading}
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:492) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:977) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) ~[minecraft-1.16.5-client.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) ~[forge-1.16.5-36.2.20-launcher.jar:36.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:57) [ForgeWrapper-mmc3.jar:mmc3] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210) [NewLaunch.jar:?] {}
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245) [NewLaunch.jar:?] {}
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?] {}
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at java.util.Optional.get(Optional.java:143) ~[?:?] {}
	at cam72cam.immersiverailroading.registry.DefinitionManager.getTrack(DefinitionManager.java:304) ~[immersiverailroading:1.16.5-forge-1.9.1] {re:classloading}
	at cam72cam.immersiverailroading.registry.DefinitionManager.getTrack(DefinitionManager.java:298) ~[immersiverailroading:1.16.5-forge-1.9.1] {re:classloading}
	at cam72cam.immersiverailroading.render.rail.RailBuilderRender.renderRailBuilder(RailBuilderRender.java:29) ~[immersiverailroading:1.16.5-forge-1.9.1] {re:classloading}
	at cam72cam.immersiverailroading.render.item.TrackBlueprintItemModel.render(TrackBlueprintItemModel.java:58) ~[immersiverailroading:1.16.5-forge-1.9.1] {re:classloading}
	at cam72cam.immersiverailroading.render.item.TrackBlueprintItemModel.lambda$getModel$0(TrackBlueprintItemModel.java:23) ~[immersiverailroading:1.16.5-forge-1.9.1] {re:classloading}
	at cam72cam.mod.render.StandardModel.lambda$addCustom$3(StandardModel.java:99) ~[universalmodcore:1.1.3] {re:classloading}
	at cam72cam.mod.render.StandardModel.lambda$renderCustom$5(StandardModel.java:165) ~[universalmodcore:1.1.3] {re:classloading}
	at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?] {}
	at cam72cam.mod.render.StandardModel.renderCustom(StandardModel.java:165) ~[universalmodcore:1.1.3] {re:classloading}
	at cam72cam.mod.render.StandardModel.render(StandardModel.java:126) ~[universalmodcore:1.1.3] {re:classloading}
	at cam72cam.mod.render.StandardModel.render(StandardModel.java:121) ~[universalmodcore:1.1.3] {re:classloading}
	at cam72cam.mod.render.ItemRender$BakedItemModel.lambda$handlePerspective$0(ItemRender.java:352) ~[universalmodcore:1.1.3] {re:classloading}
	at cam72cam.mod.render.ItemRender$2.func_239207_a_(ItemRender.java:261) ~[universalmodcore:1.1.3] {re:classloading}
	at net.minecraft.client.renderer.ItemRenderer.func_229111_a_(ItemRenderer.java:137) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.ItemRenderer.func_191962_a(ItemRenderer.java:236) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
-- Item being rendered --
Details:
	Item Type: item_rail
	Registry Name: immersiverailroading:item_rail
	Item Damage: 0
	Item NBT: {}
	Item Foil: false
Stacktrace:
	at net.minecraft.client.renderer.ItemRenderer.func_239387_b_(ItemRenderer.java:265) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.ItemRenderer.func_184391_a(ItemRenderer.java:257) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screen.inventory.ContainerScreen.func_238746_a_(ContainerScreen.java:237) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screen.inventory.ContainerScreen.func_230430_a_(ContainerScreen.java:106) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.DisplayEffectsScreen.func_230430_a_(DisplayEffectsScreen.java:48) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screen.inventory.CreativeScreen.func_230430_a_(CreativeScreen.java:608) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraftforge.client.ForgeHooksClient.drawScreenInternal(ForgeHooksClient.java:370) ~[forge:?] {re:classloading}
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:363) ~[forge:?] {re:classloading}

-- Screen render details --
Details:
	Screen name: net.minecraft.client.gui.screen.inventory.CreativeScreen
	Mouse location: Scaled: (300, 41). Absolute: (600.000000, 82.000000)
	Screen size: Scaled: (427, 240). Absolute: (854, 480). Scale factor of 2.000000

-- Affected level --
Details:
	All players: 1 total; [ClientPlayerEntity['Enderbyte09'/208, l='ClientLevel', x=-144.50, y=64.00, z=177.50]]
	Chunk stats: Client Chunk Cache: 841, 529
	Level dimension: minecraft:overworld
	Level spawn location: World: (-144,64,176), Chunk: (at 0,4,0 in -9,11; contains blocks -144,0,176 to -129,255,191), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 642 game time, 642 day time
	Server brand: forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.world.ClientWorld.func_72914_a(ClientWorld.java:447) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2031) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:623) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) ~[minecraft-1.16.5-client.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) ~[forge-1.16.5-36.2.20-launcher.jar:36.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:57) [ForgeWrapper-mmc3.jar:mmc3] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210) [NewLaunch.jar:?] {}
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245) [NewLaunch.jar:?] {}
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?] {}
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?] {}

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.1, Eclipse Adoptium
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Eclipse Adoptium
	Memory: 511485192 bytes (487 MB) / 1080033280 bytes (1030 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 4
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx2048m
	ModLauncher: 8.0.9+86+master.3cf110c
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.4.jar mixin PLUGINSERVICE 
		/eventbus-4.0.0.jar eventbus PLUGINSERVICE 
		/forge-1.16.5-36.2.20-launcher.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.5-36.2.20-launcher.jar runtime_enum_extender PLUGINSERVICE 
		/forge-1.16.5-36.2.20-launcher.jar capability_inject_definalize PLUGINSERVICE 
		/accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.5-36.2.20-launcher.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.4.jar mixin TRANSFORMATIONSERVICE 
		/forge-1.16.5-36.2.20-launcher.jar fml TRANSFORMATIONSERVICE 
	FML: 36.2
	Forge: net.minecraftforge:36.2.20
	FML Language Providers: 
		javafml@36.2
		minecraft@1
	Mod List: 
		forge-1.16.5-36.2.20-client.jar                   |Minecraft                     |minecraft                     |1.16.5              |DONE      |Manifest: NOSIGNATURE
		TrackAPI-1.16.4-forge-1.2.1.jar                   |TrackAPI                      |trackapi                      |1.2                 |DONE      |Manifest: NOSIGNATURE
		forge-1.16.5-36.2.20-universal.jar                |Forge                         |forge                         |36.2.20             |DONE      |Manifest: 22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		worldedit-mod-7.2.5-dist.jar                      |WorldEdit                     |worldedit                     |7.2.5+57d5ac9       |DONE      |Manifest: NOSIGNATURE
		ImmersiveRailroading-1.16.5-forge-1.9.1.jar       |Immersive Railroading         |immersiverailroading          |1.16.5-forge-1.9.1  |DONE      |Manifest: NOSIGNATURE
		UniversalModCore-1.16.5-forge-1.1.3.jar           |Universal Mod Core            |universalmodcore              |1.1.3               |DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: e3cf7294-d965-4798-a31e-a95dc782f08f
	Launched Version: MultiMC5
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: Intel(R) HD Graphics 620 GL version 4.6.0 - Build 27.20.100.8682, Intel
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: 
	Current Language: English (US)
	CPU: 4x Intel(R) Core(TM) i5-7300U CPU @ 2.60GHz
[17:15:31] [Render thread/INFO] [STDOUT/]: [net.minecraft.util.registry.Bootstrap:func_179870_a:123]: #@!@# Game crashed! Crash report saved to: #@!@# C:\Users\Enderbyte09\mmc-stable-win32\MultiMC\instances\TRAINZ\.minecraft\crash-reports\crash-2022-02-25_17.15.31-client.txt

**Comment by km00700** [comment]
You need to run MC with Java 8, it's currently using Java 17

**Comment by DejaVuMan** [comment]
@km00700 Are there any plans on moving to a newer JRE version? It's a difficult process depending on implementation speaking from my own experience, so I imagine no one expects anything soon, but support for newer JRE versions would be great and allow using Shenandoah or ZGC

**Comment by cam72cam** [comment]
It's in the works, but I abuse some parts of java 8 that were removed in later versions of java
