### ISSUE TITLE
Model won't load

### ISSUE THREAD

**Issue by NeonJeo** [TeamOpenIndustry/ImmersiveRailroading#1283]
**Describe the bug**  
Model won't load in game
 
**Expected behavior**  
My train is meant to show

[05:08:15] [ImmersiveRailroading-6/ERROR]: Error loading model rolling_stock/locomotives/shinkansen.json of type locomotives
[05:08:15] [ImmersiveRailroading-6/ERROR]: Catching
java.lang.NullPointerException: null
	at cam72cam.immersiverailroading.registry.LocomotiveDefinition.parseJson(LocomotiveDefinition.java:39) ~[LocomotiveDefinition.class:?]
	at cam72cam.immersiverailroading.registry.LocomotiveSteamDefinition.parseJson(LocomotiveSteamDefinition.java:42) ~[LocomotiveSteamDefinition.class:?]
	at cam72cam.immersiverailroading.registry.EntityRollingStockDefinition.<init>(EntityRollingStockDefinition.java:87) ~[EntityRollingStockDefinition.class:?]
	at cam72cam.immersiverailroading.registry.FreightDefinition.<init>(FreightDefinition.java:13) ~[FreightDefinition.class:?]
	at cam72cam.immersiverailroading.registry.LocomotiveDefinition.<init>(LocomotiveDefinition.java:24) ~[LocomotiveDefinition.class:?]
	at cam72cam.immersiverailroading.registry.LocomotiveSteamDefinition.<init>(LocomotiveSteamDefinition.java:32) ~[LocomotiveSteamDefinition.class:?]
	at cam72cam.immersiverailroading.registry.DefinitionManager.lambda$static$0(DefinitionManager.java:44) ~[DefinitionManager.class:?]
	at cam72cam.immersiverailroading.registry.DefinitionManager$$Lambda$285/1796582862.apply(Unknown Source) ~[?:?]
	at cam72cam.immersiverailroading.registry.DefinitionManager.lambda$initModels$3(DefinitionManager.java:187) [DefinitionManager.class:?]
	at cam72cam.immersiverailroading.registry.DefinitionManager$$Lambda$294/1734413827.apply(Unknown Source) [DefinitionManager.class:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) [?:1.8.0_51]
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948) [?:1.8.0_51]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512) [?:1.8.0_51]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502) [?:1.8.0_51]
	at java.util.stream.ReduceOps$ReduceTask.doLeaf(ReduceOps.java:747) [?:1.8.0_51]
	at java.util.stream.ReduceOps$ReduceTask.doLeaf(ReduceOps.java:721) [?:1.8.0_51]
	at java.util.stream.AbstractTask.compute(AbstractTask.java:316) [?:1.8.0_51]
	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731) [?:1.8.0_51]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) [?:1.8.0_51]
	at java.util.concurrent.ForkJoinPool$WorkQueue.execLocalTasks(ForkJoinPool.java:1040) [?:1.8.0_51]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1058) [?:1.8.0_51]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689) [?:1.8.0_51]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) [?:1.8.0_51]

**Comment by NeonJeo** [comment]
help asap please

**Comment by NeonJeo** [comment]
ive alreadyh checked the json with jsonlint

**Comment by km00700** [comment]
NullPointerException. The json is referencing something that's not there.

**Comment by Larky2k** [comment]
also did you export using legacy in blender
