### ISSUE TITLE
Casting basin crash when trying to change settings

### ISSUE THREAD

**Issue by dstnkota** [TeamOpenIndustry/ImmersiveRailroading#1364]
I try to change the guage on the casting basin and this happens. Anyone know why? I even turned off all other mods off so I was only using Immersive Engineering and Immersive Railroading. 
--- Minecraft Crash Report ----
// Why did you do that?

Time: 4/8/23 11:34 AM
Description: Updating screen events

java.lang.NullPointerException: Updating screen events
	at cam72cam.mod.item.ItemStack.clearTagCompound(ItemStack.java:156)
	at cam72cam.immersiverailroading.gui.CastingGUI.sendItemPacket(CastingGUI.java:162)
	at cam72cam.immersiverailroading.gui.CastingGUI.access$400(CastingGUI.java:28)
	at cam72cam.immersiverailroading.gui.CastingGUI$2.onClick(CastingGUI.java:91)
	at cam72cam.mod.gui.screen.ScreenBuilder.func_73864_a(ScreenBuilder.java:136)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:296)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:268)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1640)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at cam72cam.mod.item.ItemStack.clearTagCompound(ItemStack.java:156)
	at cam72cam.immersiverailroading.gui.CastingGUI.sendItemPacket(CastingGUI.java:162)
	at cam72cam.immersiverailroading.gui.CastingGUI.access$400(CastingGUI.java:28)
	at cam72cam.immersiverailroading.gui.CastingGUI$2.onClick(CastingGUI.java:91)
	at cam72cam.mod.gui.screen.ScreenBuilder.func_73864_a(ScreenBuilder.java:136)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:296)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:268)

-- Affected screen --
Details:
	Screen name: cam72cam.mod.gui.screen.ScreenBuilder

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityClientPlayerMP['Kotadstn'/2415, l='MpServer', x=-315.07, y=82.62, z=119.75]]
	Chunk stats: MultiplayerChunkCache: 587, 587
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (44,64,244), Chunk: (at 12,4,4 in 2,15; contains blocks 32,0,240 to 47,255,255), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 5310 game time, 5310 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 71 total; [EntityChicken['Chicken'/8224, l='MpServer', x=-308.44, y=62.39, z=160.44], EntityChicken['Chicken'/8225, l='MpServer', x=-300.53, y=72.00, z=148.53], EntityChicken['Chicken'/8226, l='MpServer', x=-295.47, y=74.00, z=150.41], EntityChicken['Chicken'/8227, l='MpServer', x=-298.53, y=69.00, z=159.56], EntityPig['Pig'/8228, l='MpServer', x=-310.75, y=65.00, z=143.91], EntityPig['Pig'/8229, l='MpServer', x=-295.31, y=77.00, z=143.50], EntityPig['Pig'/8230, l='MpServer', x=-305.47, y=66.00, z=150.53], EntityPig['Pig'/8231, l='MpServer', x=-302.94, y=70.00, z=150.59], EntityChicken['Chicken'/8232, l='MpServer', x=-299.41, y=101.00, z=67.53], EntityChicken['Chicken'/8233, l='MpServer', x=-298.50, y=103.00, z=69.50], EntityChicken['Chicken'/8234, l='MpServer', x=-298.50, y=93.00, z=64.50], EntityChicken['Chicken'/8235, l='MpServer', x=-297.50, y=90.00, z=63.50], EntityChicken['Chicken'/8563, l='MpServer', x=-317.47, y=77.00, z=127.53], EntityChicken['Chicken'/8564, l='MpServer', x=-327.41, y=75.00, z=118.63], EntityChicken['Chicken'/8566, l='MpServer', x=-326.47, y=75.00, z=99.53], EntityPig['Pig'/8567, l='MpServer', x=-314.94, y=77.00, z=107.09], EntityPig['Pig'/8568, l='MpServer', x=-327.97, y=63.00, z=133.03], EntityPig['Pig'/8569, l='MpServer', x=-333.03, y=67.00, z=116.63], EntityPig['Pig'/8570, l='MpServer', x=-328.47, y=72.95, z=114.49], EntityClientPlayerMP['Kotadstn'/2415, l='MpServer', x=-315.07, y=82.62, z=119.75], EntityBat['Bat'/12765, l='MpServer', x=-287.74, y=17.56, z=45.59], EntityChicken['Chicken'/10793, l='MpServer', x=-362.50, y=76.00, z=194.50], EntityChicken['Chicken'/10794, l='MpServer', x=-365.50, y=76.00, z=193.50], EntityChicken['Chicken'/10795, l='MpServer', x=-365.50, y=76.00, z=192.50], EntityChicken['Chicken'/10796, l='MpServer', x=-367.50, y=76.00, z=192.50], EntityChicken['Chicken'/10801, l='MpServer', x=-373.50, y=77.00, z=128.50], EntityChicken['Chicken'/10802, l='MpServer', x=-381.78, y=68.00, z=122.53], EntityChicken['Chicken'/10803, l='MpServer', x=-373.50, y=79.00, z=130.50], EntityChicken['Chicken'/10804, l='MpServer', x=-375.50, y=79.00, z=134.50], EntityChicken['Chicken'/8869, l='MpServer', x=-341.50, y=76.00, z=184.50], EntityChicken['Chicken'/8870, l='MpServer', x=-341.50, y=76.00, z=184.50], EntityChicken['Chicken'/8871, l='MpServer', x=-335.47, y=77.00, z=176.59], EntityChicken['Chicken'/8872, l='MpServer', x=-332.59, y=77.00, z=188.44], EntityCow['Cow'/10973, l='MpServer', x=-393.03, y=73.00, z=191.91], EntityCow['Cow'/10974, l='MpServer', x=-383.50, y=73.00, z=180.50], EntityCow['Cow'/10975, l='MpServer', x=-384.19, y=74.00, z=182.19], EntityChicken['Chicken'/10981, l='MpServer', x=-385.50, y=76.00, z=71.50], EntityChicken['Chicken'/10982, l='MpServer', x=-380.59, y=77.00, z=76.41], EntityChicken['Chicken'/10983, l='MpServer', x=-377.50, y=76.00, z=70.50], EntityChicken['Chicken'/10984, l='MpServer', x=-368.47, y=77.00, z=67.59], EntityChicken['Chicken'/9091, l='MpServer', x=-333.50, y=77.00, z=175.50], EntityChicken['Chicken'/9092, l='MpServer', x=-324.63, y=77.00, z=184.41], EntityChicken['Chicken'/9093, l='MpServer', x=-331.50, y=77.00, z=173.50], EntityChicken['Chicken'/9094, l='MpServer', x=-335.44, y=77.00, z=174.44], EntityItem['item.item.feather'/13199, l='MpServer', x=-329.41, y=71.13, z=115.53], EntityItem['item.item.chickenRaw'/13200, l='MpServer', x=-330.94, y=70.13, z=114.84], EntityBat['Bat'/13251, l='MpServer', x=-359.26, y=30.58, z=53.96], EntityBat['Bat'/13252, l='MpServer', x=-355.63, y=31.10, z=51.03], EntitySquid['Squid'/13273, l='MpServer', x=-264.09, y=62.00, z=177.84], EntitySquid['Squid'/13274, l='MpServer', x=-261.06, y=61.91, z=183.59], EntitySquid['Squid'/13275, l='MpServer', x=-263.50, y=61.31, z=180.50], EntitySquid['Squid'/13276, l='MpServer', x=-257.31, y=62.38, z=178.78], EntitySquid['Squid'/13278, l='MpServer', x=-255.81, y=60.75, z=175.03], EntitySquid['Squid'/13280, l='MpServer', x=-264.16, y=62.38, z=174.72], EntitySquid['Squid'/13282, l='MpServer', x=-260.47, y=58.91, z=178.75], EntityBat['Bat'/13323, l='MpServer', x=-251.27, y=10.87, z=94.71], EntityBat['Bat'/13398, l='MpServer', x=-343.34, y=35.04, z=193.56], EntityBat['Bat'/13424, l='MpServer', x=-282.41, y=40.10, z=83.65], EntityBat['Bat'/13441, l='MpServer', x=-302.64, y=30.17, z=71.82], EntityBat['Bat'/13442, l='MpServer', x=-296.53, y=29.10, z=61.75], EntityBat['Bat'/13480, l='MpServer', x=-374.41, y=44.03, z=198.34], EntityBat['Bat'/13557, l='MpServer', x=-285.42, y=16.38, z=55.66], EntityBat['Bat'/13558, l='MpServer', x=-284.25, y=20.83, z=45.29], EntityBat['Bat'/13559, l='MpServer', x=-288.31, y=19.38, z=48.14], EntityItem['item.tile.flower1.dandelion'/13640, l='MpServer', x=-371.63, y=74.13, z=171.66], EntityBat['Bat'/13657, l='MpServer', x=-297.43, y=14.00, z=173.54], EntityBat['Bat'/13665, l='MpServer', x=-257.34, y=30.10, z=64.75], EntityBat['Bat'/13666, l='MpServer', x=-257.25, y=28.00, z=63.75], EntityItem['item.tile.flower1.dandelion'/13674, l='MpServer', x=-371.75, y=75.39, z=174.18], EntityItem['item.tile.flower1.dandelion'/12195, l='MpServer', x=-371.88, y=72.13, z=173.19], EntitySquid['Squid'/12205, l='MpServer', x=-302.53, y=62.16, z=169.41]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2444)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:919)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 922000528 bytes (879 MB) / 1705508864 bytes (1626 MB) up to 3817865216 bytes (3641 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4096m -Xms256m
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 14 mods loaded, 14 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAAAAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAAAAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJAAAAAAAAA	Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJAAAAAAAAA	ImmersiveEngineering{0.7.7} [Immersive Engineering] (ImmersiveEngineering-0.7.7.jar) 
	UCHIJAAAAAAAAA	trackapi{1.2} [Track API] (TrackAPI-1.2.jar) 
	UCHIJAAAAAAAAA	universalmodcore{1.1.4} [UniversalModCore] (UniversalModCore-1.7.10-forge-1.1.4-899c85.jar) 
	UCHIJAAAAAAAAA	immersiverailroading{1.9.1} [Immersive Railroading] (ImmersiveRailroading-1.7.10-forge-1.9.1.jar) 
	UCHIJAAAAAAAAA	ForgeMultipart{1.2.0.345} [Forge Multipart] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	UCHIJAAAAAAAAA	McMultipart{1.2.0.345} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	UCHIJAAAAAAAAA	ForgeRelocation{0.0.1.4} [ForgeRelocation] (ForgeRelocation-0.0.1.4-universal.jar) 
	UCHIJAAAAAAAAA	MCFrames{1.0} [MCFrames] (ForgeRelocation-0.0.1.4-universal.jar) 
	UCHIJAAAAAAAAA	RelocationFMP{0.0.1.2} [RelocationFMP] (ForgeRelocationFMP-0.0.1.2-universal.jar) 
	UCHIJAAAAAAAAA	MrTJPCoreMod{1.1.0.33} [MrTJPCore] (MrTJPCore-1.1.0.33-universal.jar) 
	UCHIJAAAAAAAAA	ForgeMicroblock{1.2.0.345} [Forge Microblocks] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 527.56' Renderer: 'NVIDIA GeForce GTX 1050 Ti/PCIe/SSE2'
	Launched Version: forge-10.13.4.1614
	LWJGL: 2.9.1
	OpenGL: NVIDIA GeForce GTX 1050 Ti/PCIe/SSE2 GL version 4.6.0 NVIDIA 527.56, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)
	Anisotropic Filtering: Off (1)

**Comment by dstnkota** [comment]
Found problem nevermind.
