### ISSUE TITLE
[Bug] Invalid packet missing player and ticking entity server crash on latest IR testbuild

### ISSUE THREAD

**Issue by Jeronimo97** [TeamOpenIndustry/ImmersiveRailroading#1388]
**Describe the bug**  
There is an issue on servers when you get on trains, log out and reconnect that you can no longer interact with any trains. The server has to be stopped before it works again for the individual player. The problem apparently occurs randomly for some users even without reconnecting or using trains. 
If you sat on a seat in the train and left the game, the whole server crashed.

**How to reproduce**  
Steps to reproduce the unwanted behavior:

 1. Get on a train on a server
 2. Disconnect from the server
 3. Reconnect to the server and try to interact with the train. (only the missing player problem)
 
**Expected behavior**  
After rejoining the world, I should be able to use trains normally.

**System Information**  
 * IR-Version: 1.12.2-forge-1.9.1-a16da23 (as well as earlier test-builds)
 * UMC-Version: 1.12.2-forge-1.1.4-4af046d
 * Forge-Version: 1.12.2 - 14.23.5.2860
 * Server 1: Magma 1.12.2-15ea32c3
 * Server 2: SpongeForge 1.12.2-2838-7.4.7
 * Server 3: Forge-Vanilla: 1.12.2 - 14.23.5.2860

**Modlist**

* charset
* opensignals
* immersiveengineering
* mrcrayfish vehiclemod
* girutility
* spark
* trackapi
* projectred-core
* ic2
* opencomputers
* projectred-fabrication
* projectred-transmission
* tcutility
* mrtjpcore
* obfuscate
* microblockcbe
* projectred-integration
* pams harvestcraft
* tcredstone
* cfm
* minecraftmultipartcbe
* immersiverailroading
* forgemultipartcbe
* opencomputers|core
* railstuff
* codechickenlib
* fastleafdecay
* invisiblelights
* chiselsandbits
* gircredstone
* df-roads
* universalmodcore

**latest.log**

Magma server

Before disconnect
```
[Server thread/WARN] [universalmodcore]: Adding entity that was not wrapped correctly 8a47903f-49ad-4bde-9bbe-3a0419e954fb - EntityPlayerMP['Mc_Jeronimo'/763, uuid='8a47903f-49ad-4bde-9bbe-3a0419e954fb', l='world', x=-112,50, y=73,36, z=-233,50, cx=-8, cd=-15, tl=1877, v=false, d=true](Mc_Jeronimo at -112.5,73.35620345472788,-233.5)
```

After reconnect
```
[23:40:02] [Server thread/ERROR] [universalmodcore]: Catching
java.lang.Exception: Invalid Packet class cam72cam.immersiverailroading.entity.ClientPartDragging$SeatPacket: missing player
	at cam72cam.mod.net.Packet$Handler.handle(Packet.java:168) ~[Packet$Handler.class:?]
	at cam72cam.mod.net.Packet$Handler.lambda$onMessage$0(Packet.java:153) ~[Packet$Handler.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_312]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_312]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:861) ~[MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:461) ~[nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:800) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:672) ~[MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_312]
[23:40:02] [Server thread/ERROR] [universalmodcore]: Catching
java.lang.Exception: Invalid Packet class cam72cam.mod.input.Mouse$MousePressPacket: missing player
	at cam72cam.mod.net.Packet$Handler.handle(Packet.java:168) ~[Packet$Handler.class:?]
	at cam72cam.mod.net.Packet$Handler.lambda$onMessage$0(Packet.java:153) ~[Packet$Handler.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_312]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_312]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:861) ~[MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:461) ~[nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:800) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:672) ~[MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_312]
```

Sponge Server

```
[12:47:31] [Server thread/ERROR] [Sponge]: /**************************************************************************************************************************/
[12:47:31] [Server thread/ERROR] [Sponge]: /*                                         Exception occurred during a PhaseState                                         */
[12:47:31] [Server thread/ERROR] [Sponge]: /**************************************************************************************************************************/
[12:47:31] [Server thread/ERROR] [Sponge]: /* Sponge's tracking system makes a best                                                                                  */
[12:47:31] [Server thread/ERROR] [Sponge]: /* effort to not throw exceptions randomly                                                                                */
[12:47:31] [Server thread/ERROR] [Sponge]: /* but sometimes it is inevitable. In most                                                                                */
[12:47:31] [Server thread/ERROR] [Sponge]: /* cases, something else triggered this                                                                                   */
[12:47:31] [Server thread/ERROR] [Sponge]: /* exception and Sponge prevented a crash                                                                                 */
[12:47:31] [Server thread/ERROR] [Sponge]: /* by catching it. The following stacktrace                                                                               */
[12:47:31] [Server thread/ERROR] [Sponge]: /* can be used to help pinpoint the cause.                                                                                */
[12:47:31] [Server thread/ERROR] [Sponge]: /**************************************************************************************************************************/
[12:47:31] [Server thread/ERROR] [Sponge]: /* The PhaseState having an exception: Tick{Entity}                                                                       */
[12:47:31] [Server thread/ERROR] [Sponge]: /* The PhaseContext:                                                                                                      */
[12:47:31] [Server thread/ERROR] [Sponge]: /* org.spongepowered.asm.util.PrettyPrinter@a09d4a1                                                                       */
[12:47:31] [Server thread/ERROR] [Sponge]: /*                                                                                                                        */
[12:47:31] [Server thread/ERROR] [Sponge]: /*  StackTrace :                                                                                                          */
[12:47:31] [Server thread/ERROR] [Sponge]: /*     java.lang.NullPointerException: null                                                                               */
[12:47:31] [Server thread/ERROR] [Sponge]: /*     cam72cam.mod.entity.ModdedEntity.calculatePassengerOffset(ModdedEntity.java:282)                                   */
[12:47:31] [Server thread/ERROR] [Sponge]: /*     cam72cam.mod.entity.ModdedEntity.func_184200_o(ModdedEntity.java:303)                                              */
[12:47:31] [Server thread/ERROR] [Sponge]: /*     net.minecraft.entity.Entity.func_184205_a(Entity.java:2072)                                                        */
[12:47:31] [Server thread/ERROR] [Sponge]: /*     net.minecraft.entity.player.EntityPlayerMP.func_184205_a(EntityPlayerMP.java:771)                                  */
[12:47:31] [Server thread/ERROR] [Sponge]: /*     net.minecraft.entity.Entity.func_184220_m(Entity.java:2050)                                                        */
[12:47:31] [Server thread/ERROR] [Sponge]: /*     cam72cam.mod.entity.Entity.startRiding(Entity.java:219)                                                            */
[12:47:31] [Server thread/ERROR] [Sponge]: /*     cam72cam.immersiverailroading.entity.EntityRidableRollingStock.lambda$onTick$8(EntityRidableRollingStock.java:203) */
[12:47:31] [Server thread/ERROR] [Sponge]: /*     java.util.HashMap.forEach(Unknown Source)                                                                          */
[12:47:31] [Server thread/ERROR] [Sponge]: /*     cam72cam.immersiverailroading.entity.EntityRidableRollingStock.onTick(EntityRidableRollingStock.java:201)          */
[12:47:31] [Server thread/ERROR] [Sponge]: /*     cam72cam.immersiverailroading.entity.EntityMoveableRollingStock.onTick(EntityMoveableRollingStock.java:240)        */
[12:47:31] [Server thread/ERROR] [Sponge]: /*     cam72cam.immersiverailroading.entity.EntityCoupleableRollingStock.onTick(EntityCoupleableRollingStock.java:141)    */
[12:47:31] [Server thread/ERROR] [Sponge]: /*     cam72cam.immersiverailroading.entity.CarPassenger.onTick(CarPassenger.java:14)                                     */
[12:47:31] [Server thread/ERROR] [Sponge]: /*     cam72cam.mod.entity.ModdedEntity.func_70071_h_(ModdedEntity.java:221)                                              */
[12:47:31] [Server thread/ERROR] [Sponge]: /*     org.spongepowered.common.event.tracking.TrackingUtil.tickEntity(TrackingUtil.java:167)                             */
[12:47:31] [Server thread/ERROR] [Sponge]: /*     net.minecraft.world.WorldServer.redirect$zlm000$onCallEntityUpdate(WorldServer.java:4761)                          */
[12:47:31] [Server thread/ERROR] [Sponge]: /*     net.minecraft.world.World.func_72866_a(World.java:1996)                                                            */
[12:47:31] [Server thread/ERROR] [Sponge]: /*     net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)                                                 */
[12:47:31] [Server thread/ERROR] [Sponge]: /*     net.minecraft.world.World.func_72870_g(World.java:1958)                                                            */
[12:47:31] [Server thread/ERROR] [Sponge]: /*     net.minecraft.world.World.func_72939_s(World.java:1762)                                                            */
[12:47:31] [Server thread/ERROR] [Sponge]: /*     net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:3931)                                                */
[12:47:31] [Server thread/ERROR] [Sponge]: /*     net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)                                        */
[12:47:31] [Server thread/ERROR] [Sponge]: /*     net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)                              */
[12:47:31] [Server thread/ERROR] [Sponge]: /*     net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)                                        */
[12:47:31] [Server thread/ERROR] [Sponge]: /*     net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)                                                 */
[12:47:31] [Server thread/ERROR] [Sponge]: /*     java.lang.Thread.run(Unknown Source)                                                                               */
[12:47:31] [Server thread/ERROR] [Sponge]: /*                                                                                                                        */
[12:47:31] [Server thread/ERROR] [Sponge]: /* Minecraft : 1.12.2                                                                                                     */
[12:47:31] [Server thread/ERROR] [Sponge]: /* SpongeAPI : 7.4.0-5ea6215                                                                                              */
[12:47:31] [Server thread/ERROR] [Sponge]: /* Sponge : 1.12.2-7.4.7                                                                                                  */
[12:47:31] [Server thread/ERROR] [Sponge]: /* SpongeForge : 1.12.2-2838-7.4.7                                                                                        */
[12:47:31] [Server thread/ERROR] [Sponge]: /* Minecraft Forge : 14.23.5.2860                                                                                         */
[12:47:31] [Server thread/ERROR] [Sponge]: /**************************************************************************************************************************/

```

Vanilla Forge server which crash while sitting
```
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
	at cam72cam.mod.entity.ModdedEntity.calculatePassengerOffset(ModdedEntity.java:282)
	at cam72cam.mod.entity.ModdedEntity.func_184200_o(ModdedEntity.java:303)
	at net.minecraft.entity.Entity.func_184205_a(Entity.java:2072)
	at net.minecraft.entity.player.EntityPlayerMP.func_184205_a(EntityPlayerMP.java:771)
	at net.minecraft.entity.Entity.func_184220_m(Entity.java:2050)
	at cam72cam.mod.entity.Entity.startRiding(Entity.java:219)
	at cam72cam.immersiverailroading.entity.EntityRidableRollingStock.lambda$onTick$8(EntityRidableRollingStock.java:203)
	at java.util.HashMap.forEach(Unknown Source)
	at cam72cam.immersiverailroading.entity.EntityRidableRollingStock.onTick(EntityRidableRollingStock.java:201)
	at cam72cam.immersiverailroading.entity.EntityMoveableRollingStock.onTick(EntityMoveableRollingStock.java:240)
	at cam72cam.immersiverailroading.entity.EntityCoupleableRollingStock.onTick(EntityCoupleableRollingStock.java:141)
	at cam72cam.immersiverailroading.entity.CarPassenger.onTick(CarPassenger.java:14)
	at cam72cam.mod.entity.ModdedEntity.func_70071_h_(ModdedEntity.java:221)
	at net.minecraft.world.World.func_72866_a(World.java:1996)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1958)
	at net.minecraft.world.World.func_72939_s(World.java:1762)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Unknown Source)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at cam72cam.mod.entity.ModdedEntity.calculatePassengerOffset(ModdedEntity.java:282)
	at cam72cam.mod.entity.ModdedEntity.func_184200_o(ModdedEntity.java:303)
	at net.minecraft.entity.Entity.func_184205_a(Entity.java:2072)
	at net.minecraft.entity.player.EntityPlayerMP.func_184205_a(EntityPlayerMP.java:771)
	at net.minecraft.entity.Entity.func_184220_m(Entity.java:2050)
	at cam72cam.mod.entity.Entity.startRiding(Entity.java:219)
	at cam72cam.immersiverailroading.entity.EntityRidableRollingStock.lambda$onTick$8(EntityRidableRollingStock.java:203)
	at java.util.HashMap.forEach(Unknown Source)
	at cam72cam.immersiverailroading.entity.EntityRidableRollingStock.onTick(EntityRidableRollingStock.java:201)
	at cam72cam.immersiverailroading.entity.EntityMoveableRollingStock.onTick(EntityMoveableRollingStock.java:240)
	at cam72cam.immersiverailroading.entity.EntityCoupleableRollingStock.onTick(EntityCoupleableRollingStock.java:141)
	at cam72cam.immersiverailroading.entity.CarPassenger.onTick(CarPassenger.java:14)
	at cam72cam.mod.entity.ModdedEntity.func_70071_h_(ModdedEntity.java:221)
	at net.minecraft.world.World.func_72866_a(World.java:1996)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1958)

-- Entity being ticked --
Details:
	Entity Type: immersiverailroading:tender (cam72cam.mod.entity.ModdedEntity)
	Entity ID: 4209
	Entity Name: immersiverailroading:carpassenger
	Entity's Exact location: -104,50, 63,36, -194,12
	Entity's Block location: World: (-105,63,-195), Chunk: (at 7,3,13 in -7,-13; contains blocks -112,0,-208 to -97,255,-193), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Entity's Momentum: 0,00, 0,00, 0,00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1762)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
```

**Additional context**  
None.

**Comment by Larky2k** [comment]
test build bugs must be in test build channel on discord also IR doesn't work with Hybrid servers must be forge only

**Comment by Jeronimo97** [comment]
But vanilla forge crash the server :)

**Comment by cam72cam** [comment]
Then post the vanilla crash

**Comment by Jeronimo97** [comment]
# Ticking Entity problem

**Modlist**  
 * IR-Version: 1.12.2-forge-1.9.1-a16da23 (.latest official test-build version)
 * UMC-Version: 1.12.2-forge-1.1.4-4af046d
 * Track API (1.12.2-1.2)
 * Forge-Version: 1.12.2 - 14.23.5.2860

**Crash Report**
```
---- Minecraft Crash Report ----

WARNING: coremods are present:
Contact their authors BEFORE contacting forge

// You should try our sister game, Minceraft!

Time: 14.09.23 18:36
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
	at cam72cam.mod.entity.ModdedEntity.calculatePassengerOffset(ModdedEntity.java:282)
	at cam72cam.mod.entity.ModdedEntity.func_184200_o(ModdedEntity.java:303)
	at net.minecraft.entity.Entity.func_184205_a(Entity.java:2072)
	at net.minecraft.entity.player.EntityPlayerMP.func_184205_a(EntityPlayerMP.java:771)
	at net.minecraft.entity.Entity.func_184220_m(Entity.java:2050)
	at cam72cam.mod.entity.Entity.startRiding(Entity.java:219)
	at cam72cam.immersiverailroading.entity.EntityRidableRollingStock.lambda$onTick$8(EntityRidableRollingStock.java:203)
	at java.util.HashMap.forEach(Unknown Source)
	at cam72cam.immersiverailroading.entity.EntityRidableRollingStock.onTick(EntityRidableRollingStock.java:201)
	at cam72cam.immersiverailroading.entity.EntityMoveableRollingStock.onTick(EntityMoveableRollingStock.java:240)
	at cam72cam.immersiverailroading.entity.EntityCoupleableRollingStock.onTick(EntityCoupleableRollingStock.java:141)
	at cam72cam.immersiverailroading.entity.CarPassenger.onTick(CarPassenger.java:14)
	at cam72cam.mod.entity.ModdedEntity.func_70071_h_(ModdedEntity.java:221)
	at net.minecraft.world.World.func_72866_a(World.java:1996)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1958)
	at net.minecraft.world.World.func_72939_s(World.java:1762)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Unknown Source)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at cam72cam.mod.entity.ModdedEntity.calculatePassengerOffset(ModdedEntity.java:282)
	at cam72cam.mod.entity.ModdedEntity.func_184200_o(ModdedEntity.java:303)
	at net.minecraft.entity.Entity.func_184205_a(Entity.java:2072)
	at net.minecraft.entity.player.EntityPlayerMP.func_184205_a(EntityPlayerMP.java:771)
	at net.minecraft.entity.Entity.func_184220_m(Entity.java:2050)
	at cam72cam.mod.entity.Entity.startRiding(Entity.java:219)
	at cam72cam.immersiverailroading.entity.EntityRidableRollingStock.lambda$onTick$8(EntityRidableRollingStock.java:203)
	at java.util.HashMap.forEach(Unknown Source)
	at cam72cam.immersiverailroading.entity.EntityRidableRollingStock.onTick(EntityRidableRollingStock.java:201)
	at cam72cam.immersiverailroading.entity.EntityMoveableRollingStock.onTick(EntityMoveableRollingStock.java:240)
	at cam72cam.immersiverailroading.entity.EntityCoupleableRollingStock.onTick(EntityCoupleableRollingStock.java:141)
	at cam72cam.immersiverailroading.entity.CarPassenger.onTick(CarPassenger.java:14)
	at cam72cam.mod.entity.ModdedEntity.func_70071_h_(ModdedEntity.java:221)
	at net.minecraft.world.World.func_72866_a(World.java:1996)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1958)

-- Entity being ticked --
Details:
	Entity Type: immersiverailroading:cartank (cam72cam.mod.entity.ModdedEntity)
	Entity ID: 125
	Entity Name: immersiverailroading:carpassenger
	Entity's Exact location: -103,50, 63,36, -213,12
	Entity's Block location: World: (-104,63,-214), Chunk: (at 8,3,10 in -7,-14; contains blocks -112,0,-224 to -97,255,-209), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Entity's Momentum: 0,00, 0,00, 0,00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1762)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)

-- Affected level --
Details:
	Level name: world
	All players: 0 total; []
	Chunk stats: ServerChunkCache: 597 Drop: 339
	Level seed: -23427194224903150
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (-116,64,131), Chunk: (at 12,4,3 in -8,8; contains blocks -128,0,128 to -113,255,143), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 7267 game time, 7267 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 132202 (now: false), thunder time: 74441 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_301, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 846450944 bytes (807 MB) / 1044381696 bytes (996 MB) up to 1450704896 bytes (1383 MB)
	JVM Flags: 1 total; -Xmx1556M
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.42 Powered by Forge 14.23.5.2860 7 mods loaded, 7 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                   | Version      | Source                                              | Signature                                |
	|:------ |:-------------------- |:------------ |:--------------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft            | 1.12.2       | minecraft.jar                                       | None                                     |
	| LCHIJA | mcp                  | 9.42         | minecraft.jar                                       | None                                     |
	| LCHIJA | FML                  | 8.0.99.99    | forge-1.12.2-14.23.5.2860-universal.jar             | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge                | 14.23.5.2860 | forge-1.12.2-14.23.5.2860-universal.jar             | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | trackapi             | 1.2          | TrackAPI.jar                                        | None                                     |
	| LCHIJA | universalmodcore     | 1.1.4        | UniversalModCore-1.12.2-forge-1.1.4-4af046d.jar     | None                                     |
	| LCHIJA | immersiverailroading | 1.9.1        | ImmersiveRailroading-1.12.2-forge-1.9.1-a16da23.jar | None                                     |

	Loaded coremods (and transformers): 
	Profiler Position: N/A (disabled)
	Player Count: 0 / 20; []
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)
```

**Comment by Larky2k** [comment]
post latest,log as well

**Comment by Larky2k** [comment]
have you removed or updated any packs recently

**Comment by cam72cam** [comment]
That's not important to the crash

**Comment by Jeronimo97** [comment]
Idk it's a special test environment exactly for this

**Comment by Jeronimo97** [comment]
I have deleted a few mods, because I wanted to try it only with the 3. The log file is also shortened, because the otherwise had 15000 lines because of missing entries.
I can also like to set up a completely new environment again...

**Comment by cam72cam** [comment]
No need.  I've got this @Larky2k 
What were you doing when the crash occurred? Disconnecting?

**Comment by cam72cam** [comment]
I'm guessing you were seated in a piece of stock and then logged off.

**Comment by Jeronimo97** [comment]
I sit on the train and press disconnect. This can also happen when a user is disconnected because of the Internet or whatever.

**Comment by cam72cam** [comment]
@Jeronimo97 should be fixed in:

https://teamopenindustry.cc/maven/cam72cam/immersiverailroading/ImmersiveRailroading/1.12.2-forge-1.9.1-b57997f/ImmersiveRailroading-1.12.2-forge-1.9.1-b57997f.jar
https://teamopenindustry.cc/maven/cam72cam/universalmodcore/UniversalModCore/1.12.2-forge-1.1.4-98c9f07/UniversalModCore-1.12.2-forge-1.1.4-98c9f07.jar
