### ISSUE TITLE
Can't even go to second page of inventory

### ISSUE THREAD

**Issue by PolskaKrowa** [TeamOpenIndustry/ImmersiveRailroading#1401]
I have all of the required mods and no other mods, and yet when i go to page 2 of my inventory the game crashes.

Crash report can be seen below:

Crash Report ----
// Hey, that tickles! Hehehe!

Time: 07/10/2023, 22:40
Description: Rendering entity in world

java.util.NoSuchElementException: No value present
	at java.util.Optional.get(Optional.java:143) ~[?:?] {}
	at cam72cam.immersiverailroading.registry.DefinitionManager.getTrack(DefinitionManager.java:304) ~[immersiverailroading:1.16.5-forge-1.9.1] {re:classloading}
	at cam72cam.immersiverailroading.registry.DefinitionManager.getTrack(DefinitionManager.java:298) ~[immersiverailroading:1.16.5-forge-1.9.1] {re:classloading}
	at cam72cam.immersiverailroading.render.rail.RailBuilderRender.renderRailBuilder(RailBuilderRender.java:29) ~[immersiverailroading:1.16.5-forge-1.9.1] {re:classloading}
	at cam72cam.immersiverailroading.render.item.TrackBlueprintItemModel.render(TrackBlueprintItemModel.java:58) ~[immersiverailroading:1.16.5-forge-1.9.1] {re:classloading}
	at cam72cam.immersiverailroading.render.item.TrackBlueprintItemModel.lambda$getModel$0(TrackBlueprintItemModel.java:23) ~[immersiverailroading:1.16.5-forge-1.9.1] {re:classloading}
	at cam72cam.mod.render.StandardModel.lambda$addCustom$3(StandardModel.java:99) ~[universalmodcore:1.1.3] {re:classloading}
	at cam72cam.mod.render.StandardModel.lambda$renderCustom$5(StandardModel.java:165) ~[universalmodcore:1.1.3] {re:classloading}
	at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?] {}
	at cam72cam.mod.render.StandardModel.renderCustom(StandardModel.java:165) ~[universalmodcore:1.1.3] {re:classloading}
	at cam72cam.mod.render.StandardModel.render(StandardModel.java:126) ~[universalmodcore:1.1.3] {re:classloading}
	at cam72cam.mod.render.StandardModel.render(StandardModel.java:121) ~[universalmodcore:1.1.3] {re:classloading}
	at cam72cam.mod.render.ItemRender$BakedItemModel.lambda$handlePerspective$0(ItemRender.java:352) ~[universalmodcore:1.1.3] {re:classloading}
	at cam72cam.mod.render.ItemRender$2.func_239207_a_(ItemRender.java:261) ~[universalmodcore:1.1.3] {re:classloading}
	at net.minecraft.client.renderer.ItemRenderer.func_229111_a_(ItemRenderer.java:137) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.entity.ItemRenderer.func_225623_a_(ItemRenderer.java:83) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.entity.ItemRenderer.func_225623_a_(ItemRenderer.java:20) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.entity.EntityRendererManager.func_229084_a_(EntityRendererManager.java:251) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.WorldRenderer.func_228418_a_(WorldRenderer.java:1202) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.WorldRendererAccess,pl:mixin:APP:immersiveengineering.mixins.json:coremods.client.WorldRendererMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.WorldRenderer.func_228426_a_(WorldRenderer.java:1010) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.WorldRendererAccess,pl:mixin:APP:immersiveengineering.mixins.json:coremods.client.WorldRendererMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.func_228378_a_(GameRenderer.java:608) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:425) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:977) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) ~[minecraft-1.16.5-client.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) ~[forge-1.16.5-36.2.34-launcher.jar:36.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.1.3.jar:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:57) [ForgeWrapper-mmc3.jar:mmc3] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:243) [NewLaunch.jar:?] {}
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:278) [NewLaunch.jar:?] {}
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?] {}
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at java.util.Optional.get(Optional.java:143) ~[?:?] {}
	at cam72cam.immersiverailroading.registry.DefinitionManager.getTrack(DefinitionManager.java:304) ~[immersiverailroading:1.16.5-forge-1.9.1] {re:classloading}
	at cam72cam.immersiverailroading.registry.DefinitionManager.getTrack(DefinitionManager.java:298) ~[immersiverailroading:1.16.5-forge-1.9.1] {re:classloading}
	at cam72cam.immersiverailroading.render.rail.RailBuilderRender.renderRailBuilder(RailBuilderRender.java:29) ~[immersiverailroading:1.16.5-forge-1.9.1] {re:classloading}
	at cam72cam.immersiverailroading.render.item.TrackBlueprintItemModel.render(TrackBlueprintItemModel.java:58) ~[immersiverailroading:1.16.5-forge-1.9.1] {re:classloading}
	at cam72cam.immersiverailroading.render.item.TrackBlueprintItemModel.lambda$getModel$0(TrackBlueprintItemModel.java:23) ~[immersiverailroading:1.16.5-forge-1.9.1] {re:classloading}
	at cam72cam.mod.render.StandardModel.lambda$addCustom$3(StandardModel.java:99) ~[universalmodcore:1.1.3] {re:classloading}
	at cam72cam.mod.render.StandardModel.lambda$renderCustom$5(StandardModel.java:165) ~[universalmodcore:1.1.3] {re:classloading}
	at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?] {}
	at cam72cam.mod.render.StandardModel.renderCustom(StandardModel.java:165) ~[universalmodcore:1.1.3] {re:classloading}
	at cam72cam.mod.render.StandardModel.render(StandardModel.java:126) ~[universalmodcore:1.1.3] {re:classloading}
	at cam72cam.mod.render.StandardModel.render(StandardModel.java:121) ~[universalmodcore:1.1.3] {re:classloading}
	at cam72cam.mod.render.ItemRender$BakedItemModel.lambda$handlePerspective$0(ItemRender.java:352) ~[universalmodcore:1.1.3] {re:classloading}
	at cam72cam.mod.render.ItemRender$2.func_239207_a_(ItemRender.java:261) ~[universalmodcore:1.1.3] {re:classloading}
	at net.minecraft.client.renderer.ItemRenderer.func_229111_a_(ItemRenderer.java:137) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.entity.ItemRenderer.func_225623_a_(ItemRenderer.java:83) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.entity.ItemRenderer.func_225623_a_(ItemRenderer.java:20) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
-- Entity being rendered --
Details:
	Entity Type: minecraft:item (net.minecraft.entity.item.ItemEntity)
	Entity ID: 52
	Entity Name: Track Blueprint
	Entity's Exact location: -17.89, 5.32, -269.62
	Entity's Block location: World: (-18,5,-270), Chunk: (at 14,0,2 in -2,-17; contains blocks -32,0,-272 to -17,255,-257), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Entity's Momentum: 0.06, -0.01, -0.28
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: Cannot invoke "net.minecraft.entity.Entity.toString()" because the return value of "net.minecraft.entity.Entity.func_184187_bx()" is null

-- Renderer details --
Details:
	Assigned renderer: net.minecraft.client.renderer.entity.ItemRenderer@19d118d5
	Location: 0.00,-0.30,0.00 - World: (0,-1,0), Chunk: (at 0,-1,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Rotation: 211.63878
	Delta: 0.8599925
Stacktrace:
	at net.minecraft.client.renderer.entity.EntityRendererManager.func_229084_a_(EntityRendererManager.java:251) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.WorldRenderer.func_228418_a_(WorldRenderer.java:1202) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.WorldRendererAccess,pl:mixin:APP:immersiveengineering.mixins.json:coremods.client.WorldRendererMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.WorldRenderer.func_228426_a_(WorldRenderer.java:1010) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.WorldRendererAccess,pl:mixin:APP:immersiveengineering.mixins.json:coremods.client.WorldRendererMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.func_228378_a_(GameRenderer.java:608) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}

-- Affected level --
Details:
	All players: 1 total; [ClientPlayerEntity['_bruhwhat_'/4, l='ClientLevel', x=-17.89, y=4.00, z=-269.62]]
	Chunk stats: Client Chunk Cache: 841, 529
	Level dimension: minecraft:overworld
	Level spawn location: World: (-16,4,-256), Chunk: (at 0,0,0 in -1,-16; contains blocks -16,0,-256 to -1,255,-241), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Level time: 1830 game time, 1830 day time
	Server brand: forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.world.ClientWorld.func_72914_a(ClientWorld.java:447) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2031) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:623) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) ~[minecraft-1.16.5-client.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) ~[forge-1.16.5-36.2.34-launcher.jar:36.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.1.3.jar:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:57) [ForgeWrapper-mmc3.jar:mmc3] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:243) [NewLaunch.jar:?] {}
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:278) [NewLaunch.jar:?] {}
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?] {}
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?] {}

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 17.0.6, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 696393896 bytes (664 MB) / 1484783616 bytes (1416 MB) up to 6845104128 bytes (6528 MB)
	CPUs: 12
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms409m -Xmx6528m
	ModLauncher: 8.1.3+8.1.3+main-8.1.x.c94d18ec
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.4.jar mixin PLUGINSERVICE 
		/eventbus-4.0.0.jar eventbus PLUGINSERVICE 
		/forge-1.16.5-36.2.34-launcher.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.5-36.2.34-launcher.jar runtime_enum_extender PLUGINSERVICE 
		/forge-1.16.5-36.2.34-launcher.jar capability_inject_definalize PLUGINSERVICE 
		/accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.5-36.2.34-launcher.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.4.jar mixin TRANSFORMATIONSERVICE 
		/forge-1.16.5-36.2.34-launcher.jar fml TRANSFORMATIONSERVICE 
	FML: 36.2
	Forge: net.minecraftforge:36.2.34
	FML Language Providers: 
		javafml@36.2
		minecraft@1
	Mod List: 
		forge-1.16.5-36.2.34-client.jar                   |Minecraft                     |minecraft                     |1.16.5              |DONE      |Manifest: NOSIGNATURE
		TrackAPI-1.16.4-forge-1.2.1.jar                   |TrackAPI                      |trackapi                      |1.2                 |DONE      |Manifest: NOSIGNATURE
		forge-1.16.5-36.2.34-universal.jar                |Forge                         |forge                         |36.2.34             |DONE      |Manifest: 22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		ImmersiveEngineering-1.16.5-5.1.0-148.jar         |Immersive Engineering         |immersiveengineering          |1.16.5-5.1.0-148    |DONE      |Manifest: NOSIGNATURE
		ImmersiveRailroading-1.16.5-forge-1.9.1.jar       |Immersive Railroading         |immersiverailroading          |1.16.5-forge-1.9.1  |DONE      |Manifest: NOSIGNATURE
		UniversalModCore-1.16.5-forge-1.1.3.jar           |Universal Mod Core            |universalmodcore              |1.1.3               |DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: 654bd465-e3f5-4f68-a747-d80d610edeba
	Launched Version: 1.16.5
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: NVIDIA GeForce RTX 3060/PCIe/SSE2 GL version 4.6.0 NVIDIA 536.99, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, mod_resources, file/VanillaTweaks_r306710.zip
	Current Language: English (US)
	CPU: 12x Intel(R) Core(TM) i5-10400F CPU @ 2.90GHz
[22:40:43] [Render thread/INFO] [STDOUT/]: [net.minecraft.util.registry.Bootstrap:func_179870_a:123]: #@!@# Game crashed! Crash report saved to: #@!@# C:\Users\regul\OneDrive\Desktop\exclusions\MultiMC\instances\choo choos-\.minecraft\crash-reports\crash-2023-10-07_22.40.43-client.txt
AL lib: (EE) alc_cleanup: 1 device not closed
Process exited with exit code -1 (0xffffffffffffffff).
Please note that usually neither the exit code, nor its description are enough to diagnose issues!
Always upload the entire log and not just the exit code.

**Comment by Larky2k** [comment]
Can't use java 17 with IR must be Java 8

**Comment by PolskaKrowa** [comment]
i just tried that and it's giving me an error
![image](https://github.com/TeamOpenIndustry/ImmersiveRailroading/assets/85899025/297bb91e-8a7f-49d0-9768-4ffce74a1a90)

**Comment by Larky2k** [comment]
have you linked MC to the new java

**Comment by PolskaKrowa** [comment]
yes

**Comment by Larky2k** [comment]
pic of what you done

**Comment by PolskaKrowa** [comment]
![image](https://github.com/TeamOpenIndustry/ImmersiveRailroading/assets/85899025/ce1ef8e1-a243-4bb3-aca7-11965cea2628)

**Comment by Larky2k** [comment]
its latest java 8

**Comment by PolskaKrowa** [comment]
yes

**Comment by Larky2k** [comment]
are you able to give java anymore RAM

**Comment by PolskaKrowa** [comment]
i'm giving it 12 gb already

**Comment by Larky2k** [comment]
try changing xms to 1024

**Comment by PolskaKrowa** [comment]
![image](https://github.com/TeamOpenIndustry/ImmersiveRailroading/assets/85899025/497c8299-197f-4742-89d6-e8ec815ca420)

**Comment by Larky2k** [comment]
edit where the error tells you

**Comment by PolskaKrowa** [comment]
[crash.txt](https://github.com/TeamOpenIndustry/ImmersiveRailroading/files/12839179/crash.txt)

**Comment by Larky2k** [comment]
well no shit with 32bit version LOL

**Comment by PolskaKrowa** [comment]
oh
oof

**Comment by PolskaKrowa** [comment]
ha
it works now, thanks man

**Comment by Larky2k** [comment]
no problem :)
