### ISSUE TITLE
Viewing items in creative menu causes crash

### ISSUE THREAD

**Issue by jrddunbr** [TeamOpenIndustry/ImmersiveRailroading#1431]
Sorry if this is a duplicate; didn't see anything similar.

One of the players on our server crashes when they look at the IR tab with a wrench.

Log attached:
[crash-2023-12-14_22.24.06-client.txt](https://github.com/TeamOpenIndustry/ImmersiveRailroading/files/13680666/crash-2023-12-14_22.24.06-client.txt)

```
java.lang.RuntimeException: Error loading item model...
	at cam72cam.immersiverailroading.render.item.ObjItemRender.lambda$null$0(ObjItemRender.java:28)
	at cam72cam.mod.render.StandardModel.lambda$addCustom$2(StandardModel.java:109)
	at cam72cam.mod.render.StandardModel.lambda$renderCustom$4(StandardModel.java:147)
	at java.util.ArrayList.forEach(Unknown Source)
	at cam72cam.mod.render.StandardModel.renderCustom(StandardModel.java:147)
	at cam72cam.mod.render.StandardModel.render(StandardModel.java:126)
	at cam72cam.mod.render.StandardModel.render(StandardModel.java:121)
	at cam72cam.mod.render.ItemRender$BakedItemModel.renderItem(ItemRender.java:255)
	at net.minecraftforge.client.ForgeHooksClient.renderInventoryItem(ForgeHooksClient.java:202)
	at net.minecraft.client.renderer.entity.RenderItem.func_82406_b(RenderItem.java:563)
	at codechicken.nei.guihook.GuiContainerManager.drawSlotItem(GuiContainerManager.java:489)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146977_a(GuiContainer.java:270)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:99)
	at net.minecraft.client.renderer.InventoryEffectRenderer.func_73863_a(InventoryEffectRenderer.java:38)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_73863_a(GuiContainerCreative.java:638)
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1061)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ArrayIndexOutOfBoundsException: Array index out of range: 4
	at net.jpountz.util.ByteBufferUtils.checkRange(ByteBufferUtils.java:20)
	at net.jpountz.lz4.LZ4JavaUnsafeFastDecompressor.decompress(LZ4JavaUnsafeFastDecompressor.java:118)
	at net.jpountz.lz4.LZ4FastDecompressor.decompress(LZ4FastDecompressor.java:132)
	at cam72cam.mod.serialization.ResourceCache.lambda$getResource$0(ResourceCache.java:130)
	at cam72cam.mod.model.obj.OBJModel.<init>(OBJModel.java:80)
	at cam72cam.mod.model.obj.OBJModel.<init>(OBJModel.java:36)
	at cam72cam.immersiverailroading.render.item.ObjItemRender.lambda$null$0(ObjItemRender.java:26)
	... 24 more
```

**Comment by jrddunbr** [comment]
[crash-2023-12-14_23.09.12-client.txt](https://github.com/TeamOpenIndustry/ImmersiveRailroading/files/13681013/crash-2023-12-14_23.09.12-client.txt)

Updated to the latest UMC and IR from the Discord and it still did it.

**Comment by jrddunbr** [comment]
Possibly a slightly different crash.
[crash-2023-12-14_23.52.49-client.txt](https://github.com/TeamOpenIndustry/ImmersiveRailroading/files/13681526/crash-2023-12-14_23.52.49-client.txt)
