### ISSUE TITLE
crushing when going to the end on 1.7.10

### ISSUE THREAD

**Issue by tiger613** [TeamOpenIndustry/ImmersiveRailroading#1452]
this is the crush report 

---- Minecraft Crash Report ----
// Daisy, daisy...

Time: 1/19/24 10:51 PM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at cam72cam.mod.MinecraftClient.getPlayer(MinecraftClient.java:27)
	at cam72cam.immersiverailroading.ImmersiveRailroading.lambda$clientEvent$3(ImmersiveRailroading.java:200)
	at cam72cam.immersiverailroading.ImmersiveRailroading$$Lambda$685/2064723866.render(Unknown Source)
	at cam72cam.mod.render.GlobalRender.lambda$registerOverlay$3(GlobalRender.java:82)
	at cam72cam.mod.render.GlobalRender$$Lambda$686/1683803818.accept(Unknown Source)
	at cam72cam.mod.event.ClientEvents$ClientEventBus.lambda$onOverlayEvent$5(ClientEvents.java:193)
	at cam72cam.mod.event.ClientEvents$ClientEventBus$$Lambda$741/958282869.accept(Unknown Source)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at cam72cam.mod.event.Event.execute(Event.java:24)
	at cam72cam.mod.event.ClientEvents$ClientEventBus.onOverlayEvent(ClientEvents.java:193)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_20_ClientEventBus_onOverlayEvent_Pre.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at net.minecraftforge.client.GuiIngameForge.pre(GuiIngameForge.java:895)
	at net.minecraftforge.client.GuiIngameForge.renderHotbar(GuiIngameForge.java:186)
	at net.minecraftforge.client.GuiIngameForge.func_73830_a(GuiIngameForge.java:141)
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1038)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at cam72cam.mod.MinecraftClient.getPlayer(MinecraftClient.java:27)
	at cam72cam.immersiverailroading.ImmersiveRailroading.lambda$clientEvent$3(ImmersiveRailroading.java:200)
	at cam72cam.immersiverailroading.ImmersiveRailroading$$Lambda$685/2064723866.render(Unknown Source)
	at cam72cam.mod.render.GlobalRender.lambda$registerOverlay$3(GlobalRender.java:82)
	at cam72cam.mod.render.GlobalRender$$Lambda$686/1683803818.accept(Unknown Source)
	at cam72cam.mod.event.ClientEvents$ClientEventBus.lambda$onOverlayEvent$5(ClientEvents.java:193)
	at cam72cam.mod.event.ClientEvents$ClientEventBus$$Lambda$741/958282869.accept(Unknown Source)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at cam72cam.mod.event.Event.execute(Event.java:24)
	at cam72cam.mod.event.ClientEvents$ClientEventBus.onOverlayEvent(ClientEvents.java:193)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_20_ClientEventBus_onOverlayEvent_Pre.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at net.minecraftforge.client.GuiIngameForge.pre(GuiIngameForge.java:895)
	at net.minecraftforge.client.GuiIngameForge.renderHotbar(GuiIngameForge.java:186)
	at net.minecraftforge.client.GuiIngameForge.func_73830_a(GuiIngameForge.java:141)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityClientPlayerMP['LeeSamuelLydia'/1003, l='MpServer', x=8.50, y=66.62, z=8.50]]
	Chunk stats: MultiplayerChunkCache: 0, 0
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (8,64,8), Chunk: (at 8,4,8 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 1 game time, 1 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 1 total; [EntityClientPlayerMP['LeeSamuelLydia'/1003, l='MpServer', x=8.50, y=66.62, z=8.50]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2444)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:927)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1922317800 bytes (1833 MB) / 2209873920 bytes (2107 MB) up to 7456948224 bytes (7111 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx8000m -Xms256m
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 8 mods loaded, 8 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAAAAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAAAAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJAAAAAAAAA	Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJAAAAAAAAA	ImmersiveEngineering{0.7.7} [Immersive Engineering] (ImmersiveEngineering-0.7.7.jar) 
	UCHIJAAAAAAAAA	immersiveintegration{0.6.8} [Immersive Integration] (immersiveintegration-0.6.8.jar) 
	UCHIJAAAAAAAAA	trackapi{1.2} [Track API] (TrackAPI-1.2.jar) 
	UCHIJAAAAAAAAA	universalmodcore{1.2.1} [UniversalModCore] (UniversalModCore-1.7.10-forge-1.2.1.jar) 
	UCHIJAAAAAAAAA	immersiverailroading{1.10.0} [Immersive Railroading] (ImmersiveRailroading-1.7.10-forge-1.10.0.jar) 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 546.17' Renderer: 'NVIDIA GeForce GTX 1650 SUPER/PCIe/SSE2'
	Launched Version: forge-10.13.4.1614
	LWJGL: 2.9.1
	OpenGL: NVIDIA GeForce GTX 1650 SUPER/PCIe/SSE2 GL version 4.6.0 NVIDIA 546.17, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)

**Comment by LEFTER285** [comment]
Sadly the same for the nether. Had and still have his problem like many others. I just hope a new release for the 1.7.10 will come soon.

**Comment by KellenHurrey** [comment]
I wrote a quick mod to fix this. [Here](https://github.com/KellenHurrey/UMCFixer/tree/1.7.10-1.0) it is.

**Comment by LEFTER285** [comment]
Thanks a lot!

**Comment by KellenHurrey** [comment]
No problem!

**Comment by tiger613** [comment]
> I wrote a quick mod to fix this. [Here](https://github.com/KellenHurrey/UMCFixer/tree/1.7.10-1.0) it is.

works super well thanks for the fix sorry it took me this long to replay i forgot i had posted a bug here lol
