### ISSUE TITLE
Crash when going to the Nether

### ISSUE THREAD

**Issue by LEFTER285** [TeamOpenIndustry/ImmersiveRailroading#1454]
Since update in December 23 on 1.7.10:

---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3

Time: 31.01.24 17:10
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at cam72cam.mod.MinecraftClient.getPlayer(MinecraftClient.java:27)
	at cam72cam.immersiverailroading.ImmersiveRailroading.lambda$clientEvent$3(ImmersiveRailroading.java:200)
	at cam72cam.immersiverailroading.ImmersiveRailroading$$Lambda$1013/1821138724.render(Unknown Source)
	at cam72cam.mod.render.GlobalRender.lambda$registerOverlay$3(GlobalRender.java:82)
	at cam72cam.mod.render.GlobalRender$$Lambda$1014/128278707.accept(Unknown Source)
	at cam72cam.mod.event.ClientEvents$ClientEventBus.lambda$onOverlayEvent$5(ClientEvents.java:193)
	at cam72cam.mod.event.ClientEvents$ClientEventBus$$Lambda$1101/257844682.accept(Unknown Source)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at cam72cam.mod.event.Event.execute(Event.java:24)
	at cam72cam.mod.event.ClientEvents$ClientEventBus.onOverlayEvent(ClientEvents.java:193)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_428_ClientEventBus_onOverlayEvent_Pre.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at net.minecraftforge.client.GuiIngameForge.pre(GuiIngameForge.java:895)
	at net.minecraftforge.client.GuiIngameForge.renderHotbar(GuiIngameForge.java:186)
	at net.minecraftforge.client.GuiIngameForge.func_73830_a(GuiIngameForge.java:141)
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1038)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at cam72cam.mod.MinecraftClient.getPlayer(MinecraftClient.java:27)
	at cam72cam.immersiverailroading.ImmersiveRailroading.lambda$clientEvent$3(ImmersiveRailroading.java:200)
	at cam72cam.immersiverailroading.ImmersiveRailroading$$Lambda$1013/1821138724.render(Unknown Source)
	at cam72cam.mod.render.GlobalRender.lambda$registerOverlay$3(GlobalRender.java:82)
	at cam72cam.mod.render.GlobalRender$$Lambda$1014/128278707.accept(Unknown Source)
	at cam72cam.mod.event.ClientEvents$ClientEventBus.lambda$onOverlayEvent$5(ClientEvents.java:193)
	at cam72cam.mod.event.ClientEvents$ClientEventBus$$Lambda$1101/257844682.accept(Unknown Source)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at cam72cam.mod.event.Event.execute(Event.java:24)
	at cam72cam.mod.event.ClientEvents$ClientEventBus.onOverlayEvent(ClientEvents.java:193)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_428_ClientEventBus_onOverlayEvent_Pre.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at net.minecraftforge.client.GuiIngameForge.pre(GuiIngameForge.java:895)
	at net.minecraftforge.client.GuiIngameForge.renderHotbar(GuiIngameForge.java:186)
	at net.minecraftforge.client.GuiIngameForge.func_73830_a(GuiIngameForge.java:141)

-- Affected level --
Details:
	Level name: MpServer
	All players: 2 total; [GCEntityClientPlayerMP['LEFTER285'/292, l='MpServer', x=8,50, y=66,62, z=8,50], MCH_ViewEntityDummy['McHeliDummyEntity'/270446, l='MpServer', x=0,00, y=-4,00, z=0,00]]
	Chunk stats: MultiplayerChunkCache: 0, 0
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (8,64,8), Chunk: (at 8,4,8 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 1 game time, 1 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 2 total; [GCEntityClientPlayerMP['LEFTER285'/292, l='MpServer', x=8,50, y=66,62, z=8,50], MCH_ViewEntityDummy['McHeliDummyEntity'/270446, l='MpServer', x=0,00, y=-4,00, z=0,00]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2444)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:927)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 3160925552 bytes (3014 MB) / 4563402752 bytes (4352 MB) up to 32212254720 bytes (30720 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx30G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 96
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 75 mods loaded, 75 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJAAAA	Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJAAAA	appliedenergistics2-core{rv2-stable-10} [AppliedEnergistics2 Core] (minecraft.jar) 
	UCHIJAAAA	CodeChickenCore{1.0.7.48} [CodeChicken Core] (minecraft.jar) 
	UCHIJAAAA	Micdoodlecore{} [Micdoodle8 Core] (minecraft.jar) 
	UCHIJAAAA	NotEnoughItems{1.0.5.120} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.120-universal.jar) 
	UCHIJAAAA	xaerominimap_core{1.7.10-1.0} [XaeroMinimapCore] (minecraft.jar) 
	UCHIJAAAA	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) 
	UCHIJAAAA	<DragonAPI ASM>{0} [DragonAPI ASM Data Initialization] (minecraft.jar) 
	UCHIJAAAA	sapmanpack{2.5.1} [SanAndreasPs Manager Pack CORE edition] (SAPManPack-1.7.10-2.5.1.jar) 
	UCHIJAAAA	IC2{2.2.821-experimental} [IndustrialCraft 2] (Industrial-Craft-2-Mod-Experimental-1.7.10.jar) 
	UCHIJAAAA	AdvancedSolarPanel{1.7.10-3.5.1} [Advanced Solar Panels] (AdvancedSolarPanel-1.7.10-3.5.1.jar) 
	UCHIJAAAA	AncientWarfare{2.4.114-beta-MC1.7.10} [Ancient Warfare Core] (ancientwarfare-2.4.115-beta-MC1.7.10-FULL.jar) 
	UCHIJAAAA	CoFHCore{1.7.10R3.1.2} [CoFH Core] (CoFHCore-[1.7.10]3.1.2-325.jar) 
	UCHIJAAAA	BuildCraft|Core{7.1.24} [BuildCraft] (buildcraft-7.1.24.jar) 
	UCHIJAAAA	AncientWarfareAutomation{2.4.114-beta-MC1.7.10} [Ancient Warfare Automation] (ancientwarfare-2.4.115-beta-MC1.7.10-FULL.jar) 
	UCHIJAAAA	AncientWarfareNEIPlugin{2.4.114-beta-MC1.7.10} [Ancient Warfare NEI Plugin] (ancientwarfare-2.4.115-beta-MC1.7.10-FULL.jar) 
	UCHIJAAAA	AncientWarfareNpc{2.4.114-beta-MC1.7.10} [Ancient Warfare NPCs] (ancientwarfare-2.4.115-beta-MC1.7.10-FULL.jar) 
	UCHIJAAAA	AncientWarfareStructure{2.4.114-beta-MC1.7.10} [Ancient Warfare Structures] (ancientwarfare-2.4.115-beta-MC1.7.10-FULL.jar) 
	UCHIJAAAA	animalbikes{1.7.10} [Animal Bikes] (Animal-Bikes-Mod-1.7.10.jar) 
	UCHIJAAAA	appliedenergistics2{rv2-stable-10} [Applied Energistics 2] (appliedenergistics2-rv2-stable-10.jar) 
	UCHIJAAAA	ArchimedesShips{1.7.10 v1.7.1} [Archimedes' Ships] (ArchimedesShips-1.7.1.jar) 
	UCHIJAAAA	armourersWorkshop{1.7.10-0.38.1.98} [Armourer's Workshop] (Armourers-Workshop-1.7.10-0.38.1.98.jar) 
	UCHIJAAAA	plushieWrapper{0.0.0} [Plushie Wrapper] (Armourers-Workshop-1.7.10-0.38.1.98.jar) 
	UCHIJAAAA	weaponmod{v1.14.3} [Balkon's WeaponMod] (Balkons-Weapon-Mod-1.7.10.jar) 
	UCHIJAAAA	ThermalFoundation{1.7.10R1.2.3} [Thermal Foundation] (ThermalFoundation-[1.7.10]1.2.3-112.jar) 
	UCHIJAAAA	ThermalExpansion{1.7.10R4.1.2} [Thermal Expansion] (ThermalExpansion-[1.7.10]4.1.2-240.jar) 
	UCHIJAAAA	BigReactors{0.4.3A} [Big Reactors] (BigReactors-0.4.3A.jar) 
	UCHIJAAAA	BrandonsCore{1.0.0.12} [Brandon's Core] (BrandonsCore-1.0.0.12.jar) 
	UCHIJAAAA	BuildCraft|Builders{7.1.24} [BC Builders] (buildcraft-7.1.24.jar) 
	UCHIJAAAA	BuildCraft|Robotics{7.1.24} [BC Robotics] (buildcraft-7.1.24.jar) 
	UCHIJAAAA	BuildCraft|Silicon{7.1.24} [BC Silicon] (buildcraft-7.1.24.jar) 
	UCHIJAAAA	BuildCraft|Energy{7.1.24} [BC Energy] (buildcraft-7.1.24.jar) 
	UCHIJAAAA	BuildCraft|Transport{7.1.24} [BC Transport] (buildcraft-7.1.24.jar) 
	UCHIJAAAA	BuildCraft|Factory{7.1.24} [BC Factory] (buildcraft-7.1.24.jar) 
	UCHIJAAAA	GollumCoreLib{2.0.0} [Gollum Core Lib] (Gollum-Core-Lib-1.7.10.jar) 
	UCHIJAAAA	CastleDefenders{3.0.0 [Build Smeagol]} [Castle Defender] (Castle-Defender-Mod-1.7.10.jar) 
	UCHIJAAAA	claysoldiers{2.0.0-beta.2} [Clay Soldiers Mod] (ClaySoldiersMod-1.7.10-2.0.0-beta.2.jar) 
	UCHIJAAAA	DraconicEvolution{1.0.2h} [Draconic Evolution] (Draconic-Evolution-1.7.10-1.0.2h.jar) 
	UCHIJAAAA	numina{0.4.0.131} [Numina] (Numina-Mod-1.7.10.jar) 
	UCHIJAAAA	powersuits{0.11.0.176} [MachineMuse's Modular Powersuits] (Modular-Powersuits-Mod-1.7.10.jar) 
	UCHIJAAAA	ExtraUtilities{1.2.12} [Extra Utilities] (extrautilities-1.2.12.jar) 
	UCHIJAAAA	Railcraft{9.6.1.0} [Railcraft] (railcraft1.7.10.jar) 
	UCHIJAAAA	ImmersiveEngineering{0.7.7} [Immersive Engineering] (ImmersiveEngineering-0.7.7.jar) 
	UCHIJAAAA	Mantle{1.7.10-0.3.2.jenkins184} [Mantle] (Mantle-1.7.10-0.3.2.jar) 
	UCHIJAAAA	TConstruct{1.7.10-1.8.8.build988} [Tinkers' Construct] (TConstruct-1.7.10-1.8.8.jar) 
	UCHIJAAAA	DragonAPI{1.0} [DragonAPI] (DragonAPI_1.7.10_V9b.jar) 
	UCHIJAAAA	EnderIO{1.7.10-2.2.8.381} [Ender IO] (EnderIO-1.7.10-2.2.8.381.jar) 
	UCHIJAAAA	explosives_pp{1.0} [Explosives++] (ExplosivesPP-1.7.10-1.3a.jar) 
	UCHIJAAAA	extracells{2.3.14} [Extra Cells 2] (ExtraCells-Mod-1.7.10.jar) 
	UCHIJAAAA	flansmod{4.9.0} [Flan's Mod] (Flans Mod-1.7.10-4.9.0.jar) 
	UCHIJAAAA	GalacticraftCore{3.0.12} [Galacticraft Core] (GalacticraftCore-1.7-3.0.12.375.jar) 
	UCHIJAAAA	GalacticraftMars{3.0.12} [Galacticraft Planets] (Galacticraft-Planets-1.7-3.0.12.375.jar) 
	UCHIJAAAA	hbm{1.0.27 BETA (4859)} [Hbm's Nuclear Tech] (HBM-NTM-.1.0.27_X4859.jar) 
	UCHIJAAAA	iChunUtil{4.1.0} [iChunUtil] (iChunUtil-4.1.0.jar) 
	UCHIJAAAA	trackapi{1.2} [Track API] (TrackAPI-1.2.jar) 
	UCHIJAAAA	universalmodcore{1.2.1} [UniversalModCore] (UniversalModCore-1.7.10-forge-1.2.1.jar) 
	UCHIJAAAA	immersiverailroading{1.10.0} [Immersive Railroading] (ImmersiveRailroading-1.7.10-forge-1.10.0.jar) 
	UCHIJAAAA	mod_Invasion{1.1.2} [Invasion] (invasion1.7.10.jar) 
	UCHIJAAAA	ism{6.9.7} [MaggiCraft's Instant Structures Mod] (ism-6.9.7.jar) 
	UCHIJAAAA	lasermod{v1.2.0a} [Laser Mod] (LaserMod-1.7.10-v1.2.0a-universal.jar) 
	UCHIJAAAA	malisiscore{1.7.10-0.14.3} [MalisisCore] (malisiscore-1.7.10.jar) 
	UCHIJAAAA	malisisdoors{1.7.10-1.13.2} [Malisis' Doors] (MalisisDoors-Mod-1.7.10.jar) 
	UCHIJAAAA	mcheli{1.0.3} [MC Helicopter] (mcheli) 
	UCHIJAAAA	Morph{0.9.1} [Morph] (Morph-Beta-0.9.1.jar) 
	UCHIJAAAA	PneumaticCraft{1.6.6-68} [PneumaticCraft] (PneumaticCraft-1.7.10-1.6.6-68-universal.jar) 
	UCHIJAAAA	PowerConverters3{1.7.10-2.11} [Power Converters 3] (PowerConverters-1.7.10-2.11.jar) 
	UCHIJAAAA	RotaryCraft{1.0} [RotaryCraft] (RotaryCraft 1.7.10 V9b.jar) 
	UCHIJAAAA	ReactorCraft{1.0} [ReactorCraft] (ReactorCraft 1.7.10 V9b.jar) 
	UCHIJAAAA	ropebridge{1.1} [Rope Bridge] (RopeBridge-v1.2-mc1.7.10.jar) 
	UCHIJAAAA	StevesCarts{2.0.0.b16} [Steve's Carts 2] (Steves-Carts-2-Mod-1.7.10.jar) 
	UCHIJAAAA	ThermalDynamics{1.7.10R1.1.0} [Thermal Dynamics] (ThermalDynamics-[1.7.10]1.1.0-161.jar) 
	UCHIJAAAA	worldedit{6.0-beta-01} [WorldEdit] (worldedit-forge-mc1.7.10-6.0-beta-01.jar) 
	UCHIJAAAA	XaeroMinimap{21.10.30} [Xaero's Minimap] (Xaeros_Minimap_21.10.30_Forge_1.7.10.jar) 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 551.23' Renderer: 'NVIDIA GeForce RTX 4060/PCIe/SSE2'
	CoFHCore: -[1.7.10]3.1.2-325
	AE2 Version: stable rv2-stable-10 for Forge 10.13.2.1291
	ThermalFoundation: -[1.7.10]1.2.3-112
	ThermalExpansion: -[1.7.10]4.1.2-240
	Mantle Environment: Environment healthy.
	TConstruct Environment: Environment healthy.
	ThermalDynamics: -[1.7.10]1.1.0-161
	AE2 Integration: IC2:ON, RotaryCraft:ON, RC:ON, BC:ON, RF:ON, RFItem:ON, MFR:OFF, DSU:ON, FZ:OFF, FMP:OFF, RB:OFF, CLApi:OFF, Waila:OFF, InvTweaks:OFF, NEI:ON, CraftGuide:OFF, Mekanism:OFF, ImmibisMicroblocks:OFF, BetterStorage:OFF
	Launched Version: 1.7.10-Forge10.13.4.1614-1.7.10
	LWJGL: 2.9.1
	OpenGL: NVIDIA GeForce RTX 4060/PCIe/SSE2 GL version 4.6.0 NVIDIA 551.23, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)

I know I also have some other mods installed, but the problem persists and exists with only this mod.

**Comment by Jackose** [comment]
ah i have the same issue too. i hope a fix comes out

**Comment by KellenHurrey** [comment]
I have written a quick mixin mod as I was facing the same error. You can find it [here](https://github.com/KellenHurrey/UMCFixer/tree/1.7.10-1.0)

**Comment by McParrot69** [comment]
![Image](https://github.com/user-attachments/assets/97f42299-127a-4600-9687-ad1f9d28d144)

**Comment by KellenHurrey** [comment]
If you have an issue with my mod, please make an issue on my repo, not here. I will commit a fix now, it's as simple as committing out a line in the build.gradle.

**Comment by cam72cam** [comment]
@KellenHurrey, would you be up for PRing your fixes into the UMC 1.7.0 branch on github?

**Comment by Goldenfield192** [comment]
> Made a pr for both UMC and IR to implement my changes. I wasn't able to test them though, because the changes rely on each other and I have no clue how IR depends on UMC in my IDE.

You can build UMC locally then go to build.gradel of IR to change the dependency location to your build
