### ISSUE TITLE
Crash during loading

### ISSUE THREAD

**Issue by biauk** [TeamOpenIndustry/ImmersiveRailroading#699]
It also happened on 1.7.0 and 1.7.1 versions of the mod. 1.6.1 works OK.

---- Minecraft Crash Report ----

WARNING: coremods are present:
  TransformerLoader (OpenComputers-MC1.12.2-1.7.5.192.jar)
  IELoadingPlugin (ImmersiveEngineering-core-0.12-92.jar)
Contact their authors BEFORE contacting forge

// Shall we play a game?

Time: 11/23/19 1:33 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from UniversalModCore (universalmodcore)
Caused by: java.lang.OutOfMemoryError: Java heap space
	at java.awt.image.DataBufferInt.<init>(Unknown Source)
	at java.awt.image.Raster.createPackedRaster(Unknown Source)
	at java.awt.image.DirectColorModel.createCompatibleWritableRaster(Unknown Source)
	at java.awt.image.BufferedImage.<init>(Unknown Source)
	at sun.java2d.loops.GraphicsPrimitive.convertFrom(Unknown Source)
	at sun.java2d.loops.GraphicsPrimitive.convertFrom(Unknown Source)
	at sun.java2d.loops.MaskBlit$General.MaskBlit(Unknown Source)
	at sun.java2d.loops.Blit$GeneralMaskBlit.Blit(Unknown Source)
	at sun.java2d.pipe.DrawImage.blitSurfaceData(Unknown Source)
	at sun.java2d.pipe.DrawImage.renderImageCopy(Unknown Source)
	at sun.java2d.pipe.DrawImage.copyImage(Unknown Source)
	at sun.java2d.pipe.DrawImage.transformImage(Unknown Source)
	at sun.java2d.pipe.ValidatePipe.transformImage(Unknown Source)
	at sun.java2d.SunGraphics2D.drawImage(Unknown Source)
	at cam72cam.mod.render.obj.OBJTextureSheet$SubTexture.upload(OBJTextureSheet.java:345)
	at cam72cam.mod.render.obj.OBJTextureSheet.<init>(OBJTextureSheet.java:149)
	at cam72cam.mod.render.obj.OBJRender.<init>(OBJRender.java:31)
	at cam72cam.immersiverailroading.render.entity.StockModel.<init>(StockModel.java:37)
	at cam72cam.immersiverailroading.render.StockRenderCache.getRender(StockRenderCache.java:31)
	at cam72cam.immersiverailroading.render.item.StockItemModel.getSpriteModel(StockItemModel.java:62)
	at cam72cam.mod.render.ItemRender.lambda$register$5(ItemRender.java:66)
	at cam72cam.mod.render.ItemRender$$Lambda$209/1345842600.run(Unknown Source)
	at cam72cam.mod.event.ClientEvents$$Lambda$436/1299601958.accept(Unknown Source)
	at java.lang.Iterable.forEach(Unknown Source)
	at cam72cam.mod.event.Event.execute(Event.java:14)
	at cam72cam.mod.event.ClientEvents.fireReload(ClientEvents.java:36)
	at cam72cam.mod.ModCore$Internal.clientEvent(ModCore.java:178)
	at cam72cam.mod.ModCore$ClientProxy.lambda$event$0(ModCore.java:119)
	at cam72cam.mod.ModCore$ClientProxy$$Lambda$198/1527292961.accept(Unknown Source)
	at java.util.ArrayList.forEach(Unknown Source)
	at cam72cam.mod.ModCore$ClientProxy.event(ModCore.java:119)
	at cam72cam.mod.ModCore.init(ModCore.java:63)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_231, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 123809448 bytes (118 MB) / 1060372480 bytes (1011 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2847 15 mods loaded, 15 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                   | Version      | Source                                                                 | Signature                                |
	|:----- |:-------------------- |:------------ |:---------------------------------------------------------------------- |:---------------------------------------- |
	| LCHI  | minecraft            | 1.12.2       | minecraft.jar                                                          | None                                     |
	| LCHI  | mcp                  | 9.42         | minecraft.jar                                                          | None                                     |
	| LCHI  | FML                  | 8.0.99.99    | forge-1.12.2-14.23.5.2847.jar                                          | None                                     |
	| LCHI  | forge                | 14.23.5.2847 | forge-1.12.2-14.23.5.2847.jar                                          | None                                     |
	| LCHI  | opencomputers|core   | 1.7.5.192    | minecraft.jar                                                          | None                                     |
	| LCHI  | mts                  | 14.3.1       | Immersive+Vehicles-1.12.2-14.3.1.jar                                   | None                                     |
	| LCHI  | unuparts             | 2.0.3        | UNU+Parts+Pack+[MTS]+[IR]+1.10.2-14.0.0-1.5.0-2.0.3.jar                | None                                     |
	| LCHI  | btcivil              | 2.1.1        | BlackThorne+Civilian+Vehicles+[MTS]+[IR]+1.10.2-14.0.0-1.5.0-2.1.1.jar | None                                     |
	| LCHI  | igwmod               | 1.4.4-15     | IGW-Mod-1.12.2-1.4.4-15-universal.jar                                  | None                                     |
	| LCHI  | trackapi             | 1.2          | TrackAPI-1.2.jar                                                       | None                                     |
	| LCHI  | immersiverailroading | 1.7.2        | ImmersiveRailroading-1.7.2_1.12.2.jar                                  | None                                     |
	| LCHE  | universalmodcore     | 1.0.0        | ImmersiveRailroading-1.7.2_1.12.2.jar                                  | None                                     |
	| LCH   | mmmpack              | 1.0.3        | Moonspire+Metropolitan+Motors+[MTS]+1.10.2-14.0.0-1.0.3.jar            | None                                     |
	| LCH   | opencomputers        | 1.7.5.192    | OpenComputers-MC1.12.2-1.7.5.192.jar                                   | None                                     |
	| LCH   | immersiveengineering | 0.12-92      | ImmersiveEngineering-0.12-92.jar                                       | 4cb49fcde3b43048c9889e0a3d083225da926334 |

	Loaded coremods (and transformers): 
TransformerLoader (OpenComputers-MC1.12.2-1.7.5.192.jar)
  li.cil.oc.common.asm.ClassTransformer
IELoadingPlugin (ImmersiveEngineering-core-0.12-92.jar)
  blusunrize.immersiveengineering.common.asm.IEClassTransformer
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.5.13469 Compatibility Profile Context 21.19.512.4' Renderer: 'AMD Radeon (TM) R5 M430'

**Comment by Nachtflame** [comment]
You need to increase the RAM you're giving to your server instance - 

> Caused by: java.lang.OutOfMemoryError: Java heap space
Tells you that the crash is due to the Server running out of assigned Memory (RAM) 

> JVM Flags: 6 total; -Xmx1G
That line there, shows that you've only got it set to run with 1GB of RAM. While fine for a Vanilla server, modded Servers should be run with no less than 2GB, IR Servers should have _at least_ 3GB

**Comment by biauk** [comment]
How can I change it?

**Comment by biauk** [comment]
OK, I figured it out, in launcher options (profiles) there is a text string and I changed 1G to 3G and now it works.
