### ISSUE TITLE
Crash on 1.14.4 Forge

### ISSUE THREAD

**Issue by Sixdd6** [TeamOpenIndustry/ImmersiveRailroading#742]
Crashed while loading the game.

Minecraft 1.14.4
Forge 28.2.1
Immersive Railroading 1.7.2
TrackAPI 1.2

Full log is [here](https://gist.github.com/Sixdd6/bf5ba4498358cd0d19ae9d936fc2ac40)
```
[18Feb2020 06:09:30.516] [modloading-worker-0/ERROR] [net.minecraftforge.fml.javafmlmod.FMLModContainer/LOADING]: Failed to create mod instance. ModID: universalmodcore, class cam72cam.mod.ModCore
java.lang.BootstrapMethodError: java.lang.IllegalAccessError: no such constructor: cam72cam.immersiverailroading.tile.TileRailGag.<init>()void/newInvokeSpecial
	at cam72cam.immersiverailroading.blocks.BlockRailGag.<init>(BlockRailGag.java:9) ~[?:1.7.2_1.14.4]
	at cam72cam.immersiverailroading.IRBlocks.<clinit>(IRBlocks.java:10) ~[?:1.7.2_1.14.4]
	at cam72cam.immersiverailroading.ImmersiveRailroading.commonEvent(ImmersiveRailroading.java:91) ~[?:1.7.2_1.14.4]
	at cam72cam.mod.ModCore$Proxy.lambda$event$0(ModCore.java:139) ~[?:1.7.2_1.14.4]
	at java.util.ArrayList.forEach(Unknown Source) ~[?:1.8.0_241]
	at cam72cam.mod.ModCore$Proxy.event(ModCore.java:139) ~[?:1.7.2_1.14.4]
	at cam72cam.mod.ModCore$ClientProxy.event(ModCore.java:145) ~[?:1.7.2_1.14.4]
	at cam72cam.mod.ModCore.<init>(ModCore.java:72) ~[?:1.7.2_1.14.4]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_241]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_241]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_241]
	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_241]
	at java.lang.Class.newInstance(Unknown Source) ~[?:1.8.0_241]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:131) ~[?:28.2]
	at java.util.function.Consumer.lambda$andThen$0(Unknown Source) ~[?:1.8.0_241]
	at java.util.function.Consumer.lambda$andThen$0(Unknown Source) ~[?:1.8.0_241]
	at net.minecraftforge.fml.ModContainer.transitionState(ModContainer.java:112) ~[?:?]
	at net.minecraftforge.fml.ModList.lambda$null$10(ModList.java:134) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source) [?:1.8.0_241]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source) [?:1.8.0_241]
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source) [?:1.8.0_241]
	at java.util.stream.ForEachOps$ForEachTask.compute(Unknown Source) [?:1.8.0_241]
	at java.util.concurrent.CountedCompleter.exec(Unknown Source) [?:1.8.0_241]
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) [?:1.8.0_241]
	at java.util.concurrent.ForkJoinPool$WorkQueue.execLocalTasks(Unknown Source) [?:1.8.0_241]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source) [?:1.8.0_241]
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) [?:1.8.0_241]
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) [?:1.8.0_241]
Caused by: java.lang.IllegalAccessError: no such constructor: cam72cam.immersiverailroading.tile.TileRailGag.<init>()void/newInvokeSpecial
	at java.lang.invoke.MethodHandleNatives.linkMethodHandleConstant(Unknown Source) ~[?:1.8.0_241]
	... 28 more
Caused by: java.lang.NoClassDefFoundError: trackapi/lib/ITrack
	at java.lang.invoke.MethodHandleNatives.resolve(Native Method) ~[?:1.8.0_241]
	at java.lang.invoke.MemberName$Factory.resolve(Unknown Source) ~[?:1.8.0_241]
	at java.lang.invoke.MemberName$Factory.resolveOrFail(Unknown Source) ~[?:1.8.0_241]
	at java.lang.invoke.MethodHandles$Lookup.resolveOrFail(Unknown Source) ~[?:1.8.0_241]
	at java.lang.invoke.MethodHandles$Lookup.linkMethodHandleConstant(Unknown Source) ~[?:1.8.0_241]
	at java.lang.invoke.MethodHandleNatives.linkMethodHandleConstant(Unknown Source) ~[?:1.8.0_241]
	... 28 more
Caused by: java.lang.ClassNotFoundException: trackapi.lib.ITrack
	at java.lang.ClassLoader.findClass(Unknown Source) ~[?:1.8.0_241]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_241]
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:103) ~[modlauncher-4.1.0.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_241]
	at java.lang.invoke.MethodHandleNatives.resolve(Native Method) ~[?:1.8.0_241]
	at java.lang.invoke.MemberName$Factory.resolve(Unknown Source) ~[?:1.8.0_241]
	at java.lang.invoke.MemberName$Factory.resolveOrFail(Unknown Source) ~[?:1.8.0_241]
	at java.lang.invoke.MethodHandles$Lookup.resolveOrFail(Unknown Source) ~[?:1.8.0_241]
	at java.lang.invoke.MethodHandles$Lookup.linkMethodHandleConstant(Unknown Source) ~[?:1.8.0_241]
	at java.lang.invoke.MethodHandleNatives.linkMethodHandleConstant(Unknown Source) ~[?:1.8.0_241]
	... 28 more
```

**Comment by cam72cam** [comment]
You are missing the TrackAPI mod
