### ISSUE TITLE
Crashes when i either get or place a train

### ISSUE THREAD

**Issue by AndyNS1701** [TeamOpenIndustry/ImmersiveRailroading#756]
I originally had this problem and it was fixed. But its not working again and i try the same hing i did before it does nothing. I have one mod installed that is Replay mod and the other 3 are the ones for it to work "ImmersiveRailroading, ImmersiveEngineering, TrackAPI" If you need the Crash Report here it is.

The game crashed whilst rendering screen
Error: org.lwjgl.opengl.OpenGLException: Cannot use Buffers when Array Buffer Object is enabled

---- Minecraft Crash Report ----

WARNING: coremods are present:
  IELoadingPlugin (ImmersiveEngineering-core-0.12-89.jar)
  LoadingPlugin (replaymod-1.12.2-2.2.0-b7.jar)
Contact their authors BEFORE contacting forge

// I let you down. Sorry :(

Time: 3/30/20 4:57 PM
Description: Rendering screen

org.lwjgl.opengl.OpenGLException: Cannot use Buffers when Array Buffer Object is enabled
	at org.lwjgl.opengl.GLChecks.ensureArrayVBOdisabled(GLChecks.java:71)
	at org.lwjgl.opengl.GL11.glVertexPointer(GL11.java:2700)
	at net.minecraft.client.renderer.GlStateManager.func_187427_b(SourceFile:770)
	at net.minecraftforge.client.ForgeHooksClient.preDraw(ForgeHooksClient.java:468)
	at net.minecraft.client.renderer.vertex.VertexFormatElement$EnumUsage.preDraw(VertexFormatElement.java:169)
	at net.minecraft.client.renderer.WorldVertexBufferUploader.func_181679_a(WorldVertexBufferUploader.java:31)
	at net.minecraft.client.renderer.Tessellator.func_78381_a(SourceFile:22)
	at net.minecraftforge.fml.client.config.GuiUtils.drawGradientRect(GuiUtils.java:442)
	at net.minecraftforge.fml.client.config.GuiUtils.drawHoveringText(GuiUtils.java:383)
	at net.minecraftforge.fml.client.config.GuiUtils.drawHoveringText(GuiUtils.java:252)
	at net.minecraft.client.gui.GuiScreen.drawHoveringText(GuiScreen.java:182)
	at net.minecraft.client.gui.GuiScreen.func_146283_a(GuiScreen.java:177)
	at net.minecraft.client.gui.GuiScreen.func_146279_a(GuiScreen.java:162)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_147052_b(GuiContainerCreative.java:867)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_73863_a(GuiContainerCreative.java:653)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:396)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1124)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1119)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at org.lwjgl.opengl.GLChecks.ensureArrayVBOdisabled(GLChecks.java:71)
	at org.lwjgl.opengl.GL11.glVertexPointer(GL11.java:2700)
	at net.minecraft.client.renderer.GlStateManager.func_187427_b(SourceFile:770)
	at net.minecraftforge.client.ForgeHooksClient.preDraw(ForgeHooksClient.java:468)
	at net.minecraft.client.renderer.vertex.VertexFormatElement$EnumUsage.preDraw(VertexFormatElement.java:169)
	at net.minecraft.client.renderer.WorldVertexBufferUploader.func_181679_a(WorldVertexBufferUploader.java:31)
	at net.minecraft.client.renderer.Tessellator.func_78381_a(SourceFile:22)
	at net.minecraftforge.fml.client.config.GuiUtils.drawGradientRect(GuiUtils.java:442)
	at net.minecraftforge.fml.client.config.GuiUtils.drawHoveringText(GuiUtils.java:383)
	at net.minecraftforge.fml.client.config.GuiUtils.drawHoveringText(GuiUtils.java:252)
	at net.minecraft.client.gui.GuiScreen.drawHoveringText(GuiScreen.java:182)
	at net.minecraft.client.gui.GuiScreen.func_146283_a(GuiScreen.java:177)
	at net.minecraft.client.gui.GuiScreen.func_146279_a(GuiScreen.java:162)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_147052_b(GuiContainerCreative.java:867)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_73863_a(GuiContainerCreative.java:653)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:396)

-- Screen render details --
Details:
	Screen name: net.minecraft.client.gui.inventory.GuiContainerCreative
	Mouse location: Scaled: (294, 36). Absolute: (589, 406)
	Screen size: Scaled: (427, 240). Absolute: (854, 480). Scale factor of 2

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['EbicSD45'/92, l='MpServer', x=321.69, y=4.00, z=283.77]]
	Chunk stats: MultiplayerChunkCache: 441, 441
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (319,4,285), Chunk: (at 15,0,13 in 19,17; contains blocks 304,0,272 to 319,255,287), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 1115 game time, 1115 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 31 total; [EntitySlime['Slime'/68, l='MpServer', x=340.18, y=4.76, z=226.67], EntityHorse['Horse'/69, l='MpServer', x=338.93, y=4.00, z=240.80], EntityHorse['Horse'/70, l='MpServer', x=340.45, y=4.00, z=246.79], EntityChicken['Chicken'/71, l='MpServer', x=345.11, y=4.00, z=243.19], EntitySlime['Slime'/72, l='MpServer', x=364.32, y=5.10, z=333.25], EntitySlime['Slime'/76, l='MpServer', x=376.66, y=4.92, z=356.83], EntityHorse['Horse'/79, l='MpServer', x=393.73, y=4.00, z=297.15], EntityChicken['Chicken'/80, l='MpServer', x=399.14, y=4.00, z=298.48], EntityChicken['Chicken'/81, l='MpServer', x=396.50, y=4.00, z=296.50], EntitySheep['Sheep'/82, l='MpServer', x=385.72, y=4.00, z=298.55], EntityItemFrame['entity.ItemFrame.name'/20, l='MpServer', x=215.50, y=7.50, z=272.03], EntitySlime['Slime'/35, l='MpServer', x=253.89, y=5.08, z=235.00], EntitySlime['Slime'/36, l='MpServer', x=255.72, y=4.28, z=246.88], EntityVillager['Villager'/37, l='MpServer', x=244.50, y=5.00, z=280.50], EntitySlime['Slime'/38, l='MpServer', x=245.43, y=4.55, z=283.51], EntitySlime['Slime'/39, l='MpServer', x=250.85, y=4.00, z=298.82], EntitySlime['Slime'/40, l='MpServer', x=248.14, y=4.00, z=313.93], EntitySlime['Slime'/41, l='MpServer', x=243.34, y=4.42, z=364.22], EntityCow['Cow'/44, l='MpServer', x=253.14, y=4.00, z=283.74], EntityChicken['Chicken'/45, l='MpServer', x=261.50, y=4.00, z=289.50], EntityChicken['Chicken'/46, l='MpServer', x=262.50, y=4.00, z=288.50], EntityChicken['Chicken'/47, l='MpServer', x=270.17, y=4.00, z=288.55], EntitySlime['Slime'/48, l='MpServer', x=279.39, y=4.95, z=334.39], EntitySlime['Slime'/50, l='MpServer', x=297.67, y=4.28, z=216.26], EntityCow['Cow'/51, l='MpServer', x=291.12, y=4.00, z=233.36], EntityCow['Cow'/52, l='MpServer', x=299.50, y=4.00, z=225.50], EntityPlayerSP['EbicSD45'/92, l='MpServer', x=321.69, y=4.00, z=283.77], EntitySlime['Slime'/60, l='MpServer', x=301.89, y=4.27, z=204.33], EntityCow['Cow'/61, l='MpServer', x=304.50, y=4.00, z=233.50], EntityCow['Cow'/62, l='MpServer', x=312.15, y=4.00, z=230.57], EntitySlime['Slime'/63, l='MpServer', x=323.88, y=4.00, z=207.52]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:420)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2741)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:419)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 793059664 bytes (756 MB) / 1543503872 bytes (1472 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2847 9 mods loaded, 9 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                   | Version         | Source                                | Signature                                |
	|:------ |:-------------------- |:--------------- |:------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft            | 1.12.2          | minecraft.jar                         | None                                     |
	| LCHIJA | mcp                  | 9.42            | minecraft.jar                         | None                                     |
	| LCHIJA | FML                  | 8.0.99.99       | forge-1.12.2-14.23.5.2847.jar         | None                                     |
	| LCHIJA | forge                | 14.23.5.2847    | forge-1.12.2-14.23.5.2847.jar         | None                                     |
	| LCHIJA | replaymod            | 1.12.2-2.2.0-b7 | replaymod-1.12.2-2.2.0-b7.jar         | None                                     |
	| LCHIJA | trackapi             | 1.2             | TrackAPI-1.2.jar                      | None                                     |
	| LCHIJA | immersiverailroading | 1.7.2           | ImmersiveRailroading-1.7.2_1.12.2.jar | None                                     |
	| LCHIJA | universalmodcore     | 1.0.0           | ImmersiveRailroading-1.7.2_1.12.2.jar | None                                     |
	| LCHIJA | immersiveengineering | 0.12-89         | ImmersiveEngineering-0.12-89.jar      | 4cb49fcde3b43048c9889e0a3d083225da926334 |

	Loaded coremods (and transformers): 
IELoadingPlugin (ImmersiveEngineering-core-0.12-89.jar)
  blusunrize.immersiveengineering.common.asm.IEClassTransformer
LoadingPlugin (replaymod-1.12.2-2.2.0-b7.jar)
  
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 391.25' Renderer: 'Quadro K1100M/PCIe/SSE2'
	Launched Version: 1.12.2-forge1.12.2-14.23.5.2847
	LWJGL: 2.9.4
	OpenGL: Quadro K1100M/PCIe/SSE2 GL version 4.6.0 NVIDIA 391.25, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: DarkRaider's+Freight.zip, American+Diesel+Locomotive+Pack.zip
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i7-4712HQ CPU @ 2.30GHz

**Comment by shotbyapony** [comment]
What did you try before that fixed it?

**Comment by AndyNS1701** [comment]
I turned on vbos and it worked

**Comment by cam72cam** [comment]
I need to just ignore the minecraft VBO setting and use them in all cases.  Any modern (last 10 years) should have them.

**Comment by AndyNS1701** [comment]
How do i fix it???????

**Comment by shotbyapony** [comment]
I thought you said you fixed it.

**Comment by cam72cam** [comment]
Fixed in the latest test build, will be included in the next release.
