### ISSUE TITLE
rail turn bug

### ISSUE THREAD

**Issue by touhourailway** [TeamOpenIndustry/ImmersiveRailroading#790]
The game and the map will crashed after put a curve then change the rail [type: straight length:1 lock type:pixel lock]and just look to the ground.
here is the crashreport[I don't know how to check this]:

> ---- Minecraft Crash Report ----

WARNING: coremods are present:
  Inventory Tweaks Coremod ([背包整理]-InventoryTweaks-1.63.jar)
  JechCore ([JEI汉字搜索]JustEnoughCharacters-1.12.0-3.3.0.jar)
  CustomSkinLoader ([自定义皮肤]CustomSkinLoader_Forge-14.11.jar)
  IELoadingPlugin (ImmersiveEngineering-core-0.12-92.jar)
Contact their authors BEFORE contacting forge

// There are four lights!

Time: 5/2/20 9:17 PM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at cam72cam.immersiverailroading.track.BuilderIterator.<init>(BuilderIterator.java:100)
	at cam72cam.immersiverailroading.track.BuilderCubicCurve.<init>(BuilderCubicCurve.java:32)
	at cam72cam.immersiverailroading.track.BuilderStraight.<init>(BuilderStraight.java:14)
	at cam72cam.immersiverailroading.track.BuilderStraight.<init>(BuilderStraight.java:10)
	at cam72cam.immersiverailroading.util.RailInfo.constructBuilder(RailInfo.java:136)
	at cam72cam.immersiverailroading.util.RailInfo.getBuilder(RailInfo.java:130)
	at cam72cam.immersiverailroading.render.rail.RailBaseOverlayRender.doDraw(RailBaseOverlayRender.java:27)
	at cam72cam.immersiverailroading.render.rail.RailBaseOverlayRender.draw(RailBaseOverlayRender.java:84)
	at cam72cam.immersiverailroading.render.rail.RailRenderUtil.render(RailRenderUtil.java:23)
	at cam72cam.immersiverailroading.render.item.TrackBlueprintItemModel.renderMouseover(TrackBlueprintItemModel.java:98)
	at cam72cam.mod.render.GlobalRender.lambda$registerItemMouseover$4(GlobalRender.java:75)
	at cam72cam.mod.event.ClientEvents$ClientEventBus.lambda$onRenderMouseover$4(ClientEvents.java:107)
	at java.lang.Iterable.forEach(Unknown Source)
	at cam72cam.mod.event.Event.execute(Event.java:14)
	at cam72cam.mod.event.ClientEvents$ClientEventBus.onRenderMouseover(ClientEvents.java:107)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_16_ClientEventBus_onRenderMouseover_DrawBlockHighlightEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.client.ForgeHooksClient.onDrawBlockHighlight(ForgeHooksClient.java:191)
	at sun.reflect.GeneratedMethodAccessor76.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.optifine.reflect.Reflector.callBoolean(Reflector.java:680)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1820)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1614)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1385)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1119)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at cam72cam.immersiverailroading.track.BuilderIterator.<init>(BuilderIterator.java:100)
	at cam72cam.immersiverailroading.track.BuilderCubicCurve.<init>(BuilderCubicCurve.java:32)
	at cam72cam.immersiverailroading.track.BuilderStraight.<init>(BuilderStraight.java:14)
	at cam72cam.immersiverailroading.track.BuilderStraight.<init>(BuilderStraight.java:10)
	at cam72cam.immersiverailroading.util.RailInfo.constructBuilder(RailInfo.java:136)
	at cam72cam.immersiverailroading.util.RailInfo.getBuilder(RailInfo.java:130)
	at cam72cam.immersiverailroading.render.rail.RailBaseOverlayRender.doDraw(RailBaseOverlayRender.java:27)
	at cam72cam.immersiverailroading.render.rail.RailBaseOverlayRender.draw(RailBaseOverlayRender.java:84)
	at cam72cam.immersiverailroading.render.rail.RailRenderUtil.render(RailRenderUtil.java:23)
	at cam72cam.immersiverailroading.render.item.TrackBlueprintItemModel.renderMouseover(TrackBlueprintItemModel.java:98)
	at cam72cam.mod.render.GlobalRender.lambda$registerItemMouseover$4(GlobalRender.java:75)
	at cam72cam.mod.event.ClientEvents$ClientEventBus.lambda$onRenderMouseover$4(ClientEvents.java:107)
	at java.lang.Iterable.forEach(Unknown Source)
	at cam72cam.mod.event.Event.execute(Event.java:14)
	at cam72cam.mod.event.ClientEvents$ClientEventBus.onRenderMouseover(ClientEvents.java:107)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_16_ClientEventBus_onRenderMouseover_DrawBlockHighlightEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.client.ForgeHooksClient.onDrawBlockHighlight(ForgeHooksClient.java:191)
	at sun.reflect.GeneratedMethodAccessor76.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.optifine.reflect.Reflector.callBoolean(Reflector.java:680)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1820)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1614)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['touhourailway'/65, l='MpServer', x=2020.13, y=4.00, z=-676.05]]
	Chunk stats: MultiplayerChunkCache: 169, 169
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (2017,4,-679), Chunk: (at 1,0,9 in 126,-43; contains blocks 2016,0,-688 to 2031,255,-673), Region: (3,-2; contains chunks 96,-64 to 127,-33, blocks 1536,0,-1024 to 2047,255,-513)
	Level time: 1177 game time, 1177 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 39 total; [EntitySlime['史莱姆'/129, l='MpServer', x=1999.75, y=4.00, z=-639.81], EntitySlime['史莱姆'/131, l='MpServer', x=1989.87, y=4.00, z=-651.10], EntitySlime['史莱姆'/132, l='MpServer', x=2020.35, y=5.02, z=-679.13], EntitySlime['史莱姆'/135, l='MpServer', x=1991.23, y=4.92, z=-642.27], EntitySlime['史莱姆'/137, l='MpServer', x=1996.69, y=4.00, z=-670.64], EntityPlayerSP['touhourailway'/65, l='MpServer', x=2020.13, y=4.00, z=-676.05], EntitySlime['史莱姆'/141, l='MpServer', x=1942.72, y=4.00, z=-663.24], EntitySlime['史莱姆'/79, l='MpServer', x=2003.05, y=4.00, z=-664.39], EntitySlime['史莱姆'/143, l='MpServer', x=2041.00, y=4.00, z=-648.14], EntitySlime['史莱姆'/145, l='MpServer', x=1998.43, y=5.25, z=-639.05], EntitySlime['史莱姆'/83, l='MpServer', x=2035.82, y=4.00, z=-712.20], EntitySlime['史莱姆'/147, l='MpServer', x=2043.97, y=4.42, z=-719.84], EntityHorse['马'/84, l='MpServer', x=1995.89, y=4.00, z=-742.20], EntityHorse['马'/85, l='MpServer', x=1989.71, y=4.00, z=-744.90], EntitySlime['史莱姆'/149, l='MpServer', x=2032.25, y=4.50, z=-726.35], EntityCow['牛'/86, l='MpServer', x=1984.49, y=4.00, z=-741.85], EntitySlime['史莱姆'/150, l='MpServer', x=2058.30, y=4.00, z=-653.77], EntitySheep['羊'/89, l='MpServer', x=1983.50, y=4.00, z=-748.50], EntitySlime['史莱姆'/153, l='MpServer', x=1989.04, y=4.14, z=-652.41], EntitySheep['羊'/90, l='MpServer', x=1997.77, y=4.00, z=-731.54], EntitySheep['羊'/91, l='MpServer', x=2013.22, y=4.00, z=-737.20], EntitySlime['史莱姆'/155, l='MpServer', x=2068.85, y=4.00, z=-718.26], EntitySheep['羊'/93, l='MpServer', x=2007.90, y=4.00, z=-730.30], EntitySlime['史莱姆'/157, l='MpServer', x=1947.92, y=4.00, z=-634.32], EntitySlime['史莱姆'/158, l='MpServer', x=1983.10, y=4.00, z=-639.46], EntitySheep['羊'/96, l='MpServer', x=2006.50, y=4.00, z=-729.50], EntityPig['猪'/97, l='MpServer', x=2051.50, y=4.00, z=-628.50], EntitySlime['史莱姆'/161, l='MpServer', x=1988.65, y=4.00, z=-655.30], EntitySheep['羊'/98, l='MpServer', x=2050.50, y=4.00, z=-620.50], EntitySheep['羊'/99, l='MpServer', x=2048.50, y=4.00, z=-620.50], EntityCow['牛'/100, l='MpServer', x=2050.50, y=4.00, z=-626.50], EntitySheep['羊'/105, l='MpServer', x=1962.50, y=4.00, z=-656.50], EntitySheep['羊'/106, l='MpServer', x=1963.50, y=4.00, z=-653.50], EntitySheep['羊'/107, l='MpServer', x=1959.50, y=4.00, z=-650.50], EntitySheep['羊'/108, l='MpServer', x=1951.84, y=4.00, z=-657.24], EntityChicken['鸡'/111, l='MpServer', x=2086.50, y=4.00, z=-657.50], EntityChicken['鸡'/114, l='MpServer', x=2087.50, y=4.00, z=-660.50], EntityChicken['鸡'/117, l='MpServer', x=2089.50, y=4.00, z=-663.50], EntitySheep['羊'/120, l='MpServer', x=2081.50, y=4.00, z=-650.50]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:532)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2741)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:427)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_241, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 837466464 bytes (798 MB) / 2354585600 bytes (2245 MB) up to 4260102144 bytes (4062 MB)
	JVM Flags: 13 total; -Xss512K -XX:+AggressiveOpts -XX:+UseCompressedOops -XX:+UseCMSCompactAtFullCollection -XX:+UseFastAccessorMethods -XX:ParallelGCThreads=4 -XX:+UseConcMarkSweepGC -XX:CMSFullGCsBeforeCompaction=2 -XX:CMSInitiatingOccupancyFraction=70 -XX:-DisableExplicitGC -XX:TargetSurvivorRatio=90 -Xmx4096m -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2847 Optifine OptiFine_1.12.2_HD_U_F5 38 mods loaded, 38 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                   | Version                  | Source                                                    | Signature                                |
	|:------ |:-------------------- |:------------------------ |:--------------------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft            | 1.12.2                   | minecraft.jar                                             | None                                     |
	| LCHIJA | mcp                  | 9.42                     | minecraft.jar                                             | None                                     |
	| LCHIJA | FML                  | 8.0.99.99                | forge-1.12.2-14.23.5.2847.jar                             | None                                     |
	| LCHIJA | forge                | 14.23.5.2847             | forge-1.12.2-14.23.5.2847.jar                             | None                                     |
	| LCHIJA | jecharacters         | 1.12.0-3.3.0             | [JEI汉字搜索]JustEnoughCharacters-1.12.0-3.3.0.jar            | None                                     |
	| LCHIJA | jei                  | 4.15.0.268               | [JEI]_1.12.2-4.15.0.268.jar                               | None                                     |
	| LCHIJA | journeymap           | 1.12-5.4.9               | [旅行地图]-journeymap-1.12-5.4.9.jar                          | None                                     |
	| LCHIJA | neat                 | 1.4-17                   | [显血]-Neat+1.4-17.jar                                      | None                                     |
	| LCHIJA | sakura               | V0.0.8.2-MC1.12.2        | [樱花]Sakura-V0.0.8.2-MC1.12.2.jar                          | None                                     |
	| LCHIJA | inventorytweaks      | 1.63+release.109.220f184 | [背包整理]-InventoryTweaks-1.63.jar                           | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| LCHIJA | customskinloader     | 14.11                    | [自定义皮肤]CustomSkinLoader_Forge-14.11.jar                   | 52885f395e68f42e9b3b629ba56ecf606f7d4269 |
	| LCHIJA | anotheranticheat     | 2.0.0b                   | AnotherAntiCheat-1.12.2-2.0.0b.jar                        | None                                     |
	| LCHIJA | trackapi             | 1.2                      | TrackAPI-1.2.jar                                          | None                                     |
	| LCHIJA | immersiverailroading | 1.7.3                    | ImmersiveRailroading-1.7.3_1.12.2.jar                     | None                                     |
	| LCHIJA | universalmodcore     | 1.0.0                    | ImmersiveRailroading-1.7.3_1.12.2.jar                     | None                                     |
	| LCHIJA | railcraft            | 12.0.0                   | railcraft-12.0.0.jar                                      | a0c255ac501b2749537d5824bb0f0588bf0320fa |
	| LCHIJA | mtr                  | 3.0.0                    | MTR-1.12.2-alpha-test-0.0.1.jar                           | None                                     |
	| LCHIJA | customnpcs           | 1.12                     | 【npcmod】V1.jar                                            | None                                     |
	| LCHIJA | variedcommodities    | 1.12.2                   | 【npc物品】VariedCommodities_1.12.2.jar                       | None                                     |
	| LCHIJA | touhou_little_maid   | 1.1.9                    | 【东方女仆】touhoulittlemaid-1.12.2-1.1.9-release.jar           | None                                     |
	| LCHIJA | recipehandler        | 0.11                     | 【合成冲突】NoMoreRecipeConflict-0.11%281.12.2%29.jar           | None                                     |
	| LCHIJA | crafttweaker         | 4.1.20                   | 【自定义合成】.jar                                               | None                                     |
	| LCHIJA | cfm                  | 6.2.0                    | 【家具】cfm-6.2.0-mc1.12.2.jar                                | None                                     |
	| LCHIJA | bibliocraft          | 2.4.4                    | 【展示架】BiblioCraft.jar                                      | None                                     |
	| LCHIJA | mirror               | 1.12.2-0.2.0-1           | 【弹幕前置】mirror-1.12.2-0.2.0-1.jar                           | None                                     |
	| LCHIJA | danmakucore          | 1.12.2-0.6.0-10          | 【弹幕工艺】danmakucore-1.12.2-0.6.0-10.jar                     | None                                     |
	| LCHIJA | reforged             | 0.7.5                    | 【更多武器】DReforged-Mod-1.12.jar                              | None                                     |
	| LCHIJA | bonsaitrees          | 1.0.5                    | 【树木盆栽】bonsaitrees-1.0.5-b77.jar                           | None                                     |
	| LCHIJA | enhancedarmaments    | 1.3.17                   | 【武器科技树】enhancedarmaments-1.3.17.jar                       | None                                     |
	| LCHIJA | harvestcraft         | 1.12.2zb                 | 【潘马斯】Pam's+HarvestCraft+1.12.2zd+Surprise+for+Yogcast.jar | None                                     |
	| LCHIJA | cookingforblockheads | 6.4.70                   | 【烹饪书】CookingForBlockheads_1.12.2-6.4.70.jar               | None                                     |
	| LCHIJA | custommc             | 1.0v                     | 【自定义mod物品】.jar                                            | None                                     |
	| LCHIJA | ctgui                | 1.0.0                    | 【自定义合成】.jar                                               | None                                     |
	| LCHIJA | crafttweakerjei      | 2.0.3                    | 【自定义合成】.jar                                               | None                                     |
	| LCHIJA | teastory             | 3.3.2-B31.815-1.12.2     | 【茶风】TeaStory-3.3.2-B31.815-1.12.2.jar                     | None                                     |
	| LCHIJA | cucumber             | 1.1.3                    | 【魔法作物前置】Cucumber-1.12.2-1.1.3.jar                         | None                                     |
	| LCHIJA | mysticalagriculture  | 1.7.5                    | 【魔法作物】MysticalAgriculture-1.12.2-1.7.5.jar                | None                                     |
	| LCHIJA | immersiveengineering | 0.12-92                  | ImmersiveEngineering-0.12-92.jar                          | 4cb49fcde3b43048c9889e0a3d083225da926334 |

	Loaded coremods (and transformers): 
Inventory Tweaks Coremod ([背包整理]-InventoryTweaks-1.63.jar)
  invtweaks.forge.asm.ContainerTransformer
JechCore ([JEI汉字搜索]JustEnoughCharacters-1.12.0-3.3.0.jar)
  me.towdium.jecharacters.core.JechClassTransformer
CustomSkinLoader ([自定义皮肤]CustomSkinLoader_Forge-14.11.jar)
  customskinloader.forge.loader.LaunchWrapper
IELoadingPlugin (ImmersiveEngineering-core-0.12-92.jar)
  blusunrize.immersiveengineering.common.asm.IEClassTransformer
	Launched Version: 1.12.2-forge1.12.2-14.23.5.2847
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 1050 Ti/PCIe/SSE2 GL version 4.6.0 NVIDIA 432.00, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 喵玉追加.zip
	Current Language: 简体中文 (中国)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i3-7100 CPU @ 3.90GHz
	OptiFine Version: OptiFine_1.12.2_HD_U_F5
	OptiFine Build: 20191204-141934
	Render Distance Chunks: 6
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 432.00
	OpenGlRenderer: GeForce GTX 1050 Ti/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 4

**Comment by cam72cam** [comment]
Fixed in the latest test build, will be included in the next release.
