### ISSUE TITLE
Rendering Item Issue ( CRASH when right click while riding a loco or train cart )

### ISSUE THREAD

**Issue by marlonpupo24** [TeamOpenIndustry/ImmersiveRailroading#805]
Games crashes when I right click while riding a loco or train cart.

Template ---- Minecraft Crash Report ----

WARNING: coremods are present:
  ShutdownPatcher (mcef-1.12.2-1.11-coremod.jar)
  MalisisCorePlugin (malisiscore-1.12.2-6.5.1.jar)
  IELoadingPlugin (ImmersiveEngineering-core-0.12-92.jar)
  CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
  DLFMLCorePlugin (DynamicLights-1.12.2.jar)
Contact their authors BEFORE contacting forge

// You're mean.

Time: 6/4/20 5:51 PM
Description: Rendering item

java.lang.NullPointerException: Rendering item
	at cam72cam.immersiverailroading.render.item.StockItemModel.getSpriteKey(StockItemModel.java:57)
	at cam72cam.mod.render.ItemRender$BakedItemModel.func_188616_a(ItemRender.java:208)
	at net.minecraft.client.renderer.RenderItem.func_191967_a(RenderItem.java:168)
	at net.minecraft.client.renderer.RenderItem.func_191961_a(RenderItem.java:136)
	at net.minecraft.client.renderer.RenderItem.func_180454_a(RenderItem.java:216)
	at net.minecraft.client.renderer.RenderItem.func_191962_a(RenderItem.java:517)
	at net.minecraft.client.renderer.RenderItem.func_184391_a(RenderItem.java:559)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146977_a(GuiContainer.java:265)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:98)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:396)
	at sun.reflect.GeneratedMethodAccessor40.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.optifine.reflect.Reflector.callVoid(Reflector.java:660)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1457)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1119)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at cam72cam.immersiverailroading.render.item.StockItemModel.getSpriteKey(StockItemModel.java:57)
	at cam72cam.mod.render.ItemRender$BakedItemModel.func_188616_a(ItemRender.java:208)
	at net.minecraft.client.renderer.RenderItem.func_191967_a(RenderItem.java:168)
	at net.minecraft.client.renderer.RenderItem.func_191961_a(RenderItem.java:136)
	at net.minecraft.client.renderer.RenderItem.func_180454_a(RenderItem.java:216)
	at net.minecraft.client.renderer.RenderItem.func_191962_a(RenderItem.java:517)

-- Item being rendered --
Details:
	Item Type: cam72cam.mod.item.ItemBase$ItemInternal@234e5d7b
	Registry Name: immersiverailroading:item_rolling_stock
	Item Aux: 0
	Item NBT: {defID:"rolling_stock/passenger/btir_passenger_unu_streamliner.json",gauge:1.435d,display:{Name:"§rUNU Streamliner Passenger Car"}}
	Item Foil: false
Stacktrace:
	at net.minecraft.client.renderer.RenderItem.func_184391_a(RenderItem.java:559)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146977_a(GuiContainer.java:265)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:98)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:396)
	at sun.reflect.GeneratedMethodAccessor40.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.optifine.reflect.Reflector.callVoid(Reflector.java:660)

-- Screen render details --
Details:
	Screen name: cam72cam.mod.gui.container.ClientContainerBuilder
	Mouse location: Scaled: (240, 123). Absolute: (960, 493)
	Screen size: Scaled: (480, 247). Absolute: (1920, 986). Scale factor of 4

**Comment by AndyNS1701** [comment]
I have the same issue

**Comment by cam72cam** [comment]
Fixed in the latest test build, will be included in the next release.
