### ISSUE TITLE
[1.12.2] Server crash - java.lang.NullPointerException: Exception ticking world at cam72cam.immersiverailroading.tile.TileRail.save

### ISSUE THREAD

**Issue by ProsperCraft** [TeamOpenIndustry/ImmersiveRailroading#808]
https://gist.github.com/ProsperCraft/06b94d5987f6a2c137fdea022cca0563
ImmersiveRailroading-1.7.3_1.12.2.jar

TownCraft Modpack - https://www.curseforge.com/minecraft/modpacks/towncraft

I don't know what caused it, found this crash when sifting logs to report a nasty CME crash.

`java.lang.NullPointerException: Exception ticking world
	at cam72cam.immersiverailroading.tile.TileRail.save(TileRail.java:107)
	at cam72cam.mod.block.tile.TileEntity.save(TileEntity.java:375)
	at cam72cam.mod.block.tile.TileEntity.func_189515_b(TileEntity.java:112)
	at cam72cam.mod.block.tile.TileEntity.func_189517_E_(TileEntity.java:138)
	at net.minecraft.network.play.server.SPacketChunkData.<init>(SourceFile:52)
	at net.minecraft.server.management.PlayerChunkMapEntry.func_187272_b(PlayerChunkMapEntry.java:157)
	at net.minecraft.server.management.PlayerChunkMap.func_72693_b(PlayerChunkMap.java:205)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:320)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:888)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:466)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:779)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:625)
	at java.lang.Thread.run(Thread.java:748)`

**Comment by boxyourhead** [comment]
Yeah, i got this crash too. Here is the report.
java.lang.NullPointerException: Exception ticking world
	at cam72cam.immersiverailroading.tile.TileRail.save(TileRail.java:107)
	at cam72cam.mod.block.tile.TileEntity.save(TileEntity.java:375)
	at cam72cam.mod.block.tile.TileEntity.func_189515_b(TileEntity.java:112)
	at cam72cam.mod.block.tile.TileEntity.func_189518_D_(TileEntity.java:119)
	at net.minecraft.server.management.PlayerChunkMapEntry.func_187273_a(PlayerChunkMapEntry.java:288)
	at net.minecraft.server.management.PlayerChunkMapEntry.func_187280_d(PlayerChunkMapEntry.java:273)
	at net.minecraft.server.management.PlayerChunkMap.func_72693_b(PlayerChunkMap.java:182)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:227)
	at net.optifine.override.WorldServerOF.func_72835_b(WorldServerOF.java:39)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:756)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:252)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

**Comment by DDX5-DX12-Media** [comment]
@TeamOpenIndustry
Looking At The Lines Of Code That Caused The Crash. Its To Do With NBT Data.
Having This Same Issue Happen To Me, So I Thought I Would Look At The Lines Responsible For The Crash.


@ProsperCraft @boxyourhead, Just A Note For You Both, Try VanillaFix As It Saves A Lot Of Hassle

**Comment by km00700** [comment]
There is a bug that has recently been discovered but has yet to be fixed where an NPE will be thrown if a multiple track tiles overlap in a single location, as there's not yet a handler for when two tracks respond. The fix should hopefully be out in one of the next few updates.

**Comment by cam72cam** [comment]
Fixed in the test-builds, will be in the next release.
