### ISSUE TITLE
NullPointerException when engine quickly explodes

### ISSUE THREAD

**Issue by PlanMan1717** [TeamOpenIndustry/ImmersiveRailroading#857]
What happened:

So I filled the coal slots with fuel in a steam locomotive.
I fed it water via. its tender.

The little bit of water caused the temperature to skyrocket, and the steam pressure valve went off in about a fifth of a second.
Looking into the report, it looks like the explosion is what crashed the game.

Possibly the engine was blown up while the data was being processed about the explosion.

Makes some sense.

Also the game crashed.

Note: I was using the locomotive from a content pack.

The K37 Mikado or whatever from D&RGW Loco Pack.

```
---- Minecraft Crash Report ----

WARNING: coremods are present:
  IELoadingPlugin (ImmersiveEngineering-core-0.12-98.jar)
  weaponlib (mw_2.0-0.4.5.2_mc1.12.2.jar)
  CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
Contact their authors BEFORE contacting forge

// You should try our sister game, Minceraft!

Time: 11/5/20 9:51 PM
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
	at cam72cam.mod.entity.Entity.getBlockPosition(Entity.java:55)
	at cam72cam.immersiverailroading.entity.EntityBuildableRollingStock.onDamage(EntityBuildableRollingStock.java:382)
	at cam72cam.immersiverailroading.entity.Freight.onDamage(Freight.java:183)
	at cam72cam.mod.entity.ModdedEntity.func_70097_a(ModdedEntity.java:176)
	at net.minecraft.world.Explosion.func_77278_a(Explosion.java:159)
	at cam72cam.mod.entity.Entity.createExplosion(Entity.java:246)
	at cam72cam.immersiverailroading.entity.LocomotiveSteam.onTick(LocomotiveSteam.java:697)
	at cam72cam.mod.entity.ModdedEntity.func_70071_h_(ModdedEntity.java:147)
	at net.minecraft.world.World.func_72866_a(World.java:1996)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1958)
	at net.minecraft.world.World.func_72939_s(World.java:1762)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:279)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at cam72cam.mod.entity.Entity.getBlockPosition(Entity.java:55)
	at cam72cam.immersiverailroading.entity.EntityBuildableRollingStock.onDamage(EntityBuildableRollingStock.java:382)
	at cam72cam.immersiverailroading.entity.Freight.onDamage(Freight.java:183)
	at cam72cam.mod.entity.ModdedEntity.func_70097_a(ModdedEntity.java:176)
	at net.minecraft.world.Explosion.func_77278_a(Explosion.java:159)
	at cam72cam.mod.entity.Entity.createExplosion(Entity.java:246)
	at cam72cam.immersiverailroading.entity.LocomotiveSteam.onTick(LocomotiveSteam.java:697)
	at cam72cam.mod.entity.ModdedEntity.func_70071_h_(ModdedEntity.java:147)
	at net.minecraft.world.World.func_72866_a(World.java:1996)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1958)

-- Entity being ticked --
Details:
	Entity Type: immersiverailroading:cartank (cam72cam.mod.entity.ModdedEntity)
	Entity ID: 1343
	Entity Name: immersiverailroading:locomotivesteam
	Entity's Exact location: 80.51, 24.40, -557.45
	Entity's Block location: World: (80,24,-558), Chunk: (at 0,1,2 in 5,-35; contains blocks 80,0,-560 to 95,255,-545), Region: (0,-2; contains chunks 0,-64 to 31,-33, blocks 0,0,-1024 to 511,255,-513)
	Entity's Momentum: 0.00, 0.00, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1762)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)

-- Affected level --
Details:
	Level name: Test
	All players: 1 total; [EntityPlayerMP['PlanMan1717'/107, l='Test', x=81.13, y=26.10, z=-547.91]]
	Chunk stats: ServerChunkCache: 1940 Drop: 0
	Level seed: -2157850774033532984
	Level generator: ID 01 - flat, ver 0. Features enabled: true
	Level generator options: 3;minecraft:bedrock,20*minecraft:stone,2*minecraft:dirt,minecraft:grass;1;village
	Level spawn location: World: (195,4,940), Chunk: (at 3,0,12 in 12,58; contains blocks 192,0,928 to 207,255,943), Region: (0,1; contains chunks 0,32 to 31,63, blocks 0,0,512 to 511,255,1023)
	Level time: 18843 game time, 18843 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 21303 (now: false), thunder time: 106729 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:279)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 4569585336 bytes (4357 MB) / 8589934592 bytes (8192 MB) up to 8589934592 bytes (8192 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx8G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2854 Optifine OptiFine_1.12.2_HD_U_F5 26 mods loaded, 26 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                   | Version           | Source                                        | Signature                                |
	|:------ |:-------------------- |:----------------- |:--------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft            | 1.12.2            | minecraft.jar                                 | None                                     |
	| LCHIJA | mcp                  | 9.42              | minecraft.jar                                 | None                                     |
	| LCHIJA | FML                  | 8.0.99.99         | forge-1.12.2-14.23.5.2854.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge                | 14.23.5.2854      | forge-1.12.2-14.23.5.2854.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | ctm                  | MC1.12.2-1.0.2.31 | CTM-MC1.12.2-1.0.2.31.jar                     | None                                     |
	| LCHIJA | jei                  | 4.15.0.268        | jei_1.12.2-4.15.0.268.jar                     | None                                     |
	| LCHIJA | chisel               | MC1.12.2-1.0.2.45 | Chisel-MC1.12.2-1.0.2.45.jar                  | None                                     |
	| LCHIJA | flansmod             | 5.5.2             | Flan's Mod-1.12.2-5.5.2.jar                   | None                                     |
	| LCHIJA | flansmodapocalypse   | 1.0               | Flan's Mod-1.12.2-5.5.2.jar                   | None                                     |
	| LCHIJA | furenikusroads       | 1.1.8             | Fureniku's+Roads-1.1.8.jar                    | None                                     |
	| LCHIJA | cfm                  | 6.3.1             | furniture-6.3.1-1.12.2.jar                    | None                                     |
	| LCHIJA | horse_colors         | 1.12.2-1.2.6      | horse_colors-1.12.2-1.3.6.a.jar               | None                                     |
	| LCHIJA | mts                  | 19.8.0            | Immersive+Vehicles-1.12.2-19.8.0.jar          | None                                     |
	| LCHIJA | trackapi             | 1.2               | TrackAPI-1.2.jar                              | None                                     |
	| LCHIJA | immersiverailroading | 1.7.3             | ImmersiveRailroading-1.7.3_1.12.2.jar         | None                                     |
	| LCHIJA | universalmodcore     | 1.0.0             | ImmersiveRailroading-1.7.3_1.12.2.jar         | None                                     |
	| LCHIJA | industrialrenewal    | 0.19.0            | IndustrialRenewal_1.12.2-0.19.0.jar           | None                                     |
	| LCHIJA | journeymap           | 1.12.2-5.5.5      | journeymap-1.12.2-5.5.5.jar                   | None                                     |
	| LCHIJA | melvinssignpack      | 1.0.0             | Melvins_Simple_Sign_Pack-Release-1.0.jar      | None                                     |
	| LCHIJA | mtsofficialpack      | 19.0.0            | MTS_Official_Pack_V19.jar                     | None                                     |
	| LCHIJA | mw                   | 0.4.5.2           | mw_2.0-0.4.5.2_mc1.12.2.jar                   | None                                     |
	| LCHIJA | signal_stuff         | 2.2               | Trackside_Decor_2.2.jar                       | None                                     |
	| LCHIJA | trafficcontrol       | 0.3.2             | trafficcontrol-0.3.2.jar                      | None                                     |
	| LCHIJA | twilightforest       | 3.11.1021         | twilightforest-1.12.2-3.11.1021-universal.jar | None                                     |
	| LCHIJA | worldedit            | 6.1.10            | worldedit-forge-mc1.12.2-6.1.10-dist.jar      | None                                     |
	| LCHIJA | immersiveengineering | 0.12-98           | ImmersiveEngineering-0.12-98.jar              | None                                     |

	Loaded coremods (and transformers): 
IELoadingPlugin (ImmersiveEngineering-core-0.12-98.jar)
  blusunrize.immersiveengineering.common.asm.IEClassTransformer
weaponlib (mw_2.0-0.4.5.2_mc1.12.2.jar)
  com.vicmatskiv.weaponlib.core.WeaponlibClassTransformer
CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
  team.chisel.ctm.client.asm.CTMTransformer
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['PlanMan1717'/107, l='Test', x=81.13, y=26.10, z=-547.91]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	OptiFine Version: OptiFine_1.12.2_HD_U_F5
	OptiFine Build: 20191204-141934
	Render Distance Chunks: 20
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: BSL_v7.2.zip
	OpenGlVersion: 4.6.0 NVIDIA 442.19
	OpenGlRenderer: GeForce GTX 1660 Ti with Max-Q Design/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 8
```

**Comment by Larky2k** [comment]
You need to put water in first then the coal

**Comment by PlanMan1717** [comment]
Yeah, I know. But this shouldn't be a problem in the first place.

**Comment by PlanMan1717** [comment]
And it looks like the underlying problem is much more important.
Plus, I think it's unrelated to the heating.

**Comment by cam72cam** [comment]
Fixed in the most recent test build

**Comment by Jimmy805** [comment]
> 在最新的测试版本中修复
Just out of curiosity, when are you likely to release the new version?
