### ISSUE TITLE
Can't melt steel in the casting

### ISSUE THREAD

**Issue by miaowwwwww** [TeamOpenIndustry/ImmersiveRailroading#908]
**Describe the bug**  
I cant melt steel in the casting

**How to reproduce**  
set up a casting, 
try to melt it
It won't

**Expected behavior**  
let the steel be melted

**Screenshots**  
![image](https://user-images.githubusercontent.com/49871378/104775736-b5318b80-572d-11eb-81fc-50ca85f2f12c.png)

**System Information**  
 OS: Windows 10 
 <br>System Memory: 16g
 <br>Allocated Memory: 8g
 <br>CPU: Intel I7 7700k
 <br>GPU: GeForce GTX 1050 Ti
 <br>IR-Version: 1.7.10-forge-1.8.0-7e0f82
 <br>Forge-Version: Forge{10.13.4.1614}  1.7.10

**Modlist**  
I tested the bug with only te and ic2, it bugs the same way, so I don't think it is another mod problem.
![image](https://user-images.githubusercontent.com/49871378/104776234-9ed7ff80-572e-11eb-8161-c820bf01cd2b.png)
![image](https://user-images.githubusercontent.com/49871378/104776267-a9929480-572e-11eb-870f-e325415108a7.png)

 
**latest.log**
the bug is not doing something, so I don't think the log provides anything. the log is I used a scanner from Gregtech to get info.
[11:16:36] [Client thread/INFO]: cam72cam.mod.gui.screen.ScreenBuilder
[11:16:36] [Client thread/INFO]: [CHAT] --- X: 34 Y: 83 Z: 239 ---
[11:16:36] [Client thread/INFO]: [CHAT] Name: tile.immersiverailroading:multiblock  MetaData: 0
[11:16:36] [Client thread/INFO]: [CHAT] Registry: universalmodcore:immersiverailroading:multiblock
[11:16:36] [Client thread/INFO]: [CHAT] Block Class: class cam72cam.mod.block.BlockTypeEntity$BlockTypeInternal
[11:16:36] [Client thread/INFO]: [CHAT] TileEntity Class: class cam72cam.mod.block.tile.TileEntityTickable
[11:16:36] [Client thread/INFO]: [CHAT] Hardness: 0.2  Blast Resistance: 1.0 (TNT Blastable)
[11:16:36] [Client thread/INFO]: [CHAT] Tool to Harvest: None (-1)
[11:16:46] [Client thread/INFO]: net.minecraft.client.gui.GuiChat
[11:16:50] [Client thread/INFO]: cam72cam.mod.gui.screen.ScreenBuilder
[11:16:50] [Client thread/INFO]: [CHAT] --- X: 38 Y: 83 Z: 236 ---
[11:16:50] [Client thread/INFO]: [CHAT] Name: tile.immersiverailroading:multiblock  MetaData: 0
[11:16:50] [Client thread/INFO]: [CHAT] Registry: universalmodcore:immersiverailroading:multiblock
[11:16:50] [Client thread/INFO]: [CHAT] Block Class: class cam72cam.mod.block.BlockTypeEntity$BlockTypeInternal
[11:16:50] [Client thread/INFO]: [CHAT] TileEntity Class: class cam72cam.mod.block.tile.TileEntityTickable
[11:16:50] [Client thread/INFO]: [CHAT] Hardness: 0.2  Blast Resistance: 1.0 (TNT Blastable)
[11:16:50] [Client thread/INFO]: [CHAT] Tool to Harvest: None (-1)
[11:16:55] [Client thread/INFO]: cam72cam.mod.gui.screen.ScreenBuilder
[11:16:55] [Client thread/INFO]: [CHAT] --- X: 35 Y: 76 Z: 239 ---
[11:16:55] [Client thread/INFO]: [CHAT] Name: tile.immersiverailroading:multiblock  MetaData: 0
[11:16:55] [Client thread/INFO]: [CHAT] Registry: universalmodcore:immersiverailroading:multiblock
[11:16:55] [Client thread/INFO]: [CHAT] Block Class: class cam72cam.mod.block.BlockTypeEntity$BlockTypeInternal
[11:16:55] [Client thread/INFO]: [CHAT] TileEntity Class: class cam72cam.mod.block.tile.TileEntityTickable
[11:16:55] [Client thread/INFO]: [CHAT] Hardness: 0.2  Blast Resistance: 1.0 (TNT Blastable)
[11:16:55] [Client thread/INFO]: [CHAT] Tool to Harvest: None (-1)
[11:17:07] [Client thread/INFO]: net.minecraft.client.gui.inventory.GuiContainerCreative
[11:17:07] [Client thread/INFO]: net.minecraft.client.gui.inventory.GuiContainerCreative$ContainerCreative
[11:17:08] [ForkJoinPool-1-worker-4/WARN]: Error in item tooltip.
java.util.MissingFormatArgumentException: Format specifier '%s'
	at java.util.Formatter.format(Unknown Source) ~[?:1.8.0_261]
	at java.util.Formatter.format(Unknown Source) ~[?:1.8.0_261]
	at java.lang.String.format(Unknown Source) ~[?:1.8.0_261]
	at scala.collection.immutable.StringLike$class.format(StringLike.scala:287) ~[StringLike$class.class:?]
	at scala.collection.immutable.StringOps.format(StringOps.scala:30) ~[StringOps.class:?]
	at li.cil.oc.util.Tooltip$.get(Tooltip.scala:19) ~[Tooltip$.class:?]
	at li.cil.oc.common.item.traits.Delegate$class.tooltipLines(Delegate.scala:85) ~[Delegate$class.class:?]
	at li.cil.oc.common.item.Server.tooltipLines(Server.scala:17) ~[Server.class:?]
	at li.cil.oc.common.item.Delegator.func_77624_a(Delegator.scala:192) ~[Delegator.class:?]
	at net.minecraft.item.ItemStack.func_82840_a(ItemStack.java:525) ~[add.class:?]
	at codechicken.nei.guihook.GuiContainerManager.itemDisplayNameMultiline(GuiContainerManager.java:122) ~[GuiContainerManager.class:?]
	at codechicken.nei.guihook.GuiContainerManager.concatenatedDisplayName(GuiContainerManager.java:165) ~[GuiContainerManager.class:?]
	at codechicken.nei.api.ItemInfo.getSearchName(ItemInfo.java:517) ~[ItemInfo.class:?]
	at codechicken.nei.ItemList$PatternItemFilter.matches(ItemList.java:67) ~[ItemList$PatternItemFilter.class:?]
	at codechicken.nei.ItemList$AnyMultiItemFilter.matches(ItemList.java:112) ~[ItemList$AnyMultiItemFilter.class:?]
	at codechicken.nei.ItemList$AllMultiItemFilter.matches(ItemList.java:87) ~[ItemList$AllMultiItemFilter.class:?]
	at codechicken.nei.ItemList$2.lambda$null$0(ItemList.java:255) ~[ItemList$2.class:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source) [?:1.8.0_261]
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Unknown Source) [?:1.8.0_261]
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source) [?:1.8.0_261]
	at java.util.stream.ForEachOps$ForEachTask.compute(Unknown Source) [?:1.8.0_261]
	at java.util.concurrent.CountedCompleter.exec(Unknown Source) [?:1.8.0_261]
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) [?:1.8.0_261]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source) [?:1.8.0_261]
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) [?:1.8.0_261]
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) [?:1.8.0_261]

**Additional context**  
the 1.7.3 version does not have this problem, and the bug version is from higher versions mc. So I'm guessing that It needs something from a higher version.

**Comment by cam72cam** [comment]
Fixed in the next version (ref 96f93dda)
