### ISSUE TITLE
Error encoding field info in class cam72cam.immersiverailroading.tile.TileRail

### ISSUE THREAD

**Issue by v-oz** [TeamOpenIndustry/ImmersiveRailroading#911]
Hi there.

I've got this crash while put track in new world

```
---- Minecraft Crash Report ----
// Would you like a cupcake?

Time: 21.01.2021, 20:50
Description: Exception ticking world

java.lang.RuntimeException: cam72cam.mod.serialization.SerializationException: Error encoding field info in class cam72cam.immersiverailroading.tile.TileRail
	at cam72cam.mod.block.tile.TileEntity.func_189515_b(TileEntity.java:229) ~[?:1.0.0] {re:classloading}
	at cam72cam.mod.block.tile.TileEntity.getUpdateTag(TileEntity.java:256) ~[?:1.0.0] {re:classloading}
	at cam72cam.mod.block.tile.TileEntity.func_189518_D_(TileEntity.java:239) ~[?:1.0.0] {re:classloading}
	at net.minecraft.world.server.ChunkHolder.func_219305_a(ChunkHolder.java:221) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.server.ChunkHolder.func_219274_a(ChunkHolder.java:208) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.server.ServerChunkProvider.func_223434_a(SourceFile:378) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at it.unimi.dsi.fastutil.longs.Long2ObjectLinkedOpenHashMap$1.forEach(Long2ObjectLinkedOpenHashMap.java:1661) ~[fastutil-8.2.1.jar:?] {}
	at com.google.common.collect.Iterables$UnmodifiableIterable.forEach(Iterables.java:105) ~[guava-21.0.jar:?] {}
	at net.minecraft.world.server.ServerChunkProvider.func_217220_m(SourceFile:371) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.server.ServerChunkProvider.func_217207_a(SourceFile:340) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:313) ~[?:?] {re:classloading,xf:fml:immersiveengineering:IE block update callback}
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:849) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:784) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:114) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:637) [?:?] {re:classloading,pl:accesstransformer:B}
	at java.lang.Thread.run(Thread.java:832) [?:?] {}
Caused by: cam72cam.mod.serialization.SerializationException: Error encoding field info in class cam72cam.immersiverailroading.tile.TileRail
	at cam72cam.mod.serialization.TagSerializer.lambda$init$1(TagSerializer.java:108) ~[?:1.0.0] {re:classloading}
	at cam72cam.mod.serialization.TagSerializer.lambda$init$3(TagSerializer.java:127) ~[?:1.0.0] {re:classloading}
	at cam72cam.mod.serialization.TagSerializer.serialize(TagSerializer.java:156) ~[?:1.0.0] {re:classloading}
	at cam72cam.mod.block.tile.TileEntity.func_189515_b(TileEntity.java:225) ~[?:1.0.0] {re:classloading}
	... 15 more
Caused by: cam72cam.mod.serialization.SerializationException: Unable to access field settings in class class cam72cam.immersiverailroading.util.RailInfo
	at cam72cam.mod.serialization.TagSerializer.init(TagSerializer.java:68) ~[?:1.0.0] {re:classloading}
	at cam72cam.mod.serialization.TagSerializer.serialize(TagSerializer.java:155) ~[?:1.0.0] {re:classloading}
	at cam72cam.immersiverailroading.util.RailInfo$TagMapper.lambda$apply$0(RailInfo.java:343) ~[?:1.15.2-forge-1.8.0] {re:classloading}
	at cam72cam.mod.serialization.TagMapper$TagAccessor.lambda$new$0(TagMapper.java:17) ~[?:1.0.0] {re:classloading}
	at cam72cam.mod.serialization.TagSerializer.lambda$init$1(TagSerializer.java:106) ~[?:1.0.0] {re:classloading}
	at cam72cam.mod.serialization.TagSerializer.lambda$init$3(TagSerializer.java:127) ~[?:1.0.0] {re:classloading}
	at cam72cam.mod.serialization.TagSerializer.serialize(TagSerializer.java:156) ~[?:1.0.0] {re:classloading}
	at cam72cam.mod.block.tile.TileEntity.func_189515_b(TileEntity.java:225) ~[?:1.0.0] {re:classloading}
	... 15 more
Caused by: java.lang.NoSuchFieldException: modifiers
	at java.lang.Class.getDeclaredField(Class.java:2489) ~[?:?] {}
	at cam72cam.mod.serialization.TagSerializer.init(TagSerializer.java:64) ~[?:1.0.0] {re:classloading}
	at cam72cam.mod.serialization.TagSerializer.serialize(TagSerializer.java:155) ~[?:1.0.0] {re:classloading}
	at cam72cam.immersiverailroading.util.RailInfo$TagMapper.lambda$apply$0(RailInfo.java:343) ~[?:1.15.2-forge-1.8.0] {re:classloading}
	at cam72cam.mod.serialization.TagMapper$TagAccessor.lambda$new$0(TagMapper.java:17) ~[?:1.0.0] {re:classloading}
	at cam72cam.mod.serialization.TagSerializer.lambda$init$1(TagSerializer.java:106) ~[?:1.0.0] {re:classloading}
	at cam72cam.mod.serialization.TagSerializer.lambda$init$3(TagSerializer.java:127) ~[?:1.0.0] {re:classloading}
	at cam72cam.mod.serialization.TagSerializer.serialize(TagSerializer.java:156) ~[?:1.0.0] {re:classloading}
	at cam72cam.mod.block.tile.TileEntity.func_189515_b(TileEntity.java:225) ~[?:1.0.0] {re:classloading}
	... 15 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at cam72cam.mod.block.tile.TileEntity.func_189515_b(TileEntity.java:229)
	at cam72cam.mod.block.tile.TileEntity.getUpdateTag(TileEntity.java:256)
	at cam72cam.mod.block.tile.TileEntity.func_189518_D_(TileEntity.java:239)
	at net.minecraft.world.server.ChunkHolder.func_219305_a(ChunkHolder.java:221)
	at net.minecraft.world.server.ChunkHolder.func_219274_a(ChunkHolder.java:208)
	at net.minecraft.world.server.ServerChunkProvider.func_223434_a(SourceFile:378)
	at it.unimi.dsi.fastutil.longs.Long2ObjectLinkedOpenHashMap$1.forEach(Long2ObjectLinkedOpenHashMap.java:1661)
	at com.google.common.collect.Iterables$UnmodifiableIterable.forEach(Iterables.java:105)
	at net.minecraft.world.server.ServerChunkProvider.func_217220_m(SourceFile:371)
	at net.minecraft.world.server.ServerChunkProvider.func_217207_a(SourceFile:340)
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:313)

-- Affected level --
Details:
	All players: 1 total; [ServerPlayerEntity['ptichkaYT'/1317, l='Новый мир', x=-248.40, y=4.00, z=149.96]]
	Chunk stats: ServerChunkCache: 2412
	Level dimension: DimensionType{minecraft:overworld}
	Level name: Новый мир
	Level seed: 8492301284506257081
	Level generator: ID 01 - flat, ver 0. Features enabled: true
	Level generator options: {}
	Level spawn location: World: (-96,4,160), Chunk: (at 0,0,0 in -6,10; contains blocks -96,0,160 to -81,255,175), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 41122 game time, 41122 day time
	Known server brands: forge
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 109802 (now: false), thunder time: 112323 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:849)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:784)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:114)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:637)
	at java.base/java.lang.Thread.run(Thread.java:832)

-- System Details --
Details:
	Minecraft Version: 1.15.2
	Minecraft Version ID: 1.15.2
	Operating System: Linux (amd64) version 5.10.1-1-default
	Java Version: 14.0.2, N/A
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1135825560 bytes (1083 MB) / 2147483648 bytes (2048 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 4
	JVM Flags: 8 total; -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 5.1.2+70+master.2845bb9
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.2.jar mixin PLUGINSERVICE 
		/eventbus-2.2.0-service.jar eventbus PLUGINSERVICE 
		/forge-1.15.2-31.2.45.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.15.2-31.2.45.jar runtime_enum_extender PLUGINSERVICE 
		/forge-1.15.2-31.2.45.jar capability_inject_definalize PLUGINSERVICE 
		/accesstransformers-2.1.3-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.15.2-31.2.45.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.2.jar mixin TRANSFORMATIONSERVICE 
		/forge-1.15.2-31.2.45.jar fml TRANSFORMATIONSERVICE 
	FML: 31.2
	Forge: net.minecraftforge:31.2.45
	FML Language Providers: 
		javafml@31.2
		minecraft@1
	Mod List: 
		forge-1.15.2-31.2.45-client.jar Minecraft {minecraft@1.15.2 DONE}
		TrackAPI-1.15.2-forge-1.2.1.jar TrackAPI {trackapi@1.2 DONE}
		Paraglider_1.15.2_1.2.1.1.jar Paraglider {paraglider@1.2.1.1 DONE}
		forge-1.15.2-31.2.45-universal.jar Forge {forge@31.2.45 DONE}
		pneumaticcraft_repressurized_1.15.2_1.5.3_89.jar PneumaticCraft: Repressurized {pneumaticcraft@1.15.2-1.5.3-89 DONE}
		ImmersiveEngineering_1.15.2_4.1.1_125.jar Immersive Engineering {immersiveengineering@1.15.2-4.1.1-125 DONE}
		gulliver_2.0.0.jar Gulliver-1.15.2 {gulliver@2.0.0 DONE}
		create_mc1.15.2_v0.3e.jar Create {create@mc1.15.2_v0.3e DONE}
		TerraForged_1.15.2_0.1.3.jar TerraForged {terraforged@0.1.3 DONE}
		ImmersiveRailroading-1.15.2-forge-1.8.0.1.jar Immersive Railroading {immersiverailroading@1.15.2-forge-1.8.0 DONE}
		UniversalModCore-1.15.2-forge-1.0.0-fixed.jar Universal Mod Core {universalmodcore@1.0.0 DONE}
	Player Count: 1 / 8; [ServerPlayerEntity['ptichkaYT'/1317, l='Новый мир', x=-248.40, y=4.00, z=149.96]]
	Data Packs: mod:gulliver (incompatible), vanilla, mod:trackapi, mod:paraglider, mod:forge (incompatible), mod:pneumaticcraft, mod:immersiveengineering (incompatible), mod:create, mod:terraforged, mod:immersiverailroading, mod:universalmodcore
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'forge'
```

**Comment by noahboegli** [comment]
Hi
I have the same issue
Did you manage to solve it?

**Comment by cam72cam** [comment]
This is due to newer java versions being unsupported, please downgrade to 1.8 for now

**Comment by noahboegli** [comment]
That worked, thanks!
