### ISSUE TITLE
Crash shortly after placing tracks

### ISSUE THREAD

**Issue by biauk** [TeamOpenIndustry/ImmersiveRailroading#932]
It's second time something like that happens.

---- Minecraft Crash Report ----
// Don't do that.

Time: 12.02.21 12:42
Description: Batching chunks

java.util.ConcurrentModificationException: null
	at java.util.HashMap$HashIterator.nextNode(Unknown Source) ~[?:1.8.0_261] {}
	at java.util.HashMap$KeyIterator.next(Unknown Source) ~[?:1.8.0_261] {}
	at java.util.AbstractCollection.addAll(Unknown Source) ~[?:1.8.0_261] {}
	at java.util.HashSet.<init>(Unknown Source) ~[?:1.8.0_261] {}
	at com.google.common.collect.Sets.newHashSet(Sets.java:273) ~[guava-21.0.jar:?] {}
	at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher$ChunkRender.func_228931_a_(ChunkRenderDispatcher.java:621) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher$ChunkRender.access$500(ChunkRenderDispatcher.java:353) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher$ChunkRender$RebuildTask.func_225618_a_(ChunkRenderDispatcher.java:719) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher.lambda$runTask$1(ChunkRenderDispatcher.java:182) ~[?:?] {re:classloading,xf:OptiFine:default}
	at java.util.concurrent.CompletableFuture.uniCompose(Unknown Source) ~[?:1.8.0_261] {}
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(Unknown Source) ~[?:1.8.0_261] {}
	at java.util.concurrent.CompletableFuture.postComplete(Unknown Source) ~[?:1.8.0_261] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source) ~[?:1.8.0_261] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(Unknown Source) ~[?:1.8.0_261] {}
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[?:1.8.0_261] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source) ~[?:1.8.0_261] {}
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) ~[?:1.8.0_261] {re:computing_frames}
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) ~[?:1.8.0_261] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at java.util.HashMap$HashIterator.nextNode(Unknown Source) ~[?:1.8.0_261] {}
	at java.util.HashMap$KeyIterator.next(Unknown Source) ~[?:1.8.0_261] {}
	at java.util.AbstractCollection.addAll(Unknown Source) ~[?:1.8.0_261] {}
	at java.util.HashSet.<init>(Unknown Source) ~[?:1.8.0_261] {}
	at com.google.common.collect.Sets.newHashSet(Sets.java:273) ~[guava-21.0.jar:?] {}
	at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher$ChunkRender.func_228931_a_(ChunkRenderDispatcher.java:621) ~[?:?] {re:classloading,xf:OptiFine:default}
-- Affected level --
Details:
	All players: 1 total; [ClientPlayerEntity['biauk'/112, l='ClientLevel', x=-454.85, y=76.54, z=905.26]]
	Chunk stats: Client Chunk Cache: 729, 483
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,79,0), Chunk: (at 0,4,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 8030976 game time, 9083204 day time
	Server brand: forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.world.ClientWorld.func_72914_a(ClientWorld.java:617) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2024) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher.lambda$runTask$3(ChunkRenderDispatcher.java:188) ~[?:?] {re:classloading,xf:OptiFine:default}
	at java.util.concurrent.CompletableFuture.uniWhenComplete(Unknown Source) ~[?:1.8.0_261] {}
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(Unknown Source) ~[?:1.8.0_261] {}
	at java.util.concurrent.CompletableFuture.postComplete(Unknown Source) ~[?:1.8.0_261] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source) ~[?:1.8.0_261] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(Unknown Source) ~[?:1.8.0_261] {}
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[?:1.8.0_261] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source) ~[?:1.8.0_261] {}
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) ~[?:1.8.0_261] {re:computing_frames}
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) ~[?:1.8.0_261] {}

-- System Details --
Details:
	Minecraft Version: 1.16.4
	Minecraft Version ID: 1.16.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_261, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 772593720 bytes (736 MB) / 2134114304 bytes (2035 MB) up to 2134114304 bytes (2035 MB)
	CPUs: 4
	JVM Flags: 6 total; -Xmx2G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	ModLauncher: 8.0.6+85+master.325de55
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.2.jar mixin PLUGINSERVICE 
		/eventbus-3.0.5-service.jar eventbus PLUGINSERVICE 
		/forge-1.16.4-35.1.15.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.4-35.1.15.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.2.0-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.4-35.1.15.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.4-35.1.15.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.2.jar mixin TRANSFORMATIONSERVICE 
		/OptiFine_1.16.4_HD_U_G6.jar OptiFine TRANSFORMATIONSERVICE 
		/forge-1.16.4-35.1.15.jar fml TRANSFORMATIONSERVICE 
	FML: 35.1
	Forge: net.minecraftforge:35.1.15
	FML Language Providers: 
		javafml@35.1
		minecraft@1
	Mod List: 
		forge-1.16.4-35.1.15-client.jar                   |Minecraft                     |minecraft                     |1.16.4              |DONE      |NOSIGNATURE
		ImmersiveEngineering-1.16.4-4.1.2-129.jar         |Immersive Engineering         |immersiveengineering          |1.16.4-4.1.2-129    |DONE      |44:39:94:cf:1d:8c:be:3c:7f:a9:ee:f4:1e:63:a5:ac:61:f9:c2:87:d5:5b:d9:d6:8c:b5:3e:96:5d:8e:3f:b7
		worldedit-forge-mc1.16.3-7.2.1-dist.jar           |WorldEdit                     |worldedit                     |7.2.1+299386a       |DONE      |NOSIGNATURE
		BiomesOPlenty-1.16.4-13.0.0.426-universal.jar     |Biomes O' Plenty              |biomesoplenty                 |1.16.4-13.0.0.426   |DONE      |NOSIGNATURE
		ImmersiveRailroading-1.16.4-forge-1.8.0.1.jar     |Immersive Railroading         |immersiverailroading          |1.16.4-forge-1.8.0  |DONE      |NOSIGNATURE
		engineersdecor-1.16.4-1.1.7.jar                   |Engineer's Decor              |engineersdecor                |1.1.7               |DONE      |bf:30:76:97:e4:58:41:61:2a:f4:30:d3:8f:4c:e3:71:1d:14:c4:a1:4e:85:36:e3:1d:aa:2f:cb:22:b0:04:9b
		TrackAPI-1.16.4-forge-1.2.1.jar                   |TrackAPI                      |trackapi                      |1.2                 |DONE      |NOSIGNATURE
		ImmersivePetroleum-1.16.4-3.1.0-2.jar             |Immersive Petroleum           |immersivepetroleum            |3.1.0-2             |DONE      |NOSIGNATURE
		forge-1.16.4-35.1.15-universal.jar                |Forge                         |forge                         |35.1.15             |DONE      |22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		cofh_core-1.16.3-1.1.6.jar                        |CoFH Core                     |cofh_core                     |1.1.6               |DONE      |NOSIGNATURE
		thermal_foundation-1.16.3-1.1.6.jar               |Thermal Series                |thermal                       |1.1.6               |DONE      |NOSIGNATURE
		thermal_expansion-1.16.3-1.1.6.jar                |Thermal Expansion             |thermal_expansion             |1.1.6               |DONE      |NOSIGNATURE
		thermal_innovation-1.16.3-1.1.7.jar               |Thermal Innovation            |thermal_innovation            |1.1.7               |DONE      |NOSIGNATURE
		thermal_cultivation-1.16.3-1.1.6.jar              |Thermal Cultivation           |thermal_cultivation           |1.1.6               |DONE      |NOSIGNATURE
		UniversalModCore-1.16.4-forge-1.0.1.jar           |Universal Mod Core            |universalmodcore              |1.0.1               |DONE      |NOSIGNATURE
	Crash Report UUID: ef9642a3-bf2d-4170-8e1b-d3efcd8f92a0
	Launched Version: 1.16.4-forge-35.1.15
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: ~~ERROR~~ IllegalStateException: Rendersystem called from wrong thread
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: mod_resources, vanilla, file/VoxelTrainsV2.zip
	Current Language: English (US)
	CPU: 4x Intel(R) Core(TM) i3-6100U CPU @ 2.30GHz
	OptiFine Version: OptiFine_1.16.4_HD_U_G6
	OptiFine Build: 20210117-001622
	Render Distance Chunks: 11
	Mipmaps: 2
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.5.13469 Compatibility Profile Context 21.19.512.4
	OpenGlRenderer: AMD Radeon (TM) R5 M430
	OpenGlVendor: ATI Technologies Inc.
	CpuCount: 4

**Comment by MinerMan812** [comment]
I got the same thing
I'm playing on a server and once we made the casting basin i've been getting the crash when i leave the chuck and returned.
For some reason I am the only one who gets this crash despite all of us having the exact same mods

**Comment by Larky2k** [comment]
Increase your RAM as you don't meet the minimum for modded MC
if you got 16gb+ in your system around 8gb you be golden

**Comment by MinerMan812** [comment]
Ah that makes sense
But I only have 8gb of ram

**Comment by Larky2k** [comment]
try 4gb or 5gb but no more

**Comment by reydaniels39** [comment]
I have the same problem, and I am also starting the game with 5GB of RAM.

**Comment by biauk** [comment]
I increased RAM to 4 GB and this crash still happened but this time not after placing track but when flying in creative mode.
