### ISSUE TITLE
1.16.5 Error when some models loading on Forge server

### ISSUE THREAD

**Issue by Senyum** [TeamOpenIndustry/ImmersiveRailroading#966]
**Describe the bug**  
When forge server startup some model from mod have errors in server startup logs

**How to reproduce**  
Startup forge server

**Mod List**
ImmersiveRailroading-1.16.4-forge-1.8.0.1
forge-1.16.5-36.1.4
 
**Expected behavior**  
[08:37:48] [modloading-worker-0/ERROR] [ca.mo.ModCore/]: Error loading model rolling_stock/tender/.json of type tender
[08:37:48] [modloading-worker-0/ERROR] [ca.mo.ModCore/CATCHING]: Catching
java.io.FileNotFoundException: immersiverailroading:rolling_stock/tender/.json
        at cam72cam.mod.resource.Data$DataProxy.getResourceStream(Data.java:44) ~[universalmodcore:1.0.1] {re:classloading}
        at cam72cam.mod.resource.Data$DataProxy.getResourceStream(Data.java:50) ~[universalmodcore:1.0.1] {re:classloading}
        at cam72cam.mod.resource.Identifier.getResourceStream(Identifier.java:81) ~[universalmodcore:1.0.1] {re:classloading}
        at cam72cam.immersiverailroading.registry.DefinitionManager.getJsonData(DefinitionManager.java:234) ~[immersiverailroading:1.16.4-forge-1.8.0] {re:classloading}
        at cam72cam.immersiverailroading.registry.DefinitionManager.lambda$initModels$1(DefinitionManager.java:137) ~[immersiverailroading:1.16.4-forge-1.8.0] {re:classloading}
        at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source) [?:1.8.0_281] {}
        at java.util.Spliterators$ArraySpliterator.forEachRemaining(Unknown Source) [?:1.8.0_281] {}
        at java.util.stream.AbstractPipeline.copyInto(Unknown Source) [?:1.8.0_281] {}
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) [?:1.8.0_281] {}
        at java.util.stream.ReduceOps$ReduceTask.doLeaf(Unknown Source) [?:1.8.0_281] {}
        at java.util.stream.ReduceOps$ReduceTask.doLeaf(Unknown Source) [?:1.8.0_281] {}
        at java.util.stream.AbstractTask.compute(Unknown Source) [?:1.8.0_281] {}
        at java.util.concurrent.CountedCompleter.exec(Unknown Source) [?:1.8.0_281] {}
        at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) [?:1.8.0_281] {}
        at java.util.concurrent.ForkJoinPool$WorkQueue.execLocalTasks(Unknown Source) [?:1.8.0_281] {}
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source) [?:1.8.0_281] {}
        at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) [?:1.8.0_281] {}
        at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) [?:1.8.0_281] {}

**Comment by cam72cam** [comment]
That's due to one of the IR resource packs you have loaded, not a base mod issue.  Please report it to them.
