### ISSUE TITLE
Universal Mod Core Crash.

### ISSUE THREAD

**Issue by technoguy505** [TeamOpenIndustry/ImmersiveRailroading#986]
This is my first GitHub post, so go easy on me. I'm trying to run a server (On Aternos {yes, I know. It's horrible. Its just temporary lol}), and I just basically copied my mod pack from my desktop forge server to the aternos, but every time I launch I get this crash report. I've tried both version 1.0.0, and 1.0.1 of UniversalModCore, and neither work. I read about a conflict with quark, and I deleted quark, and still no dice. Any help would be appreciated.
---- Minecraft Crash Report ----
// My bad.

Time: 6/9/21 12:31 PM
Description: Mod loading error has occurred

java.lang.Exception: Mod Loading has failed
	at net.minecraftforge.fml.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:85) ~[forge:?] {re:classloading}
	at net.minecraftforge.fml.server.ServerModLoader.load(ServerModLoader.java:51) ~[forge:?] {re:classloading}
	at net.minecraft.server.Main.main(Main.java:95) ~[?:?] {re:classloading,re:mixin,pl:mixin:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_292] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_292] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_292] {}
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_292] {}
	at net.minecraftforge.fml.loading.FMLServerLaunchProvider.lambda$launchService$0(FMLServerLaunchProvider.java:51) ~[forge.jar:36.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {}
	at net.minecraftforge.server.ServerMain$Runner.runLauncher(ServerMain.java:63) [forge.jar:?] {}
	at net.minecraftforge.server.ServerMain$Runner.access$100(ServerMain.java:60) [forge.jar:?] {}
	at net.minecraftforge.server.ServerMain.main(ServerMain.java:57) [forge.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: main
Stacktrace:
	at java.lang.ClassLoader.findClass(ClassLoader.java:523) ~[?:1.8.0_292] {}
-- MOD universalmodcore --
Details:
	Caused by 0: java.lang.NoClassDefFoundError: trackapi/lib/ITrack
		at cam72cam.immersiverailroading.blocks.BlockRailGag.constructBlockEntity(BlockRailGag.java:13) ~[immersiverailroading:1.16.4-forge-1.8.0] {re:classloading}
		at cam72cam.mod.block.tile.TileEntity.register(TileEntity.java:145) ~[universalmodcore:1.0.1] {re:classloading}
		at cam72cam.mod.block.BlockTypeEntity.<init>(BlockTypeEntity.java:26) ~[universalmodcore:1.0.1] {re:classloading}
		at cam72cam.immersiverailroading.blocks.BlockRailBase.<init>(BlockRailBase.java:10) ~[immersiverailroading:1.16.4-forge-1.8.0] {re:classloading}
		at cam72cam.immersiverailroading.blocks.BlockRailGag.<init>(BlockRailGag.java:8) ~[immersiverailroading:1.16.4-forge-1.8.0] {re:classloading}
		at cam72cam.immersiverailroading.IRBlocks.<clinit>(IRBlocks.java:10) ~[immersiverailroading:1.16.4-forge-1.8.0] {re:classloading}
		at cam72cam.immersiverailroading.thirdparty.Legacy.registerBlocks(Legacy.java:17) ~[immersiverailroading:1.16.4-forge-1.8.0] {re:classloading}
		at cam72cam.immersiverailroading.thirdparty.CompatLoader.common(CompatLoader.java:28) ~[immersiverailroading:1.16.4-forge-1.8.0] {re:classloading}
		at cam72cam.immersiverailroading.ImmersiveRailroading.commonEvent(ImmersiveRailroading.java:66) ~[immersiverailroading:1.16.4-forge-1.8.0] {re:classloading}
		at cam72cam.mod.ModCore$Proxy.event(ModCore.java:164) ~[universalmodcore:1.0.1] {re:classloading}
		at cam72cam.mod.ModCore$ServerProxy.event(ModCore.java:177) ~[universalmodcore:1.0.1] {re:classloading}
		at cam72cam.mod.ModCore$Proxy.lambda$event$0(ModCore.java:161) ~[universalmodcore:1.0.1] {re:classloading}
		at java.util.ArrayList.forEach(ArrayList.java:1259) ~[?:1.8.0_292] {}
		at cam72cam.mod.ModCore$Proxy.event(ModCore.java:161) ~[universalmodcore:1.0.1] {re:classloading}
		at cam72cam.mod.ModCore.<init>(ModCore.java:74) ~[universalmodcore:1.0.1] {re:classloading}
		at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_292] {}
		at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_292] {}
		at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_292] {}
		at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_292] {}
		at java.lang.Class.newInstance(Class.java:442) ~[?:1.8.0_292] {}
		at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:81) ~[forge:36.1] {re:classloading}
		at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:120) ~[forge:?] {re:classloading}
		at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1640) ~[?:1.8.0_292] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1632) ~[?:1.8.0_292] {}
		at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_292] {}
		at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_292] {}
		at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) ~[?:1.8.0_292] {re:computing_frames}
		at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175) ~[?:1.8.0_292] {}

	Mod File: UniversalModCore-1.16.4-forge-1.0.1.jar
	Failure message: Universal Mod Core (universalmodcore) has failed to load correctly
		java.lang.NoClassDefFoundError: trackapi/lib/ITrack
	Mod Version: 1.0.1
	Mod Issue URL: https://github.com/TeamOpenIndustry/UniversalModCore/issues
	Exception message: java.lang.ClassNotFoundException: trackapi.lib.ITrack
Stacktrace:
	at java.lang.ClassLoader.findClass(ClassLoader.java:523) ~[?:1.8.0_292] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_292] {}
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:106) ~[modlauncher-8.0.9.jar:?] {re:classloading}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_292] {}
	at cam72cam.immersiverailroading.blocks.BlockRailGag.constructBlockEntity(BlockRailGag.java:13) ~[immersiverailroading:1.16.4-forge-1.8.0] {re:classloading}
	at cam72cam.mod.block.tile.TileEntity.register(TileEntity.java:145) ~[universalmodcore:1.0.1] {re:classloading}
	at cam72cam.mod.block.BlockTypeEntity.<init>(BlockTypeEntity.java:26) ~[universalmodcore:1.0.1] {re:classloading}
	at cam72cam.immersiverailroading.blocks.BlockRailBase.<init>(BlockRailBase.java:10) ~[immersiverailroading:1.16.4-forge-1.8.0] {re:classloading}
	at cam72cam.immersiverailroading.blocks.BlockRailGag.<init>(BlockRailGag.java:8) ~[immersiverailroading:1.16.4-forge-1.8.0] {re:classloading}
	at cam72cam.immersiverailroading.IRBlocks.<clinit>(IRBlocks.java:10) ~[immersiverailroading:1.16.4-forge-1.8.0] {re:classloading}
	at cam72cam.immersiverailroading.thirdparty.Legacy.registerBlocks(Legacy.java:17) ~[immersiverailroading:1.16.4-forge-1.8.0] {re:classloading}
	at cam72cam.immersiverailroading.thirdparty.CompatLoader.common(CompatLoader.java:28) ~[immersiverailroading:1.16.4-forge-1.8.0] {re:classloading}
	at cam72cam.immersiverailroading.ImmersiveRailroading.commonEvent(ImmersiveRailroading.java:66) ~[immersiverailroading:1.16.4-forge-1.8.0] {re:classloading}
	at cam72cam.mod.ModCore$Proxy.event(ModCore.java:164) ~[universalmodcore:1.0.1] {re:classloading}
	at cam72cam.mod.ModCore$ServerProxy.event(ModCore.java:177) ~[universalmodcore:1.0.1] {re:classloading}
	at cam72cam.mod.ModCore$Proxy.lambda$event$0(ModCore.java:161) ~[universalmodcore:1.0.1] {re:classloading}
	at java.util.ArrayList.forEach(ArrayList.java:1259) ~[?:1.8.0_292] {}
	at cam72cam.mod.ModCore$Proxy.event(ModCore.java:161) ~[universalmodcore:1.0.1] {re:classloading}
	at cam72cam.mod.ModCore.<init>(ModCore.java:74) ~[universalmodcore:1.0.1] {re:classloading}
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_292] {}
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_292] {}
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_292] {}
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_292] {}
	at java.lang.Class.newInstance(Class.java:442) ~[?:1.8.0_292] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:81) ~[forge:36.1] {re:classloading}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:120) ~[forge:?] {re:classloading}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1640) ~[?:1.8.0_292] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1632) ~[?:1.8.0_292] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_292] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_292] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) ~[?:1.8.0_292] {re:computing_frames}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175) ~[?:1.8.0_292] {}

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Linux (amd64) version 5.4.0-72-generic
	Java Version: 1.8.0_292, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1639202016 bytes (1563 MB) / 2052063232 bytes (1957 MB) up to 2143813632 bytes (2044 MB)
	CPUs: 3
	JVM Flags: 3 total; -XX:MaxMetaspaceSize=200M -Xmx2300M -Xms1150M
	ModLauncher: 8.0.9+86+master.3cf110c
	ModLauncher launch target: fmlserver
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.2.jar mixin PLUGINSERVICE 
		/eventbus-4.0.0.jar eventbus PLUGINSERVICE 
		/forge.jar object_holder_definalize PLUGINSERVICE 
		/forge.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE 
		/forge.jar capability_inject_definalize PLUGINSERVICE 
		/forge.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.2.jar mixin TRANSFORMATIONSERVICE 
		/forge.jar fml TRANSFORMATIONSERVICE 
	FML: 36.1
	Forge: net.minecraftforge:36.1.0
	FML Language Providers: 
		javafml@36.1
		minecraft@1
	Mod List: 
		forge-1.16.5-36.1.0-server.jar                    |Minecraft                     |minecraft                     |1.16.5              |CREATE_REG|NOSIGNATURE
		TConstruct-1.16.5-3.0.3.152.jar                   |Tinkers' Construct            |tconstruct                    |3.0.3.152           |CREATE_REG|NOSIGNATURE
		ExtraArmor-1.12.1-1.16.5.jar                      |Extra Armor Mod               |extraarmor                    |1.16.5-1.12.1       |CREATE_REG|NOSIGNATURE
		DungeonsMod-1.16.3-1.3.20.jar                     |Dungeons Mod                  |dungeonsmod                   |1.16.3-1.3.20       |CREATE_REG|NOSIGNATURE
		theoneprobe-1.16-3.1.4.jar                        |The One Probe                 |theoneprobe                   |1.16-3.1.4          |CREATE_REG|NOSIGNATURE
		SimplyJetpacks2-1.16.5-2.6.7.1.jar                |Simply Jetpacks 2             |simplyjetpacks                |1.16.5-2.6.7.1      |CREATE_REG|NOSIGNATURE
		oneplayersleeping-1.16.4-0.0.5.jar                |One Player Sleeping           |oneplayersleeping             |0.0.5               |CREATE_REG|NOSIGNATURE
		ImmersiveEngineering-1.16.5-4.2.4-134.jar         |Immersive Engineering         |immersiveengineering          |1.16.5-4.2.4-134    |CREATE_REG|44:39:94:cf:1d:8c:be:3c:7f:a9:ee:f4:1e:63:a5:ac:61:f9:c2:87:d5:5b:d9:d6:8c:b5:3e:96:5d:8e:3f:b7
		Hats-1.16.5-10.3.0.jar                            |Hats                          |hats                          |10.3.0              |CREATE_REG|NOSIGNATURE
		cgm-1.0.1-1.16.3.jar                              |MrCrayfish's Gun Mod          |cgm                           |1.0.1               |CREATE_REG|NOSIGNATURE
		BiomesOPlenty-1.16.5-13.1.0.465-universal.jar     |Biomes O' Plenty              |biomesoplenty                 |1.16.5-13.1.0.463   |CREATE_REG|NOSIGNATURE
		jei-1.16.5-7.7.0.99.jar                           |Just Enough Items             |jei                           |7.7.0.99            |CREATE_REG|NOSIGNATURE
		smoothboot-forge-1.16.4-1.2.2.jar                 |Smooth Boot                   |smoothboot                    |1.16.4-1.2.2        |CREATE_REG|NOSIGNATURE
		Mekanism-1.16.5-10.0.21.448.jar                   |Mekanism                      |mekanism                      |10.0.21             |CREATE_REG|NOSIGNATURE
		Patchouli-1.16.4-51.jar                           |Patchouli                     |patchouli                     |1.16.4-51           |CREATE_REG|NOSIGNATURE
		overworld_two-1.0-Forge-1.16.4.jar                |Overworld 2                   |overworld_two                 |1.0                 |CREATE_REG|NOSIGNATURE
		Mantle-1.16.5-1.6.97.jar                          |Mantle                        |mantle                        |1.6.97              |CREATE_REG|NOSIGNATURE
		create-mc1.16.5_v0.3.1c.jar                       |Create                        |create                        |mc1.16.5_v0.3.1c+151|CREATE_REG|NOSIGNATURE
		gravestone-1.16.5-1.0.4.jar                       |Gravestone Mod                |gravestone                    |1.16.5-1.0.4        |CREATE_REG|NOSIGNATURE
		journeymap-1.16.5-5.7.1.jar                       |Journeymap                    |journeymap                    |5.7.1               |CREATE_REG|NOSIGNATURE
		AutoRegLib-1.6-49.jar                             |AutoRegLib                    |autoreglib                    |1.6-49              |CREATE_REG|NOSIGNATURE
		appliedenergistics2-8.3.1.jar                     |Applied Energistics 2         |appliedenergistics2           |8.3.1               |CREATE_REG|95:58:cc:83:9d:a8:fa:4f:e9:f3:54:90:66:61:c8:ae:9c:08:88:11:52:52:df:2d:28:5f:05:d8:28:57:0f:98
		adaptive_performance_tweaks_1.16.5-1.0.5.jar      |Adaptive Performance Tweaks   |adaptive_performance_tweaks   |1.0.5               |CREATE_REG|NOSIGNATURE
		OreExcavation-1.8.157.jar                         |Ore Excavation                |oreexcavation                 |1.8.157             |CREATE_REG|e7:68:1c:0d:b9:7e:cf:f8:f3:40:9c:84:c5:39:d7:a4:59:78:b0:6b:c3:fd:b7:4f:69:18:a3:88:e3:76:8c:3f
		quickteleports-1.16.2-1.1.2.jar                   |QuickTeleports                |quickteleports                |1.1.2               |CREATE_REG|NOSIGNATURE
		obfuscate-0.6.1-1.16.3.jar                        |Obfuscate                     |obfuscate                     |0.6.1               |CREATE_REG|e1:59:1a:56:ec:97:b3:d0:b3:4b:25:06:1f:83:b0:f4:fd:0c:24:e3:6d:ea:94:b1:9f:22:b0:38:13:60:88:ea
		vehicle-mod-0.45.2-1.16.3.jar                     |MrCrayfish's Vehicle Mod      |vehicle                       |0.45.2              |CREATE_REG|NOSIGNATURE
		cfm-7.0.0pre21-1.16.3.jar                         |MrCrayfish's Furniture Mod    |cfm                           |7.0.0-pre21         |CREATE_REG|NOSIGNATURE
		ImmersiveRailroading-1.16.4-forge-1.8.0.1.jar     |Immersive Railroading         |immersiverailroading          |1.16.4-forge-1.8.0  |CREATE_REG|NOSIGNATURE
		ferritecore-2.0.4-forge.jar                       |Ferrite Core                  |ferritecore                   |2.0.4               |CREATE_REG|41:ce:50:66:d1:a0:05:ce:a1:0e:02:85:9b:46:64:e0:bf:2e:cf:60:30:9a:fe:0c:27:e0:63:66:9a:84:ce:8a
		MekanismGenerators-1.16.5-10.0.21.448.jar         |Mekanism: Generators          |mekanismgenerators            |10.0.21             |CREATE_REG|NOSIGNATURE
		iChunUtil-1.16.5-10.4.0.jar                       |iChunUtil                     |ichunutil                     |10.4.0              |CREATE_REG|NOSIGNATURE
		fastbenchminusreplacement-1.4.jar                 |FastWorkbench Minus Replacemen|fastbenchminusreplacement     |1.4                 |CREATE_REG|NOSIGNATURE
		KimetsunoYaiba_1.16.5_ver26.jar                   |Kimetsunoyaiba                |kimetsunoyaiba                |1.0.0               |CREATE_REG|NOSIGNATURE
		forge-1.16.5-36.1.0-universal.jar                 |Forge                         |forge                         |36.1.0              |CREATE_REG|22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		Quark-r2.4-311.jar                                |Quark                         |quark                         |r2.4-311            |CREATE_REG|NOSIGNATURE
		twilightforest-1.16.5-4.0.482-universal.jar       |The Twilight Forest           |twilightforest                |NONE                |CREATE_REG|NOSIGNATURE
		DynamicTrees-1.16.5-0.10.0-Beta12.jar             |Dynamic Trees                 |dynamictrees                  |1.16.5-0.10.0-Beta12|CREATE_REG|NOSIGNATURE
		quickhomes-1.16.3-1.2.6.jar                       |QuickHomes                    |quickhomes                    |1.2.6               |CREATE_REG|NOSIGNATURE
		ironchest-1.16.4-11.2.10.jar                      |Iron Chests                   |ironchest                     |1.16.4-11.2.10      |CREATE_REG|NOSIGNATURE
		UniversalModCore-1.16.4-forge-1.0.1.jar           |Universal Mod Core            |universalmodcore              |1.0.1               |ERROR     |NOSIGNATURE
	Crash Report UUID: 3c111d27-c21d-4ece-bd24-da502751c3f9

**Comment by cam72cam** [comment]
You are missing the TrackAPI mod
