### ISSUE TITLE
Crash a textures Universal Core Mod

### ISSUE THREAD

**Issue by Foxriks** [TeamOpenIndustry/ImmersiveRailroading#988]
Logs:
---- Minecraft Crash Report ----

WARNING: coremods are present:
  TLSkinCapeHookLoader (tlskincape_1.12.2-1.4.jar)
Contact their authors BEFORE contacting forge

// Everything's going to plan. No, really, that was supposed to happen.

Time: 6/13/21 7:24 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from UniversalModCore (universalmodcore)
Caused by: java.lang.IllegalStateException: Function is not supported
	at org.lwjgl.BufferChecks.checkFunctionAddress(BufferChecks.java:58)
	at org.lwjgl.opengl.GL15.glGenBuffers(GL15.java:116)
	at cam72cam.mod.render.VBA.drawVBO(VBA.java:81)
	at cam72cam.mod.render.VBA.draw(VBA.java:64)
	at cam72cam.mod.render.obj.OBJRender.draw(OBJRender.java:67)
	at cam72cam.immersiverailroading.render.item.StockItemModel.lambda$getSpriteModel$2(StockItemModel.java:82)
	at cam72cam.immersiverailroading.render.item.StockItemModel$$Lambda$360/1186385521.run(Unknown Source)
	at cam72cam.mod.render.StandardModel.lambda$addCustom$1(StandardModel.java:84)
	at cam72cam.mod.render.StandardModel$$Lambda$361/640511728.accept(Unknown Source)
	at cam72cam.mod.render.StandardModel.lambda$renderCustom$3(StandardModel.java:145)
	at cam72cam.mod.render.StandardModel$$Lambda$363/567826158.accept(Unknown Source)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at cam72cam.mod.render.StandardModel.renderCustom(StandardModel.java:145)
	at cam72cam.mod.render.StandardModel.renderCustom(StandardModel.java:140)
	at cam72cam.mod.render.ItemRender.createSprite(ItemRender.java:178)
	at cam72cam.mod.render.ItemRender.lambda$register$5(ItemRender.java:80)
	at cam72cam.mod.render.ItemRender$$Lambda$176/893350828.run(Unknown Source)
	at cam72cam.mod.event.ClientEvents$$Lambda$354/1113063982.accept(Unknown Source)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at cam72cam.mod.event.Event.execute(Event.java:24)
	at cam72cam.mod.event.ClientEvents.fireReload(ClientEvents.java:38)
	at cam72cam.mod.ModCore$Internal.clientEvent(ModCore.java:197)
	at cam72cam.mod.ModCore$ClientProxy.event(ModCore.java:139)
	at cam72cam.mod.ModCore$Proxy.lambda$event$0(ModCore.java:129)
	at cam72cam.mod.ModCore$Proxy$$Lambda$194/1533086864.accept(Unknown Source)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1080)
	at cam72cam.mod.ModCore$Proxy.event(ModCore.java:129)
	at cam72cam.mod.ModCore.init(ModCore.java:69)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:749)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:535)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 414772952 bytes (395 MB) / 922009600 bytes (879 MB) up to 3197370368 bytes (3049 MB)
	JVM Flags: 3 total; -Xmn128M -Xmx3062M -XX:+UseConcMarkSweepGC
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2855 8 mods loaded, 8 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                         | Version      | Source                                             | Signature                                |
	|:----- |:-------------------------- |:------------ |:-------------------------------------------------- |:---------------------------------------- |
	| LCHI  | minecraft                  | 1.12.2       | minecraft.jar                                      | None                                     |
	| LCHI  | mcp                        | 9.42         | minecraft.jar                                      | None                                     |
	| LCHI  | FML                        | 8.0.99.99    | forge-1.12.2-14.23.5.2855.jar                      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHI  | forge                      | 14.23.5.2855 | forge-1.12.2-14.23.5.2855.jar                      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHI  | trackapi                   | 1.2          | TrackAPI-1.12.2-1.2.jar                            | None                                     |
	| LCHE  | universalmodcore           | 1.0.0        | UniversalModCore-1.12.2-forge-1.0.0.jar            | None                                     |
	| LCH   | immersiverailroading       | 1.8.0-7e0f82 | ImmersiveRailroading-1.12.2-forge-1.8.0-7e0f82.jar | None                                     |
	| LCH   | tlauncher_custom_cape_skin | 1.4          | tlskincape_1.12.2-1.4.jar                          | None                                     |

	Loaded coremods (and transformers): 
TLSkinCapeHookLoader (tlskincape_1.12.2-1.4.jar)
  gloomyfolken.hooklib.minecraft.PrimaryClassTransformer
	GL info: ' Vendor: 'Intel' Version: '1.4.0 - Build 8.14.10.1930' Renderer: 'Intel Bear Lake B'

**Comment by km00700** [comment]
Do you have a different Graphics card to use? The graphics you're running are built into your processor which is an older one, so it doesn't seem to be able to handle some of the OpenGL functions used by IR and UMC.

**Comment by Foxriks** [comment]
yes, I have a new Graphics card Thank You
