### ISSUE TITLE
Paintbrush model causing crash in 1.16.5, forge 3.6.1.0

### ISSUE THREAD

**Issue by kodaxmax** [TeamOpenIndustry/ImmersiveRailroading#989]
Searched for "paint" in creative menu, game then crashed,

"Details:
	Item Type: item_paint_brush
	Registry Name: immersiverailroading:item_paint_brush
	Item Damage: 0
	Item NBT: null
	Item Foil: false"

`---- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 6/15/21 11:31 PM
Description: Rendering item

java.lang.RuntimeException: Error loading item model...
	at cam72cam.immersiverailroading.render.item.ObjItemRender.lambda$null$0(ObjItemRender.java:28) ~[?:1.16.4-forge-1.8.0] {re:classloading}
	at cam72cam.immersiverailroading.render.item.ObjItemRender$$Lambda$14857/1978170988.run(Unknown Source) ~[?:?] {}
	at cam72cam.mod.render.StandardModel.lambda$addCustom$3(StandardModel.java:99) ~[?:1.0.1] {re:classloading}
	at cam72cam.mod.render.StandardModel$$Lambda$12501/355635406.accept(Unknown Source) ~[?:?] {}
	at cam72cam.mod.render.StandardModel.lambda$renderCustom$5(StandardModel.java:165) ~[?:1.0.1] {re:classloading}
	at cam72cam.mod.render.StandardModel$$Lambda$14858/1829425777.accept(Unknown Source) ~[?:?] {}
	at java.util.ArrayList.forEach(ArrayList.java:1249) ~[?:1.8.0_51] {re:computing_frames}
	at cam72cam.mod.render.StandardModel.renderCustom(StandardModel.java:165) ~[?:1.0.1] {re:classloading}
	at cam72cam.mod.render.StandardModel.render(StandardModel.java:126) ~[?:1.0.1] {re:classloading}
	at cam72cam.mod.render.StandardModel.render(StandardModel.java:121) ~[?:1.0.1] {re:classloading}
	at cam72cam.mod.render.ItemRender$BakedItemModel.lambda$handlePerspective$0(ItemRender.java:354) ~[?:1.0.1] {re:classloading}
	at cam72cam.mod.render.ItemRender$BakedItemModel$$Lambda$14855/1031166685.run(Unknown Source) ~[?:?] {}
	at cam72cam.mod.render.ItemRender$2.func_239207_a_(ItemRender.java:263) ~[?:1.0.1] {re:classloading}
	at net.minecraft.client.renderer.ItemRenderer.func_229111_a_(ItemRenderer.java:239) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,pl:mixin:APP:quark.mixins.json:client.ItemRendererMixin,pl:mixin:A}
	at net.minecraft.client.renderer.ItemRenderer.func_191962_a(ItemRenderer.java:419) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,pl:mixin:APP:quark.mixins.json:client.ItemRendererMixin,pl:mixin:A}
	at net.minecraft.client.renderer.ItemRenderer.func_239387_b_(ItemRenderer.java:459) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,pl:mixin:APP:quark.mixins.json:client.ItemRendererMixin,pl:mixin:A}
	at net.minecraft.client.renderer.ItemRenderer.func_184391_a(ItemRenderer.java:448) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,pl:mixin:APP:quark.mixins.json:client.ItemRendererMixin,pl:mixin:A}
	at net.minecraft.client.gui.screen.inventory.ContainerScreen.func_238746_a_(ContainerScreen.java:237) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:quark.mixins.json:client.ContainerScreenMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screen.inventory.ContainerScreen.func_230430_a_(ContainerScreen.java:106) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:quark.mixins.json:client.ContainerScreenMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.DisplayEffectsScreen.func_230430_a_(DisplayEffectsScreen.java:48) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screen.inventory.CreativeScreen.func_230430_a_(CreativeScreen.java:608) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:297) ~[?:?] {re:classloading}
	at sun.reflect.GeneratedMethodAccessor61.invoke(Unknown Source) ~[?:?] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.optifine.reflect.Reflector.callVoid(Reflector.java:789) ~[?:?] {re:classloading}
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:821) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:976) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:APP:assets/botania/botania.mixins.json:AccessorMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:APP:assets/botania/botania.mixins.json:AccessorMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.5-36.1.0.jar:36.1] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$478/646757254.call(Unknown Source) [forge-1.16.5-36.1.0.jar:36.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {}
Caused by: java.lang.NumberFormatException: empty String
	at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:1842) ~[?:1.8.0_51] {}
	at sun.misc.FloatingDecimal.parseFloat(FloatingDecimal.java:122) ~[?:1.8.0_51] {}
	at java.lang.Float.parseFloat(Float.java:451) ~[?:1.8.0_51] {}
	at cam72cam.mod.render.obj.OBJTextureSheet.<init>(OBJTextureSheet.java:169) ~[?:1.0.1] {re:classloading}
	at cam72cam.mod.render.obj.OBJRender.<init>(OBJRender.java:36) ~[?:1.0.1] {re:classloading}
	at cam72cam.mod.render.obj.OBJRender.<init>(OBJRender.java:27) ~[?:1.0.1] {re:classloading}
	at cam72cam.mod.render.obj.OBJRender.<init>(OBJRender.java:23) ~[?:1.0.1] {re:classloading}
	at cam72cam.immersiverailroading.render.item.ObjItemRender.lambda$null$0(ObjItemRender.java:26) ~[?:1.16.4-forge-1.8.0] {re:classloading}
	... 40 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at cam72cam.immersiverailroading.render.item.ObjItemRender.lambda$null$0(ObjItemRender.java:28) ~[?:1.16.4-forge-1.8.0] {re:classloading}
	at cam72cam.immersiverailroading.render.item.ObjItemRender$$Lambda$14857/1978170988.run(Unknown Source) ~[?:?] {}
	at cam72cam.mod.render.StandardModel.lambda$addCustom$3(StandardModel.java:99) ~[?:1.0.1] {re:classloading}
	at cam72cam.mod.render.StandardModel$$Lambda$12501/355635406.accept(Unknown Source) ~[?:?] {}
	at cam72cam.mod.render.StandardModel.lambda$renderCustom$5(StandardModel.java:165) ~[?:1.0.1] {re:classloading}
	at cam72cam.mod.render.StandardModel$$Lambda$14858/1829425777.accept(Unknown Source) ~[?:?] {}
	at java.util.ArrayList.forEach(ArrayList.java:1249) ~[?:1.8.0_51] {re:computing_frames}
	at cam72cam.mod.render.StandardModel.renderCustom(StandardModel.java:165) ~[?:1.0.1] {re:classloading}
	at cam72cam.mod.render.StandardModel.render(StandardModel.java:126) ~[?:1.0.1] {re:classloading}
	at cam72cam.mod.render.StandardModel.render(StandardModel.java:121) ~[?:1.0.1] {re:classloading}
	at cam72cam.mod.render.ItemRender$BakedItemModel.lambda$handlePerspective$0(ItemRender.java:354) ~[?:1.0.1] {re:classloading}
	at cam72cam.mod.render.ItemRender$BakedItemModel$$Lambda$14855/1031166685.run(Unknown Source) ~[?:?] {}
	at cam72cam.mod.render.ItemRender$2.func_239207_a_(ItemRender.java:263) ~[?:1.0.1] {re:classloading}
	at net.minecraft.client.renderer.ItemRenderer.func_229111_a_(ItemRenderer.java:239) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,pl:mixin:APP:quark.mixins.json:client.ItemRendererMixin,pl:mixin:A}
	at net.minecraft.client.renderer.ItemRenderer.func_191962_a(ItemRenderer.java:419) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,pl:mixin:APP:quark.mixins.json:client.ItemRendererMixin,pl:mixin:A}
-- Item being rendered --
Details:
	Item Type: item_paint_brush
	Registry Name: immersiverailroading:item_paint_brush
	Item Damage: 0
	Item NBT: null
	Item Foil: false
Stacktrace:
	at net.minecraft.client.renderer.ItemRenderer.func_239387_b_(ItemRenderer.java:459) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,pl:mixin:APP:quark.mixins.json:client.ItemRendererMixin,pl:mixin:A}
	at net.minecraft.client.renderer.ItemRenderer.func_184391_a(ItemRenderer.java:448) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,pl:mixin:APP:quark.mixins.json:client.ItemRendererMixin,pl:mixin:A}
	at net.minecraft.client.gui.screen.inventory.ContainerScreen.func_238746_a_(ContainerScreen.java:237) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:quark.mixins.json:client.ContainerScreenMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screen.inventory.ContainerScreen.func_230430_a_(ContainerScreen.java:106) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:quark.mixins.json:client.ContainerScreenMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.DisplayEffectsScreen.func_230430_a_(DisplayEffectsScreen.java:48) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screen.inventory.CreativeScreen.func_230430_a_(CreativeScreen.java:608) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:297) ~[?:?] {re:classloading}
	at sun.reflect.GeneratedMethodAccessor61.invoke(Unknown Source) ~[?:?] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.optifine.reflect.Reflector.callVoid(Reflector.java:789) ~[?:?] {re:classloading}

-- Screen render details --
Details:
	Screen name: net.minecraft.client.gui.screen.inventory.CreativeScreen
	Mouse location: Scaled: (264, 55). Absolute: (2378.000000, 495.000000)
	Screen size: Scaled: (427, 240). Absolute: (3840, 2160). Scale factor of 9.000000

-- Affected level --
Details:
	All players: 1 total; [ClientPlayerEntity['kodaxmax'/207, l='ClientLevel', x=106.36, y=92.00, z=-23.62]]
	Chunk stats: Client Chunk Cache: 5041, 4289
	Level dimension: minecraft:overworld
	Level spawn location: World: (-208,75,272), Chunk: (at 0,4,0 in -13,17; contains blocks -208,0,272 to -193,255,287), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 3697717 game time, 3971180 day time
	Server brand: forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.world.ClientWorld.func_72914_a(ClientWorld.java:617) ~[?:?] {re:mixin,re:classloading,xf:OptiFine:default,pl:mixin:APP:architectury.mixins.json:MixinClientLevel,pl:mixin:A}
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2029) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:APP:assets/botania/botania.mixins.json:AccessorMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:623) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:APP:assets/botania/botania.mixins.json:AccessorMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.5-36.1.0.jar:36.1] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$478/646757254.call(Unknown Source) [forge-1.16.5-36.1.0.jar:36.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {}

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 843301920 bytes (804 MB) / 4368367616 bytes (4166 MB) up to 11453595648 bytes (10923 MB)
	CPUs: 12
	JVM Flags: 5 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx12288m -Xms256m -XX:PermSize=256m
	ModLauncher: 8.0.9+86+master.3cf110c
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.2.jar mixin PLUGINSERVICE 
		/eventbus-4.0.0.jar eventbus PLUGINSERVICE 
		/forge-1.16.5-36.1.0.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.5-36.1.0.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.5-36.1.0.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.5-36.1.0.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.2.jar mixin TRANSFORMATIONSERVICE 
		/OptiFine_1.16.5_HD_U_G8.jar OptiFine TRANSFORMATIONSERVICE 
		/forge-1.16.5-36.1.0.jar fml TRANSFORMATIONSERVICE 
	FML: 36.1
	Forge: net.minecraftforge:36.1.0
	FML Language Providers: 
		javafml@36.1
		minecraft@1
	Mod List: 
		mowziesmobs-1.5.18.jar                            |Mowzie's Mobs                 |mowziesmobs                   |1.5.18              |DONE      |NOSIGNATURE
		biggerreactors-1.16.4-0.4.3.jar                   |Bigger Reactors               |biggerreactors                |0.4.3               |DONE      |NOSIGNATURE
		advancedperipherals-0.6r.jar                      |Advanced Peripherals          |advancedperipherals           |0.6r                |DONE      |NOSIGNATURE
		Hats-1.16.5-10.3.1.jar                            |Hats                          |hats                          |10.3.1              |DONE      |NOSIGNATURE
		xlpackets-1.1.jar                                 |XL Packets                    |xlpackets                     |1.1                 |DONE      |NOSIGNATURE
		jei-1.16.5-7.7.0.106.jar                          |Just Enough Items             |jei                           |7.7.0.106           |DONE      |NOSIGNATURE
		DoggyTalents-1.16.5-2.0.1.8.jar                   |Doggy Talents 2               |doggytalents                  |2.0.1.8             |DONE      |NOSIGNATURE
		ae2extras-1.3-1.16.5.jar                          |AE2 Extras                    |ae2extras                     |1.3-1.16.5          |DONE      |NOSIGNATURE
		modnametooltip_1.16.2-1.15.0.jar                  |Mod Name Tooltip              |modnametooltip                |1.15.0              |DONE      |NOSIGNATURE
		invtweaks-1.16.4-1.0.1.jar                        |Inventory Tweaks Renewed      |invtweaks                     |1.16.4-1.0.1        |DONE      |NOSIGNATURE
		BetterCaves-Forge-1.16.4-1.1.2.jar                |YUNG's Better Caves           |bettercaves                   |1.16.4-1.1.2        |DONE      |NOSIGNATURE
		journeymap-1.16.5-5.7.1.jar                       |Journeymap                    |journeymap                    |5.7.1               |DONE      |NOSIGNATURE
		appliedenergistics2-8.3.1.jar                     |Applied Energistics 2         |appliedenergistics2           |8.3.1               |DONE      |95:58:cc:83:9d:a8:fa:4f:e9:f3:54:90:66:61:c8:ae:9c:08:88:11:52:52:df:2d:28:5f:05:d8:28:57:0f:98
		SereneSeasons-1.16.5-4.0.1.91-universal.jar       |Serene Seasons                |sereneseasons                 |1.16.5-4.0.1.91     |DONE      |NOSIGNATURE
		YungsApi-1.16.4-Forge-6.jar                       |YUNG's API                    |yungsapi                      |1.16.4-Forge-6      |DONE      |NOSIGNATURE
		stoneholm-1.2.2.jar                               |Stoneholm                     |stoneholm                     |1.2                 |DONE      |NOSIGNATURE
		phosphophyllite-1.16.4-0.4.5.jar                  |Phosphophyllite               |phosphophyllite               |0.4.5               |DONE      |NOSIGNATURE
		Bookshelf-1.16.5-10.1.11.jar                      |Bookshelf                     |bookshelf                     |10.1.11             |DONE      |eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		buildinggadgets-1.16.5-3.8.0.jar                  |Building Gadgets              |buildinggadgets               |3.8.0               |DONE      |NOSIGNATURE
		Hwyla-forge-1.10.11-B78_1.16.2.jar                |Waila                         |waila                         |1.10.11-B78_1.16.2  |DONE      |NOSIGNATURE
		WAWLA-1.16.5-8.0.1.jar                            |WAWLA                         |wawla                         |8.0.1               |DONE      |eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		voyage-1.16.4-1.0.3.jar                           |Voyage                        |voyage                        |1.0.3               |DONE      |NOSIGNATURE
		iChunUtil-1.16.5-10.4.1.jar                       |iChunUtil                     |ichunutil                     |10.4.1              |DONE      |NOSIGNATURE
		traverse-1.16.4-0.4.3.8.jar                       |Traverse: Reforged            |traverse                      |1.16.4-0.4.3.8      |DONE      |NOSIGNATURE
		JustEnoughResources-1.16.5-0.12.1.121.jar         |Just Enough Resources         |jeresources                   |0.12.1.121          |DONE      |NOSIGNATURE
		forge-1.16.5-36.1.0-universal.jar                 |Forge                         |forge                         |36.1.0              |DONE      |22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		BloodMagic-1.16.4-3.1.0-15.jar                    |Blood Magic                   |bloodmagic                    |1.16.4-3.1.0-15     |DONE      |NOSIGNATURE
		ae2ao-5.0.1-1.16.5.jar                            |AE2AO                         |ae2ao                         |5.0.1-1.16.5        |DONE      |NOSIGNATURE
		corpse-1.16.5-1.0.5.jar                           |Corpse                        |corpse                        |1.16.5-1.0.5        |DONE      |NOSIGNATURE
		forge-1.16.5-36.1.0-client.jar                    |Minecraft                     |minecraft                     |1.16.5              |DONE      |NOSIGNATURE
		MouseTweaks-2.14-mc1.16.2.jar                     |Mouse Tweaks                  |mousetweaks                   |2.14                |DONE      |NOSIGNATURE
		Psi 1.16-94.jar                                   |Psi                           |psi                           |1.16-94             |DONE      |NOSIGNATURE
		mana-and-artifice-1.3.0.6.jar                     |Mana and Artifice             |mana-and-artifice             |1.3.0.6             |DONE      |NOSIGNATURE
		ImmersiveEngineering-1.16.5-5.0.0-135.jar         |Immersive Engineering         |immersiveengineering          |1.16.5-5.0.0-135    |DONE      |44:39:94:cf:1d:8c:be:3c:7f:a9:ee:f4:1e:63:a5:ac:61:f9:c2:87:d5:5b:d9:d6:8c:b5:3e:96:5d:8e:3f:b7
		SaveYourPets-1.16.2-1.0.0.5.jar                   |Save Your Pets                |syp                           |1.0.0.5             |DONE      |NOSIGNATURE
		Numina-1.16.4-2.0.10.jar                          |Numina                        |numina                        |2.0.10              |DONE      |NOSIGNATURE
		ModularPowersuits-1.16.4-2.0.4.jar                |MachineMuse's Modular Powersui|powersuits                    |1.0.0               |DONE      |NOSIGNATURE
		GeneticAnimals-0_6_29.jar                         |Genetic Animals               |eanimod                       |0_6_29              |DONE      |NOSIGNATURE
		Botania-1.16.5-416.jar                            |Botania                       |botania                       |1.16.5-416          |DONE      |NOSIGNATURE
		villagespawnpoint_1.16.5-1.5.jar                  |Village Spawn Point           |villagespawnpoint             |1.5                 |DONE      |NOSIGNATURE
		TrackAPI-1.16.4-forge-1.2.1.jar                   |TrackAPI                      |trackapi                      |1.2                 |DONE      |NOSIGNATURE
		lycanitesmobs-1.16.5-2.3.1.1.jar                  |Lycanites Mobs                |lycanitesmobs                 |1.16.5-2.3.1.1      |DONE      |NOSIGNATURE
		jeiintegration_1.16.5-7.0.1.15.jar                |JEI Integration               |jeiintegration                |7.0.1.15            |DONE      |NOSIGNATURE
		curios-forge-1.16.5-4.0.5.2.jar                   |Curios API                    |curios                        |1.16.5-4.0.5.2      |DONE      |NOSIGNATURE
		Patchouli-1.16.4-51.jar                           |Patchouli                     |patchouli                     |1.16.4-51           |DONE      |NOSIGNATURE
		ftb-backups-2.1.1.6.jar                           |FTB Backups                   |ftbbackups                    |2.1.1.6             |DONE      |NOSIGNATURE
		collective-1.16.5-2.26.jar                        |Collective                    |collective                    |2.26                |DONE      |NOSIGNATURE
		AutoRegLib-1.6-49.jar                             |AutoRegLib                    |autoreglib                    |1.6-49              |DONE      |NOSIGNATURE
		Quark-r2.4-312.jar                                |Quark                         |quark                         |r2.4-312            |DONE      |NOSIGNATURE
		Regrowth-1.16.4-1.16.5-1.35.0.19.jar              |Regrowth Mod                  |regrowth                      |1.16.5-1.35.0.19    |DONE      |NOSIGNATURE
		BetterStrongholds-1.16.4-1.1.jar                  |YUNG's Better Strongholds     |betterstrongholds             |1.16.4-1.1          |DONE      |NOSIGNATURE
		structurize-0.13.177-ALPHA-universal.jar          |Structurize                   |structurize                   |0.13.177-ALPHA      |DONE      |NOSIGNATURE
		worldedit-mod-7.2.5-dist.jar                      |WorldEdit                     |worldedit                     |7.2.5+57d5ac9       |DONE      |NOSIGNATURE
		NaturesAura-34.2.jar                              |Nature's Aura                 |naturesaura                   |34.2                |DONE      |NOSIGNATURE
		minecolonies-0.14.219-ALPHA-universal.jar         |MineColonies                  |minecolonies                  |0.14.219-ALPHA      |DONE      |NOSIGNATURE
		architectury-1.17.21-forge.jar                    |Architectury                  |architectury                  |1.17.21             |DONE      |NOSIGNATURE
		ftb-gui-library-1605.2.1.41-forge.jar             |FTB GUI Library               |ftbguilibrary                 |1605.2.1.41         |DONE      |NOSIGNATURE
		AppleSkin-mc1.16.2-forge-1.0.14.jar               |AppleSkin                     |appleskin                     |1.0.14              |DONE      |NOSIGNATURE
		lootr-1.16.4-0.0.5.17.jar                         |Lootr                         |lootr                         |1.16.4-0.0.5.17     |DONE      |NOSIGNATURE
		ImmersiveRailroading-1.16.4-forge-1.8.0.1.jar     |Immersive Railroading         |immersiverailroading          |1.16.4-forge-1.8.0  |DONE      |NOSIGNATURE
		UniversalModCore-1.16.4-forge-1.0.1.jar           |Universal Mod Core            |universalmodcore              |1.0.1               |DONE      |NOSIGNATURE
		cc-tweaked-1.16.4-1.96.0.jar                      |CC: Tweaked                   |computercraft                 |1.96.0              |DONE      |NOSIGNATURE
		Colony4ComputerCraft-1.16.4-1.2.5.jar             |MineColonies for ComputerCraft|colony4cc                     |1.2.5               |DONE      |NOSIGNATURE
		cloth-config-4.11.26-forge.jar                    |Cloth Config v4 API           |cloth-config                  |4.11.26             |DONE      |NOSIGNATURE
		DynamicTrees-1.16.5-0.10.0-Beta16.jar             |Dynamic Trees                 |dynamictrees                  |1.16.5-0.10.0-Beta16|DONE      |NOSIGNATURE
		DynamicTreesPlus-1.16.5-0.1.0-Beta9.jar           |Dynamic Trees Plus            |dynamictreesplus              |1.16.5-0.1.0-Beta9  |DONE      |NOSIGNATURE
		DynamicTreesNaturesAura-1.16.5-1.2.2.jar          |Dynamic Trees for Nature's Aur|dtnaturesaura                 |1.16.5-1.2.2        |DONE      |NOSIGNATURE
		DynamicTreesQuark-1.16.5-2.0.4.jar                |Dynamic Trees for Quark       |dtquark                       |1.16.5-2.0.4        |DONE      |NOSIGNATURE
		DynamicTreesTraverse-1.16.5-2.2.0.jar             |Dynamic Trees for Traverse    |dttraverse                    |1.16.5-2.2.0        |DONE      |NOSIGNATURE
		chiselsandbits-0.3.4-RELEASE.jar                  |Chisels & bits                |chiselsandbits                |NONE                |DONE      |NOSIGNATURE
		BetterMineshafts-Forge-1.16.4-2.0.4.jar           |YUNG's Better Mineshafts      |bettermineshafts              |1.16.4-2.0.4        |DONE      |NOSIGNATURE
		geckolib-forge-1.16.5-3.0.41.jar                  |GeckoLib                      |geckolib3                     |3.0.41              |DONE      |NOSIGNATURE
		WailaHarvestability-mc1.16.x-forge-1.1.15.jar     |Waila Harvestability          |wailaharvestability           |1.1.15              |DONE      |NOSIGNATURE
	Crash Report UUID: fb12e247-5b02-4707-8a1f-acbea9b65321
	[Psi] Active spell: None
	Patchouli open book context: n/a
	Launched Version: forge-36.1.0
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: GeForce RTX 3090/PCIe/SSE2 GL version 4.6.0 NVIDIA 461.92, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: 
	Current Language: English (US)
	CPU: 12x Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz
	OptiFine Version: OptiFine_1.16.5_HD_U_G8
	OptiFine Build: 20210515-161946
	Render Distance Chunks: 32
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 461.92
	OpenGlRenderer: GeForce RTX 3090/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 12`

**Comment by cam72cam** [comment]
This was due to a bad cache item.  Remove the cache dir and try again.  I also rewrote the obj loader for the next version so it should be less of a problem
